# =============================================================
# DSM Combat Engine Rules
# Commit 12
# =============================================================


[COMBAT]


KILLED=PLAYER_KILL

SHOT=WEAPON_KILL

SUICIDE=PLAYER_SUICIDE

DIED=PLAYER_DEATH


[RANGE]


LONG_DISTANCE=LONG_DISTANCE_KILL


[TYPE]


PLAYER_PLAYER=PVP_KILL

PLAYER_ZOMBIE=PVE_KILL

PLAYER_ENVIRONMENT=PVE_DEATH