#!/usr/bin/env python3
from __future__ import annotations
from datetime import datetime,timedelta,timezone
import io,sys,tempfile,unittest
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
for path in (ROOT/"database",ROOT/"dashboard",ROOT/"core"):
 if str(path) not in sys.path:sys.path.insert(0,str(path))
from agent_instance_provisioning_repository import AgentInstanceProvisioningRepository
from artifact_transfer_repository import ArtifactTransferRepository
from backend import DatabaseConfig
from backend_factory import create_backend
from instance_backup_clone_repository import InstanceBackupCloneRepository
class CustomerBackupCloneE2ETest(unittest.TestCase):
 def setUp(self):
  self.temp=tempfile.TemporaryDirectory();self.root=Path(self.temp.name);self.backend=create_backend(DatabaseConfig(driver="sqlite",database=str(self.root/"capivara.db")));self.backend.initialize()
  with self.backend.transaction() as c:
   c.execute("INSERT INTO nodes(id,name,role,status) VALUES (?,?,?,?)",("controller-node","Controller","controller","active"));c.execute("INSERT INTO nodes(id,name,role,status) VALUES (?,?,?,?)",("agent-node-a","Agent A","agent","active"));c.execute("INSERT INTO nodes(id,name,role,status) VALUES (?,?,?,?)",("agent-node-b","Agent B","agent","active"));c.execute("INSERT INTO controllers(id,node_id,name,status) VALUES (?,?,?,?)",("controller-one","controller-node","Controller","active"));c.execute("INSERT INTO agents(id,controller_id,node_id,name,status) VALUES (?,?,?,?,?)",("agent-a","controller-one","agent-node-a","Agent A","active"));c.execute("INSERT INTO agents(id,controller_id,node_id,name,status) VALUES (?,?,?,?,?)",("agent-b","controller-one","agent-node-b","Agent B","active"));c.execute("INSERT INTO customers(id,controller_id,name,status) VALUES (?,?,?,?)",(1,"controller-one","Customer","active"));c.execute("INSERT INTO instances(id,node_id,game_id,runtime_id,name,status,controller_id,agent_id,customer_id) VALUES (?,?,?,?,?,?,?,?,?)",("target-instance","agent-node-b","minecraft","minecraft.java.vanilla","Restored Server","offline","controller-one","agent-b",1));c.execute("INSERT INTO instance_ports(instance_id,node_id,name,protocol,port,bind_address) VALUES (?,?,?,?,?,?)",("target-instance","agent-node-b","game","tcp",25565,"0.0.0.0"))
  self.artifacts=ArtifactTransferRepository(self.backend,self.root);self.artifacts.initialize();seed=self.artifacts.create(agent_id="agent-a",customer_id=1,direction="controller_to_agent",purpose="vault_seed",filename="source.tar.gz",requested_by="test",ttl_hours=24);seed=self.artifacts.stage_from_controller(seed["transfer_id"],io.BytesIO(b"capivara-backup"),len(b"capivara-backup"));self.source_path=Path(seed["controller_path"]);expires=(datetime.now(timezone.utc)+timedelta(hours=12)).isoformat().replace("+00:00","Z")
  with self.backend.transaction() as c:c.execute("INSERT INTO deleted_instance_backups(vault_id,customer_id,source_instance_id,source_instance_name,game_id,runtime_id,agent_id,status,artifact_path,size_bytes,sha256,created_at,expires_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)",("vault-source",1,"deleted-source","Old Server","minecraft","minecraft.java.vanilla","agent-a","ready",str(self.source_path),seed["size_bytes"],seed["sha256"],datetime.now(timezone.utc).isoformat(),expires,datetime.now(timezone.utc).isoformat()))
  self.provisioning=AgentInstanceProvisioningRepository(self.backend);self.provisioning.initialize();self.provision=self.provisioning.enqueue(agent_id="agent-b",instance_id="target-instance",environment_id="minecraft.java.vanilla",selector="1.21.8",selection={"provider":"test"},configuration={},desired_state="stopped",requested_by="owner");self.clones=InstanceBackupCloneRepository(self.backend,self.root);self.clones.initialize()
 def tearDown(self):self.backend.close();self.temp.cleanup()
 def test_full_cross_agent_clone_provision_transfer_restore_complete(self):
  clone,idempotent=self.clones.start(customer_id=1,source_vault_id="vault-source",target_instance_id="target-instance",target_agent_id="agent-b",provisioning_id=self.provision["provisioning_id"],requested_by="owner");self.assertFalse(idempotent);self.assertEqual(clone["status"],"provisioning");self.assertEqual(self.clones.reconcile(clone["clone_id"])["status"],"provisioning")
  self.provisioning.apply_result("agent-b",{"provisioning_id":self.provision["provisioning_id"],"instance_id":"target-instance","status":"completed","progress":100,"current_step":"completed"});clone=self.clones.reconcile(clone["clone_id"]);self.assertEqual(clone["status"],"transferring");self.assertTrue(clone["transfer_id"]);transfer=self.artifacts.get(clone["transfer_id"]);self.assertEqual(transfer["agent_id"],"agent-b");self.assertEqual(transfer["direction"],"controller_to_agent");self.assertEqual(transfer["purpose"],"backup_clone");self.assertTrue(self.source_path.exists())
  self.artifacts.apply_agent_result("agent-b",{"transfer_id":clone["transfer_id"],"status":"completed","transferred_bytes":transfer["size_bytes"]});clone=self.clones.reconcile(clone["clone_id"]);self.assertEqual(clone["status"],"restoring");self.assertTrue(clone["restore_job_id"]);job=self.clones.backups.get_job(clone["restore_job_id"]);self.assertEqual(job["instance_id"],"target-instance");self.assertEqual(job["action"],"restore");self.assertEqual(job["backup_id"],clone["imported_backup_id"])
  self.clones.backups.record_agent_state("agent-b",[{"command_id":clone["restore_job_id"],"instance_id":"target-instance","action":"restore","backup_id":clone["imported_backup_id"],"status":"completed","size_bytes":transfer["size_bytes"],"sha256":transfer["sha256"]}]);clone=self.clones.reconcile(clone["clone_id"]);self.assertEqual(clone["status"],"completed");self.assertIsNotNone(clone["completed_at"]);self.assertTrue(self.source_path.exists());same,again=self.clones.start(customer_id=1,source_vault_id="vault-source",target_instance_id="target-instance",target_agent_id="agent-b",provisioning_id=self.provision["provisioning_id"],requested_by="owner");self.assertTrue(again);self.assertEqual(same["clone_id"],clone["clone_id"])
 def test_source_policy_rejects_wrong_customer_game_and_runtime(self):
  with self.assertRaises(PermissionError):self.clones.validate_source("vault-source",2,"minecraft","minecraft.java.vanilla")
  with self.assertRaises(ValueError):self.clones.validate_source("vault-source",1,"dayz","dayz.stable")
  with self.assertRaises(ValueError):self.clones.validate_source("vault-source",1,"minecraft","minecraft.java.paper")
 def test_heartbeat_layer_reconciles_clone_after_agent_results(self):
  text=(ROOT/"dashboard/agent_remote_http.py").read_text(encoding="utf-8");self.assertIn("InstanceBackupCloneRepository",text);self.assertIn("reconcile_for_agent",text);self.assertIn("backup_clone_states",text)
if __name__=="__main__":unittest.main()
