#
# DSM Event Schema
#

[server]

SERVER_START
SERVER_STOP
SERVER_CRASH
SERVER_RESTART


[backup]

BACKUP_STARTED
BACKUP_CREATED
BACKUP_FAILED


[update]

UPDATE_STARTED
UPDATE_FINISHED
UPDATE_FAILED


[player]

PLAYER_JOIN
PLAYER_LEAVE
PLAYER_DEATH