#!/usr/bin/env bash

GAME_ID="http-fail-test"
GAME_NAME="HTTP Failure Test"

INSTALL_PROVIDER="http"
INSTALL_PACKAGE_ID="https://example.com/"
INSTALL_AUTH="anonymous"

INSTALL_DIR="/opt/dsm/test-failure/http-update/serverfiles"
EXECUTABLE="arquivo-que-nao-existe"

GAME_VARIANT="test"
GAME_VERSION="current"
GAME_BUILD="auto"

PROCESS_ENGINE="native"
