#!/usr/bin/env python3
"""Compile historical consolidated SQL into canonical Database Baseline v2."""
from __future__ import annotations
import re

_BACKENDS = {"postgresql", "sqlite", "mysql", "mariadb"}


def _customer_ddl(backend: str) -> str:
    if backend == "postgresql":
        return """CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT GENERATED ALWAYS AS ('CLI-' || CASE WHEN LENGTH(id::TEXT) >= 6 THEN id::TEXT ELSE LPAD(id::TEXT, 6, '0') END) STORED UNIQUE,
    controller_id TEXT NOT NULL,
    name TEXT NOT NULL,
    legal_name TEXT,
    email TEXT,
    phone TEXT,
    document_type TEXT CHECK (document_type IS NULL OR document_type IN ('cpf', 'cnpj', 'other')),
    document_number TEXT,
    account_email TEXT,
    sftp_username TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'cancelled')),
    registration_status TEXT NOT NULL DEFAULT 'managed' CHECK (registration_status IN ('managed', 'pending', 'active', 'disabled')),
    email_verified_at TIMESTAMPTZ,
    billing_provider TEXT,
    billing_customer_id TEXT,
    billing_status TEXT CHECK (billing_status IS NULL OR billing_status IN ('pending','active','past_due','suspended','cancelled','unlinked')),
    billing_synced_at TIMESTAMPTZ,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_billing_pair CHECK ((billing_provider IS NULL AND billing_customer_id IS NULL) OR (billing_provider IS NOT NULL AND billing_customer_id IS NOT NULL)),
    CONSTRAINT uq_customers_billing UNIQUE (billing_provider, billing_customer_id),
    CONSTRAINT fk_customers_controller FOREIGN KEY (controller_id) REFERENCES controllers(id) ON DELETE RESTRICT
);"""
    if backend == "sqlite":
        return """CREATE TABLE customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_code TEXT GENERATED ALWAYS AS ('CLI-' || printf('%06d', id)) STORED UNIQUE,
    controller_id TEXT NOT NULL,
    name TEXT NOT NULL,
    legal_name TEXT,
    email TEXT,
    phone TEXT,
    document_type TEXT CHECK (document_type IS NULL OR document_type IN ('cpf', 'cnpj', 'other')),
    document_number TEXT,
    account_email TEXT,
    sftp_username TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'cancelled')),
    registration_status TEXT NOT NULL DEFAULT 'managed' CHECK (registration_status IN ('managed', 'pending', 'active', 'disabled')),
    email_verified_at TEXT,
    billing_provider TEXT,
    billing_customer_id TEXT,
    billing_status TEXT CHECK (billing_status IS NULL OR billing_status IN ('pending','active','past_due','suspended','cancelled','unlinked')),
    billing_synced_at TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_billing_pair CHECK ((billing_provider IS NULL AND billing_customer_id IS NULL) OR (billing_provider IS NOT NULL AND billing_customer_id IS NOT NULL)),
    CONSTRAINT uq_customers_billing UNIQUE (billing_provider, billing_customer_id),
    CONSTRAINT fk_customers_controller FOREIGN KEY (controller_id) REFERENCES controllers(id) ON DELETE RESTRICT
);"""
    return """CREATE TABLE customers (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    customer_code VARCHAR(32) GENERATED ALWAYS AS (CONCAT('CLI-', CASE WHEN CHAR_LENGTH(CAST(id AS CHAR)) >= 6 THEN CAST(id AS CHAR) ELSE LPAD(CAST(id AS CHAR), 6, '0') END)) STORED UNIQUE,
    controller_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    legal_name VARCHAR(255),
    email VARCHAR(320),
    phone VARCHAR(64),
    document_type VARCHAR(16),
    document_number VARCHAR(64),
    account_email VARCHAR(320),
    sftp_username VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    registration_status VARCHAR(32) NOT NULL DEFAULT 'managed',
    email_verified_at TIMESTAMP NULL,
    billing_provider VARCHAR(64),
    billing_customer_id VARCHAR(255),
    billing_status VARCHAR(32),
    billing_synced_at TIMESTAMP NULL,
    metadata_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_document_type CHECK (document_type IS NULL OR document_type IN ('cpf', 'cnpj', 'other')),
    CONSTRAINT ck_customers_status CHECK (status IN ('active', 'suspended', 'cancelled')),
    CONSTRAINT ck_customers_registration_status CHECK (registration_status IN ('managed', 'pending', 'active', 'disabled')),
    CONSTRAINT ck_customers_billing_status CHECK (billing_status IS NULL OR billing_status IN ('pending','active','past_due','suspended','cancelled','unlinked')),
    CONSTRAINT ck_customers_billing_pair CHECK ((billing_provider IS NULL AND billing_customer_id IS NULL) OR (billing_provider IS NOT NULL AND billing_customer_id IS NOT NULL)),
    CONSTRAINT uq_customers_billing UNIQUE (billing_provider, billing_customer_id),
    CONSTRAINT fk_customers_controller FOREIGN KEY (controller_id) REFERENCES controllers(id) ON DELETE RESTRICT
);"""


def _password_state_ddl(backend: str) -> str:
    if backend == "postgresql":
        flag, timestamp = "BOOLEAN NOT NULL DEFAULT FALSE", "TIMESTAMPTZ"
    elif backend == "sqlite":
        flag, timestamp = "INTEGER NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1))", "TEXT"
    else:
        flag, timestamp = "TINYINT NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1))", "TIMESTAMP"
    username_type = "TEXT" if backend in {"postgresql", "sqlite"} else "VARCHAR(128)"
    return f"""CREATE TABLE customer_password_state (
    username {username_type} PRIMARY KEY,
    must_change_password {flag},
    updated_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_password_state_user FOREIGN KEY (username) REFERENCES dashboard_users(username) ON DELETE CASCADE
);"""


def _customer_fk_type(backend: str) -> str:
    return "BIGINT" if backend in {"postgresql", "mysql", "mariadb"} else "INTEGER"


def _system_user_text_type(backend: str, length: int) -> str:
    return "TEXT" if backend in {"postgresql", "sqlite"} else f"VARCHAR({length})"


def _strip_historical_comments(sql: str) -> str:
    lines = []
    for line in sql.splitlines():
        lowered = line.lower()
        if re.match(r"\s*--\s*source:\s*[0-9]{3}_", line, re.IGNORECASE):
            continue
        if re.search(r"\bmigration\s+[0-9]{3}\b", line, re.IGNORECASE):
            continue
        if "historical migration" in lowered:
            continue
        lines.append(line)
    return "\n".join(lines)


def _table_pattern(name: str) -> re.Pattern[str]:
    # Top-level closing parenthesis is column-zero in all canonical source
    # snapshots. Capturing only through that parenthesis works for both `);`
    # and MySQL/MariaDB `) ENGINE=InnoDB ...;` table suffixes.
    return re.compile(
        rf"(CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?{re.escape(name)}\s*\()(.*?)(\n\))",
        re.IGNORECASE | re.DOTALL,
    )


def _replace_customer_table(sql: str, backend: str) -> str:
    pattern = _table_pattern("customers")
    match = pattern.search(sql)
    if match is None:
        raise ValueError(f"{backend} baseline has no customers table")
    end = match.end()
    if backend in {"mysql", "mariadb"}:
        suffix = re.match(r"\s*ENGINE\s*=.*?;", sql[end:], re.IGNORECASE | re.DOTALL)
        if suffix is None:
            raise ValueError(f"{backend} customers table has no engine terminator")
        end += suffix.end()
    elif sql[end:end + 1] == ";":
        end += 1
    sql = sql[:match.start()] + _customer_ddl(backend) + sql[end:]
    return re.sub(r"\n?ALTER\s+TABLE\s+customers\b.*?;", "", sql, flags=re.IGNORECASE | re.DOTALL)


def _numeric_customer_foreign_keys(sql: str, backend: str) -> str:
    target = _customer_fk_type(backend)
    return re.sub(
        r"\bcustomer_id\s+(?:TEXT|VARCHAR\s*\(\s*\d+\s*\)|CHAR\s*\(\s*\d+\s*\))\b",
        f"customer_id {target}", sql, flags=re.IGNORECASE,
    )


def _dashboard_customer_fk(sql: str, backend: str) -> str:
    target = _customer_fk_type(backend)
    pattern = _table_pattern("dashboard_users")
    match = pattern.search(sql)
    if match is None:
        raise ValueError(f"{backend} baseline has no dashboard_users table")
    body = match.group(2)
    if re.search(r"\bcustomer_id\b", body, re.IGNORECASE):
        return sql
    scope = re.search(r"(\bscope_id\s+[^,\n]+,?)", body, re.IGNORECASE)
    if scope is None:
        raise ValueError(f"{backend} dashboard_users has no scope_id")
    body = body[:scope.start()] + scope.group(1) + f"\n\n    customer_id {target}," + body[scope.end():]
    stripped = body.rstrip()
    if not stripped.endswith(","):
        stripped += ","
    body = stripped + "\n\n    CONSTRAINT fk_dashboard_users_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE"
    return sql[:match.start()] + match.group(1) + body + match.group(3) + sql[match.end():]


def _dashboard_system_user_identity(sql: str, backend: str) -> str:
    pattern = _table_pattern("dashboard_users")
    match = pattern.search(sql)
    if match is None:
        raise ValueError(f"{backend} baseline has no dashboard_users table")
    body = match.group(2)
    if re.search(r"\bcorporate_email\b", body, re.IGNORECASE):
        return sql
    customer = re.search(r"(\bcustomer_id\s+[^,\n]+,?)", body, re.IGNORECASE)
    if customer is None:
        raise ValueError(f"{backend} dashboard_users has no customer_id")
    full_name_type = _system_user_text_type(backend, 255)
    email_type = _system_user_text_type(backend, 320)
    short_type = _system_user_text_type(backend, 128)
    fields = (
        f"\n\n    full_name {full_name_type},"
        f"\n    corporate_email {email_type} UNIQUE,"
        f"\n    phone {short_type},"
        f"\n    job_title {full_name_type},"
        f"\n    department {full_name_type},"
        f"\n    created_by {short_type},"
    )
    body = body[:customer.start()] + customer.group(1) + fields + body[customer.end():]
    return sql[:match.start()] + match.group(1) + body + match.group(3) + sql[match.end():]


def _ensure_password_state(sql: str, backend: str) -> str:
    if re.search(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?customer_password_state\b", sql, re.IGNORECASE):
        return sql
    return sql.rstrip() + "\n\n" + _password_state_ddl(backend) + "\n"


def _remove_schema_migration_ledger(sql: str) -> str:
    # schema_migrations may carry backend-specific table suffixes. Remove from
    # CREATE through the terminating semicolon without relying on `);`.
    pattern = _table_pattern("schema_migrations")
    match = pattern.search(sql)
    if match is None:
        return sql
    end = match.end()
    semicolon = sql.find(";", end)
    if semicolon >= 0:
        end = semicolon + 1
    return sql[:match.start()] + sql[end:]


def compile_baseline_v2(sql: str, backend: str) -> str:
    backend = str(backend or "").strip().lower()
    if backend == "postgres":
        backend = "postgresql"
    if backend not in _BACKENDS:
        raise ValueError(f"unsupported database backend: {backend}")
    result = _strip_historical_comments(sql)
    result = _replace_customer_table(result, backend)
    result = _numeric_customer_foreign_keys(result, backend)
    result = _dashboard_customer_fk(result, backend)
    result = _dashboard_system_user_identity(result, backend)
    result = _remove_schema_migration_ledger(result)
    result = _ensure_password_state(result, backend)
    result = re.sub(r"\n{4,}", "\n\n\n", result).strip() + "\n"
    return result


__all__ = ["compile_baseline_v2"]
