#!/usr/bin/env python3
"""Compile historical consolidated SQL into canonical Database Baseline v2.

The checked-in v41 SQL snapshots remain source material while the Baseline v2
branch is being finalized. Runtime database engines consume only the compiled,
final-state result and never replay numbered migrations.
"""

from __future__ import annotations

import re

_BACKENDS = {"postgresql", "sqlite", "mysql", "mariadb"}


def _customer_ddl(backend: str) -> str:
    if backend == "postgresql":
        return """CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code TEXT GENERATED ALWAYS AS (
        'CLI-' || CASE
            WHEN LENGTH(id::TEXT) >= 6 THEN id::TEXT
            ELSE LPAD(id::TEXT, 6, '0')
        END
    ) STORED UNIQUE,
    controller_id TEXT NOT NULL,
    name TEXT NOT NULL,
    legal_name TEXT,
    email TEXT,
    phone TEXT,
    document_type TEXT CHECK (
        document_type IS NULL OR document_type IN ('cpf', 'cnpj', 'other')
    ),
    document_number TEXT,
    account_email TEXT,
    sftp_username TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (
        status IN ('active', 'suspended', 'cancelled')
    ),
    registration_status TEXT NOT NULL DEFAULT 'managed' CHECK (
        registration_status IN ('managed', 'pending', 'active', 'disabled')
    ),
    email_verified_at TIMESTAMPTZ,
    billing_provider TEXT,
    billing_customer_id TEXT,
    billing_status TEXT CHECK (
        billing_status IS NULL OR billing_status IN (
            'pending','active','past_due','suspended','cancelled','unlinked'
        )
    ),
    billing_synced_at TIMESTAMPTZ,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_billing_pair CHECK (
        (billing_provider IS NULL AND billing_customer_id IS NULL)
        OR (billing_provider IS NOT NULL AND billing_customer_id IS NOT NULL)
    ),
    CONSTRAINT uq_customers_billing UNIQUE (billing_provider, billing_customer_id),
    CONSTRAINT fk_customers_controller FOREIGN KEY (controller_id)
        REFERENCES controllers(id) ON DELETE RESTRICT
);"""
    if backend == "sqlite":
        return """CREATE TABLE customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_code TEXT GENERATED ALWAYS AS (
        'CLI-' || printf('%06d', id)
    ) STORED UNIQUE,
    controller_id TEXT NOT NULL,
    name TEXT NOT NULL,
    legal_name TEXT,
    email TEXT,
    phone TEXT,
    document_type TEXT CHECK (
        document_type IS NULL OR document_type IN ('cpf', 'cnpj', 'other')
    ),
    document_number TEXT,
    account_email TEXT,
    sftp_username TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (
        status IN ('active', 'suspended', 'cancelled')
    ),
    registration_status TEXT NOT NULL DEFAULT 'managed' CHECK (
        registration_status IN ('managed', 'pending', 'active', 'disabled')
    ),
    email_verified_at TEXT,
    billing_provider TEXT,
    billing_customer_id TEXT,
    billing_status TEXT CHECK (
        billing_status IS NULL OR billing_status IN (
            'pending','active','past_due','suspended','cancelled','unlinked'
        )
    ),
    billing_synced_at TEXT,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_billing_pair CHECK (
        (billing_provider IS NULL AND billing_customer_id IS NULL)
        OR (billing_provider IS NOT NULL AND billing_customer_id IS NOT NULL)
    ),
    CONSTRAINT uq_customers_billing UNIQUE (billing_provider, billing_customer_id),
    CONSTRAINT fk_customers_controller FOREIGN KEY (controller_id)
        REFERENCES controllers(id) ON DELETE RESTRICT
);"""
    return """CREATE TABLE customers (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    customer_code VARCHAR(32) GENERATED ALWAYS AS (
        CONCAT(
            'CLI-',
            CASE
                WHEN CHAR_LENGTH(CAST(id AS CHAR)) >= 6 THEN CAST(id AS CHAR)
                ELSE LPAD(CAST(id AS CHAR), 6, '0')
            END
        )
    ) STORED UNIQUE,
    controller_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    legal_name VARCHAR(255),
    email VARCHAR(320),
    phone VARCHAR(64),
    document_type VARCHAR(16),
    document_number VARCHAR(64),
    account_email VARCHAR(320),
    sftp_username VARCHAR(64),
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    registration_status VARCHAR(32) NOT NULL DEFAULT 'managed',
    email_verified_at TIMESTAMP NULL,
    billing_provider VARCHAR(64),
    billing_customer_id VARCHAR(255),
    billing_status VARCHAR(32),
    billing_synced_at TIMESTAMP NULL,
    metadata_json JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_customers_document_type CHECK (
        document_type IS NULL OR document_type IN ('cpf', 'cnpj', 'other')
    ),
    CONSTRAINT ck_customers_status CHECK (
        status IN ('active', 'suspended', 'cancelled')
    ),
    CONSTRAINT ck_customers_registration_status CHECK (
        registration_status IN ('managed', 'pending', 'active', 'disabled')
    ),
    CONSTRAINT ck_customers_billing_status CHECK (
        billing_status IS NULL OR billing_status IN (
            'pending','active','past_due','suspended','cancelled','unlinked'
        )
    ),
    CONSTRAINT ck_customers_billing_pair CHECK (
        (billing_provider IS NULL AND billing_customer_id IS NULL)
        OR (billing_provider IS NOT NULL AND billing_customer_id IS NOT NULL)
    ),
    CONSTRAINT uq_customers_billing UNIQUE (billing_provider, billing_customer_id),
    CONSTRAINT fk_customers_controller FOREIGN KEY (controller_id)
        REFERENCES controllers(id) ON DELETE RESTRICT
);"""


def _password_state_ddl(backend: str) -> str:
    if backend == "postgresql":
        flag = "BOOLEAN NOT NULL DEFAULT FALSE"
        timestamp = "TIMESTAMPTZ"
    elif backend == "sqlite":
        flag = "INTEGER NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1))"
        timestamp = "TEXT"
    else:
        flag = "TINYINT NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1))"
        timestamp = "TIMESTAMP"
    return f"""CREATE TABLE customer_password_state (
    username {'TEXT' if backend in {'postgresql', 'sqlite'} else 'VARCHAR(128)'} PRIMARY KEY,
    must_change_password {flag},
    updated_at {timestamp} NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_password_state_user FOREIGN KEY (username)
        REFERENCES dashboard_users(username) ON DELETE CASCADE
);"""


def _customer_fk_type(backend: str) -> str:
    return "BIGINT" if backend in {"postgresql", "mysql", "mariadb"} else "INTEGER"


def _strip_historical_comments(sql: str) -> str:
    lines = []
    for line in sql.splitlines():
        lowered = line.lower()
        if re.match(r"\s*--\s*source:\s*[0-9]{3}_", line, re.IGNORECASE):
            continue
        if re.search(r"\bmigration\s+[0-9]{3}\b", line, re.IGNORECASE):
            continue
        if "historical migration" in lowered:
            continue
        lines.append(line)
    return "\n".join(lines)


def _replace_customer_table(sql: str, backend: str) -> str:
    pattern = re.compile(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?customers\s*\(.*?\n\);",
        re.IGNORECASE | re.DOTALL,
    )
    match = pattern.search(sql)
    if match is None:
        raise ValueError(f"{backend} baseline has no customers table")
    sql = sql[: match.start()] + _customer_ddl(backend) + sql[match.end() :]
    return re.sub(
        r"\n?ALTER\s+TABLE\s+customers\b.*?;",
        "",
        sql,
        flags=re.IGNORECASE | re.DOTALL,
    )


def _numeric_customer_foreign_keys(sql: str, backend: str) -> str:
    target = _customer_fk_type(backend)
    return re.sub(
        r"\bcustomer_id\s+(?:TEXT|VARCHAR\s*\(\s*\d+\s*\)|CHAR\s*\(\s*\d+\s*\))\b",
        f"customer_id {target}",
        sql,
        flags=re.IGNORECASE,
    )


def _dashboard_customer_fk(sql: str, backend: str) -> str:
    target = _customer_fk_type(backend)
    pattern = re.compile(
        r"(CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?dashboard_users\s*\()(.*?)(\n\);)",
        re.IGNORECASE | re.DOTALL,
    )
    match = pattern.search(sql)
    if match is None:
        raise ValueError(f"{backend} baseline has no dashboard_users table")
    body = match.group(2)
    if re.search(r"\bcustomer_id\b", body, re.IGNORECASE):
        return sql
    scope = re.search(r"(\bscope_id\s+[^,\n]+,?)", body, re.IGNORECASE)
    if scope is None:
        raise ValueError(f"{backend} dashboard_users has no scope_id")
    insertion = scope.group(1)
    replacement = insertion + f"\n\n    customer_id {target},"
    body = body[: scope.start()] + replacement + body[scope.end() :]
    stripped = body.rstrip()
    if not stripped.endswith(","):
        stripped += ","
    body = stripped + (
        "\n\n    CONSTRAINT fk_dashboard_users_customer "
        "FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE"
    )
    return sql[: match.start()] + match.group(1) + body + match.group(3) + sql[match.end() :]


def _ensure_password_state(sql: str, backend: str) -> str:
    if re.search(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?customer_password_state\b", sql, re.IGNORECASE):
        return sql
    # This table depends only on dashboard_users and is safe to append after the
    # complete source snapshot has defined user persistence.
    return sql.rstrip() + "\n\n" + _password_state_ddl(backend) + "\n"


def _remove_schema_migration_ledger(sql: str) -> str:
    return re.sub(
        r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?schema_migrations\s*\(.*?\n\);",
        "",
        sql,
        flags=re.IGNORECASE | re.DOTALL,
    )


def compile_baseline_v2(sql: str, backend: str) -> str:
    backend = str(backend or "").strip().lower()
    if backend == "postgres":
        backend = "postgresql"
    if backend not in _BACKENDS:
        raise ValueError(f"unsupported database backend: {backend}")
    result = _strip_historical_comments(sql)
    result = _replace_customer_table(result, backend)
    result = _numeric_customer_foreign_keys(result, backend)
    result = _dashboard_customer_fk(result, backend)
    result = _remove_schema_migration_ledger(result)
    result = _ensure_password_state(result, backend)
    result = re.sub(r"\n{4,}", "\n\n\n", result).strip() + "\n"
    return result


__all__ = ["compile_baseline_v2"]
