"use strict";

const API="/api";let currentUser=null;let selectedAgent=null;let infrastructureTopology=null;let telemetryTimer=null;
const $=id=>document.getElementById(id);
function authHeader(){const token=sessionStorage.getItem("dsm_auth");if(!token){location.replace("/login.html");throw new Error("authentication required")}return{Authorization:`Basic ${token}`,Accept:"application/json"}}
async function request(endpoint,options={}){const headers={...authHeader(),...(options.headers||{})};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(`${API}${endpoint}`,{...options,headers,cache:"no-store",credentials:"same-origin"});if(response.status===401){sessionStorage.clear();location.replace("/login.html");return null}const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||body.message||`HTTP ${response.status}`);return body}
function errorMessage(message=""){const box=$("agents-error");if(!box)return;if(!message){box.hidden=true;box.textContent="";return}box.hidden=false;box.textContent=message}
function bytes(value){const n=Number(value);if(!Number.isFinite(n))return"—";const units=["B","KB","MB","GB","TB"];let v=n,i=0;while(v>=1024&&i<units.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${units[i]}`}
function pct(value){const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1)}%`:"—"}
function duration(value){let n=Number(value);if(!Number.isFinite(n))return"—";const d=Math.floor(n/86400);n%=86400;const h=Math.floor(n/3600),m=Math.floor((n%3600)/60);return`${d?`${d}d `:""}${h}h ${m}m`}
function card(label,value){const node=document.createElement("article");node.className="range-card";const span=document.createElement("span");span.textContent=label;const strong=document.createElement("strong");strong.textContent=value??"—";node.append(span,strong);return node}
async function loadSidebar(){const target=$("sidebar-component");const response=await fetch("/components/sidebar.html",{cache:"no-store"});if(response.ok)target.innerHTML=await response.text();const logout=$("btn-logout");if(logout)logout.onclick=()=>{sessionStorage.clear();location.replace("/login.html")}}
function applyRole(){document.querySelectorAll(".admin-only").forEach(el=>el.style.display=currentUser.role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(el=>el.style.display=["admin","controller"].includes(currentUser.role)?"":"none");const force=$("force-wrapper");if(force)force.hidden=currentUser.role!=="admin"}
async function loadInfrastructure(){infrastructureTopology=await request("/infrastructure?active_only=true");return infrastructureTopology}
function collectDatacenters(value,result=[]){if(!value)return result;if(Array.isArray(value)){for(const item of value)collectDatacenters(item,result);return result}if(typeof value!=="object")return result;if(value.type==="datacenter"&&value.id)result.push(value);for(const child of Object.values(value))if(child&&typeof child==="object")collectDatacenters(child,result);return result}
function renderDatacenters(){const select=$("agent-datacenter");if(!select)return;const current=select.value;select.replaceChildren(new Option("Selecione um datacenter",""));const unique=new Map();for(const item of collectDatacenters(infrastructureTopology))if(item?.id)unique.set(String(item.id),item);for(const item of unique.values())select.append(new Option(item.name||String(item.id),String(item.id)));if(current)select.value=current}
function agentCard(agent){const node=document.createElement("article");node.className="agent-card";const title=document.createElement("h2");title.textContent=agent.name||agent.id;const status=document.createElement("div");status.className="agent-status";status.textContent=agent.status||"unknown";const info=document.createElement("p");info.textContent=`Agent: ${agent.id} · Node: ${agent.node_id||"—"} · Instâncias: ${agent.instance_count||0}`;const open=document.createElement("button");open.type="button";open.textContent="Abrir Agent";open.onclick=()=>loadAgent(agent.id);node.append(title,status,info,open);return node}
async function loadAgents(){errorMessage();try{const result=await request("/agents"),list=$("agents-list");list.replaceChildren();for(const agent of result.agents||[])list.append(agentCard(agent));if(!(result.agents||[]).length)list.textContent="Nenhum Agent cadastrado."}catch(error){errorMessage(error.message)}}
function rangeCard(item){const node=card(`${String(item.protocol||"").toUpperCase()} ${item.start_port}-${item.end_port}`,`${item.available} livres de ${item.capacity}`);if(item.near_exhaustion)node.classList.add("near-exhaustion");return node}
function renderIdentity(data){const a=data.agent||{},root=$("agent-identity-grid");root.replaceChildren(card("Agent",a.agent_id),card("Node",a.node_id),card("Hostname",a.hostname||a.node_name),card("Endereço",a.address),card("Sistema",`${a.os_name||"—"} ${a.architecture||""}`),card("Versão",a.capivara_version),card("Saúde",a.health_status),card("Último heartbeat",a.last_seen?new Date(a.last_seen).toLocaleString():"—"))}
function renderHost(data){const t=data.host_telemetry||{},root=$("agent-host-telemetry");root.replaceChildren(card("CPU",pct(t.cpu_percent)),card("RAM",pct(t.memory_percent)),card("RAM usada",bytes(t.memory_used_bytes)),card("RAM disponível",bytes(t.memory_available_bytes)),card("Disco",pct(t.storage_percent)),card("Disco livre",bytes(t.storage_free_bytes)),card("Load 1 / 5 / 15",[t.load1,t.load5,t.load15].map(v=>Number.isFinite(Number(v))?Number(v).toFixed(2):"—").join(" / ")),card("Uptime",duration(t.uptime_seconds)),card("Rede recebida",bytes(t.network_rx_bytes)),card("Rede enviada",bytes(t.network_tx_bytes)))}
function renderAgentProcess(data){const t=data.agent_telemetry||{},root=$("agent-process-telemetry");root.replaceChildren(card("CPU do Agent",pct(t.cpu_percent)),card("RAM do Agent",bytes(t.memory_bytes)),card("PID",t.pid??"—"),card("Threads",t.threads??"—"))}
function renderInstances(data){const root=$("agent-instance-resources");root.replaceChildren();for(const item of data.instances||[]){const node=document.createElement("article");node.className="agent-card";const title=document.createElement("h3");title.textContent=item.name||item.id;const owner=document.createElement("p");owner.textContent=`${item.game_id||"—"} · ${item.customer_name||item.customer_id||"Sem Customer"} · ${item.status||"—"}`;const t=item.telemetry||{},metrics=document.createElement("p");metrics.textContent=`CPU ${pct(t.cpu_percent)} · RAM ${bytes(t.memory_bytes)} · PID ${t.pid??"—"} · I/O R ${bytes(t.io_read_bytes)} · W ${bytes(t.io_write_bytes)}`;const link=document.createElement("a");link.className="button";link.href=`/customer-admin.html?id=${encodeURIComponent(item.customer_id||"")}&instance=${encodeURIComponent(item.id)}`;link.textContent=item.customer_id?"Administrar pelo cliente":"Ver cadastro";node.append(title,owner,metrics,link);root.append(node)}if(!(data.instances||[]).length)root.textContent="Nenhuma instância hospedada neste Agent."}
function renderGameData(data){const gd=data.game_data||{},installed=$("agent-game-data-installed"),jobs=$("agent-game-data-jobs");installed.replaceChildren();for(const item of gd.installed||[])installed.append(card(item.environment_id,item.selector||item.status||"instalado"));if(!(gd.installed||[]).length)installed.textContent="Nenhum game-data concluído registrado.";jobs.replaceChildren();for(const item of (gd.jobs||[]).slice(0,10))jobs.append(card(`${item.environment_id||"runtime"} · ${item.action||"install"}`,`${item.status||"—"}${item.updated_at?` · ${new Date(item.updated_at).toLocaleString()}`:""}`));if(!(gd.jobs||[]).length)jobs.textContent="Nenhuma operação registrada."}
function renderLogs(data){$("agent-recent-logs").textContent=(data.recent_logs||[]).join("\n")||"Nenhum log recebido."}
async function loadAgentDetail(){if(!selectedAgent)return;const data=await request(`/admin/agent/detail?agent_id=${encodeURIComponent(selectedAgent)}`);renderIdentity(data);renderHost(data);renderAgentProcess(data);renderInstances(data);renderGameData(data);renderLogs(data);const a=data.agent||{};$("agent-detail-meta").textContent=`${a.hostname||a.node_name||selectedAgent} · ${a.health_status||"unknown"} · ${a.os_name||"—"}`}
async function loadAgent(agentId){errorMessage();try{const result=await request(`/agent/ports?agent_id=${encodeURIComponent(agentId)}`);selectedAgent=result.agent.id;const detail=$("agent-detail");detail.hidden=false;$("agent-detail-title").textContent=`${result.agent.name} · ${result.agent.id}`;const ranges=$("agent-ranges");ranges.replaceChildren();for(const item of result.ranges||[])ranges.append(rangeCard(item));const conflicts=$("agent-conflicts");conflicts.className=result.conflict_count?"conflict-box conflict-danger":"conflict-box";conflicts.textContent=result.conflict_count?`${result.conflict_count} reserva(s) fora das faixas configuradas.`:"Nenhum conflito persistente detectado.";const first=(result.ranges||[])[0];if(first){$("range-start").value=first.start_port;$("range-end").value=first.end_port}await loadAgentDetail();history.replaceState(null,"",`/agents.html?agent=${encodeURIComponent(selectedAgent)}`);if(telemetryTimer)clearInterval(telemetryTimer);telemetryTimer=setInterval(()=>loadAgentDetail().catch(error=>errorMessage(error.message)),5000);detail.scrollIntoView({behavior:"smooth",block:"start"})}catch(error){errorMessage(error.message)}}
async function loadGameCatalog(){const select=$("agent-game-data-runtime");try{const data=await request("/catalog/runtimes"),items=Array.isArray(data)?data:(data.runtimes||[]);select.replaceChildren(new Option("Selecione um ambiente",""));for(const runtime of items){const option=new Option(`${runtime.name||runtime.id}${runtime.game?` · ${runtime.game}`:""}`,runtime.id);select.append(option)}select.disabled=!items.length;if(!items.length)select.replaceChildren(new Option("Nenhum ambiente disponível",""))}catch(error){select.replaceChildren(new Option("Falha ao carregar catálogo",""));select.disabled=true}}
async function installGameData(){if(!selectedAgent)throw new Error("Selecione um Agent.");const environment_id=$("agent-game-data-runtime").value;if(!environment_id)throw new Error("Selecione um ambiente de execução.");const selector=$("agent-game-data-selector").value.trim()||"current";const feedback=$("agent-game-data-feedback");feedback.textContent="Enfileirando instalação no Agent…";const result=await request("/agents/game-data",{method:"POST",body:JSON.stringify({agent_id:selectedAgent,environment_id,selector,action:"install"})});feedback.textContent=`Operação ${result.job_id||""} enfileirada para ${selectedAgent}.`;await loadAgentDetail()}
async function saveAgentLocation(event){event.preventDefault();if(!selectedAgent){errorMessage("Selecione um Agent.");return}const datacenter=$("agent-datacenter").value;if(!datacenter){errorMessage("Selecione um datacenter.");return}const latitude=$("agent-latitude").value.trim(),longitude=$("agent-longitude").value.trim();try{const result=await request("/agent/location",{method:"POST",body:JSON.stringify({agent_id:selectedAgent,datacenter_id:datacenter,latitude:latitude===""?null:Number(latitude),longitude:longitude===""?null:Number(longitude),public_host:$("agent-public-host").value.trim()||null,status:$("agent-location-status").value})});errorMessage();await loadInfrastructure();renderDatacenters();$("agent-datacenter").value=result.datacenter_id||""}catch(error){errorMessage(error.message)}}
async function saveRange(event){event.preventDefault();if(!selectedAgent){errorMessage("Selecione um Agent.");return}try{await request("/agent/ports/set",{method:"POST",body:JSON.stringify({agent_id:selectedAgent,protocol:$("range-protocol").value,start_port:Number($("range-start").value),end_port:Number($("range-end").value),force:$("range-force").checked})});await loadAgent(selectedAgent);await loadAgents()}catch(error){errorMessage(error.message)}}
async function initialize(){try{await loadSidebar();currentUser=await request("/whoami");if(!["admin","controller"].includes(currentUser.role))throw new Error("Você não possui permissão para administrar Agents.");applyRole();$("refresh-agents").onclick=loadAgents;$("agent-detail-refresh").onclick=()=>loadAgentDetail().catch(error=>errorMessage(error.message));$("agent-range-form").onsubmit=saveRange;$("agent-location-form").onsubmit=saveAgentLocation;$("agent-game-data-install").onclick=()=>installGameData().catch(error=>{$("agent-game-data-feedback").textContent=error.message});await Promise.all([loadInfrastructure(),loadGameCatalog()]);renderDatacenters();await loadAgents();const requested=new URLSearchParams(location.search).get("agent");if(requested)await loadAgent(requested)}catch(error){errorMessage(error.message)}}
window.addEventListener("beforeunload",()=>{if(telemetryTimer)clearInterval(telemetryTimer)});document.addEventListener("DOMContentLoaded",initialize);
