(function(){"use strict";
const el=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";let collapsed=false;const params=new URLSearchParams(location.search);const agentId=params.get("agent_id")||params.get("id")||"";
async function request(path){const r=await fetch(path,{headers:{Authorization:"Basic "+auth(),Accept:"application/json"}});if(r.status===401){sessionStorage.clear();location.replace("login.html");throw new Error("Sessão expirada");}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p}function text(id,v){const n=el(id);if(n)n.textContent=v??"—"}function value(v,f="—"){return v===null||v===undefined||v===""?f:String(v)}function heartbeat(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("pt-BR")}
function applySidebar(c){collapsed=c;document.body.classList.toggle("cap-sidebar-collapsed",c);localStorage.setItem("cap_sidebar_collapsed",c?"1":"0")}
function bindMenu(){el("agent-detail-menu-toggle")?.addEventListener("click",()=>{if(innerWidth<=760){document.body.classList.toggle("sidebar-open");return}applySidebar(!collapsed)})}
async function sidebar(){const host=el("sidebar-component");const r=await fetch("components/sidebar-v3.html");if(!r.ok)throw new Error(`sidebar HTTP ${r.status}`);host.innerHTML=await r.text();host.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="agents.html"));host.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>document.body.classList.remove("sidebar-open")));el("btn-logout")?.addEventListener("click",()=>{sessionStorage.clear();location.replace("login.html")});const who=await request("/api/whoami");text("current-user",`${who.username} (${who.role})`);text("agent-detail-user",who.username);text("agent-detail-role",who.role);document.querySelectorAll(".admin-only").forEach(x=>x.style.display=who.role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(x=>x.style.display=["admin","controller"].includes(who.role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(x=>x.style.display=["admin","controller","operator"].includes(who.role)?"":"none");if(!["admin","controller"].includes(who.role))throw new Error("Você não possui permissão para administrar Agents.");applySidebar(localStorage.getItem("cap_sidebar_collapsed")==="1")}
function rangeCard(r){const n=document.createElement("div");n.className="cap-range-card";const protocol=value(r.protocol,"").toUpperCase();n.innerHTML=`<strong>${protocol} ${value(r.start_port,"?")}-${value(r.end_port,"?")}</strong><span>${value(r.available,0)} disponíveis · ${value(r.reserved,0)} reservadas · ${value(r.usage_pct,0)}% de uso</span>`;return n}
async function load(){if(!agentId)throw new Error("Agent não informado na URL.");const result=await request(`/api/agent/ports?agent_id=${encodeURIComponent(agentId)}`);const a=result.agent||{};text("agent-detail-title",`${value(a.name||a.hostname||a.node_id||a.id,"Agent")} · ${value(a.id,agentId)}`);text("detail-hostname",a.hostname||a.name||a.node_id||a.id);text("detail-address",a.address||a.ip||a.public_host);text("detail-system",a.system||a.os||a.os_name||a.platform);text("detail-version",a.version||a.capivara_version||a.agent_version||a.installed_version);text("detail-health",a.health||a.health_status||a.status);text("detail-heartbeat",heartbeat(a.last_heartbeat||a.heartbeat_at||a.last_seen||a.updated_at));text("detail-datacenter",a.datacenter_name||a.datacenter||a.location_name||a.location);text("detail-region",a.region_name||a.region||a.region_id);text("detail-public-host",a.public_host||a.address||a.ip);text("detail-node",a.node_id||a.hostname||a.id);const ranges=el("detail-ranges");ranges.replaceChildren(...(Array.isArray(result.ranges)?result.ranges:[]).map(rangeCard));if(!ranges.children.length){const empty=document.createElement("div");empty.className="cap-detail-note";empty.textContent="Nenhuma faixa de portas configurada.";ranges.appendChild(empty)}text("detail-conflicts",result.conflict_count?`${result.conflict_count} conflito(s) persistente(s) detectado(s).`:"Nenhum conflito persistente detectado.")}
async function refresh(){const b=el("refresh-agent-detail");if(b)b.disabled=true;const box=el("agent-detail-error");try{await load();box.hidden=true}catch(e){box.hidden=false;box.textContent=e.message}finally{if(b)b.disabled=false}}
async function init(){if(!auth()){location.replace("login.html");return}bindMenu();el("refresh-agent-detail")?.addEventListener("click",refresh);try{await sidebar();await refresh()}catch(e){const box=el("agent-detail-error");box.hidden=false;box.textContent=e.message}}
document.addEventListener("DOMContentLoaded",init)})();
