(function(){"use strict";
const state={agents:[],operationalAgents:[],filter:"all",lifecycle:"operational",query:"",sidebarCollapsed:false};const el=id=>document.getElementById(id);const controllerHeaders=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
async function request(path,options={}){const headers={...controllerHeaders()};if(options.body)headers["Content-Type"]="application/json";const r=await fetch(path,{...options,headers,credentials:"same-origin",cache:options.cache||"no-store"});if(r.status===401){location.replace("/login.html");throw new Error("Sessão expirada");}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.message||p.error||`HTTP ${r.status}`);return p;}
function applySidebarState(c){state.sidebarCollapsed=c;document.body.classList.toggle("cap-sidebar-collapsed",c);localStorage.setItem("cap_sidebar_collapsed",c?"1":"0")}
function bindMenu(){el("agents-menu-toggle")?.addEventListener("click",()=>{if(window.innerWidth<=760){document.body.classList.toggle("sidebar-open");return}applySidebarState(!state.sidebarCollapsed)});}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"})}finally{location.replace("/login.html")}}
async function loadSidebar(){const host=el("sidebar-component");if(!host)return;const r=await fetch("components/sidebar-v3.html",{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error(`sidebar HTTP ${r.status}`);host.innerHTML=await r.text();host.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="agents.html"));host.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>document.body.classList.remove("sidebar-open")));el("btn-logout")?.addEventListener("click",logout);const who=await request("/api/whoami");el("current-user").textContent=`${who.username} (${who.role})`;el("agents-user-name").textContent=who.username||"—";el("agents-user-role").textContent=who.role||"—";document.querySelectorAll(".admin-only").forEach(x=>x.style.display=who.role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(x=>x.style.display=["admin","controller"].includes(who.role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(x=>x.style.display=["admin","controller","operator"].includes(who.role)?"":"none");if(!["admin","controller"].includes(who.role))throw new Error("Você não possui permissão para administrar Agents.");applySidebarState(localStorage.getItem("cap_sidebar_collapsed")==="1");}
function healthy(a){const s=String(a.health_status||a.health||a.status||"").toLowerCase();return ["online","healthy","ok","active"].includes(s)}function txt(v,f="—"){return v===null||v===undefined||v===""?f:String(v)}function escapeHtml(v){return txt(v,"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function heartbeat(a){const value=a.last_heartbeat||a.heartbeat_at||a.last_seen||a.updated_at;if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?txt(value):d.toLocaleString("pt-BR")}
function steamState(a){const caps=a.capabilities||{},detail=caps.steamcmd_status||{};if(detail.functional||caps.steamcmd===true)return{state:"ready",label:"SteamCMD funcionando"};if(detail.installed)return{state:"error",label:"SteamCMD com problema"};return{state:"missing",label:"SteamCMD não instalado"}}
function card(a){const online=healthy(a),id=txt(a.id,""),name=txt(a.name||a.hostname||a.node_id||a.id,"Agent"),address=txt(a.address||a.ip||a.public_host),dc=txt(a.datacenter_name||a.datacenter||a.location_name||a.location),version=txt(a.capivara_version||a.agent_version||a.version),instances=Number(a.instance_count||0)||0,steam=steamState(a);const node=document.createElement("article");node.className=`cap-agent-card ${online?"online":"offline"}`;node.innerHTML=`<div class="cap-agent-card-head"><div><h3>${escapeHtml(name)}</h3><div class="sub">${escapeHtml(id)}</div></div><span class="cap-agent-badge ${online?"online":"offline"}">${online?"Online":"Offline"}</span></div><div class="cap-agent-meta"><div><span>Endereço</span><strong>${escapeHtml(address)}</strong></div><div><span>Datacenter</span><strong>${escapeHtml(dc)}</strong></div><div><span>Versão</span><strong>${escapeHtml(version)}</strong></div><div><span>Heartbeat</span><strong>${escapeHtml(heartbeat(a))}</strong></div></div><div class="cap-steam-status" data-state="${steam.state}"><span>${escapeHtml(steam.label)}</span>${steam.state!=="ready"&&online?`<button type="button" data-install-steamcmd="${escapeHtml(id)}">Instalar SteamCMD</button>`:""}</div><div class="cap-agent-actions"><a class="detail" href="agent-details.html?agent_id=${encodeURIComponent(id)}">Detalhes</a><a class="instances" href="servers.html?agent=${encodeURIComponent(id)}">${instances} instância(s)</a></div>`;return node}
async function followSteamJob(jobId,button){for(let attempt=0;attempt<180;attempt++){const job=await request(`/api/agents/game-data/jobs?job_id=${encodeURIComponent(jobId)}`);button.textContent=job.status==="running"?`Instalando… ${Number(job.progress||0)}%`:"Aguardando Agent…";if(job.status==="completed"){button.textContent="Instalado";await new Promise(resolve=>setTimeout(resolve,35000));await load();return}if(job.status==="failed")throw new Error(job.last_error||job.result?.error||"Não foi possível instalar o SteamCMD.");await new Promise(resolve=>setTimeout(resolve,2000))}throw new Error("O Agent não concluiu a instalação dentro do tempo esperado.")}
function steamErrorMessage(error){const raw=String(error||'');if(/cannot execute: required file not found/i.test(raw))return'Falta o suporte Linux para aplicativos de 32 bits.';return raw||'Não foi possível instalar o SteamCMD.'}
async function installSteam(button){const agentId=button.dataset.installSteamcmd;if(!agentId)return;button.disabled=true;button.textContent="Preparando…";try{const job=await request("/api/agents/game-data",{method:"POST",body:JSON.stringify({agent_id:agentId,environment_id:"_system.steamcmd",selector:"current",action:"install-steamcmd"})});await followSteamJob(job.job_id,button)}catch(e){button.disabled=false;button.textContent="Tentar novamente";const status=button.closest('.cap-steam-status');if(status){status.dataset.state='error';let details=status.querySelector('details');if(!details){details=document.createElement('details');details.innerHTML='<summary>Ver detalhes</summary><p></p>';status.appendChild(details)}details.querySelector('p').textContent=steamErrorMessage(e.message)}const box=el("agents-error");box.hidden=false;box.textContent=`SteamCMD: ${steamErrorMessage(e.message)}`}}
function render(){const q=state.query.trim().toLowerCase(),visible=state.agents.filter(a=>{const online=healthy(a);if(state.filter==="online"&&!online)return false;if(state.filter==="offline"&&online)return false;if(!q)return true;return [a.id,a.name,a.hostname,a.node_id,a.address,a.ip,a.public_host,a.datacenter_name,a.datacenter,a.location_name,a.location].some(v=>String(v||"").toLowerCase().includes(q))});const operational=state.operationalAgents;el("agents-list").replaceChildren(...visible.map(card));el("agents-empty").hidden=visible.length>0;el("agents-summary-text").textContent=state.lifecycle==="decommissioned"?`${visible.length} de ${state.agents.length} Agent(s) desativado(s) / removido(s) exibido(s).`:`${visible.length} de ${state.agents.length} Agent(s) operacional(is) exibido(s).`;el("agents-total").textContent=operational.length;el("agents-online").textContent=operational.filter(healthy).length;el("agents-offline").textContent=operational.filter(a=>!healthy(a)).length;el("agents-instances").textContent=operational.reduce((sum,a)=>sum+(Number(a.instance_count||0)||0),0)}
async function load(){const btn=el("refresh-agents");if(btn)btn.disabled=true;el("agents-summary-text").textContent="Sincronizando Agents...";try{const operationalResult=await request("/api/agents");state.operationalAgents=Array.isArray(operationalResult)?operationalResult:(Array.isArray(operationalResult.agents)?operationalResult.agents:[]);if(state.lifecycle==="operational"){state.agents=state.operationalAgents}else{const lifecycleResult=await request(`/api/agents?lifecycle=${encodeURIComponent(state.lifecycle)}`);state.agents=Array.isArray(lifecycleResult)?lifecycleResult:(Array.isArray(lifecycleResult.agents)?lifecycleResult.agents:[])}render();el("agents-error").hidden=true}catch(e){state.agents=[];render();el("agents-error").hidden=false;el("agents-error").textContent=e.message}finally{if(btn)btn.disabled=false}}
function bind(){bindMenu();el("refresh-agents")?.addEventListener("click",load);el("agents-list")?.addEventListener("click",event=>{const button=event.target.closest("[data-install-steamcmd]");if(button)installSteam(button)});el("agent-search")?.addEventListener("input",e=>{state.query=e.target.value;render()});document.querySelectorAll(".cap-agent-filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".cap-agent-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;render()}));document.querySelectorAll(".cap-agent-lifecycle-filter").forEach(b=>b.addEventListener("click",async()=>{document.querySelectorAll(".cap-agent-lifecycle-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.lifecycle=b.dataset.lifecycle||"operational";state.filter="all";document.querySelectorAll(".cap-agent-filter").forEach(x=>x.classList.toggle("active",x.dataset.filter==="all"));await load()}))}
async function init(){bind();try{await loadSidebar();await load()}catch(e){const box=el("agents-error");if(box){box.hidden=false;box.textContent=e.message}}}
document.addEventListener("DOMContentLoaded",init)})();
