(function(){"use strict";
const state={agents:[],filter:"all",query:"",sidebarCollapsed:false};const el=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";
async function request(path){const r=await fetch(path,{headers:{Authorization:"Basic "+auth(),Accept:"application/json"}});if(r.status===401){sessionStorage.clear();location.replace("login.html");throw new Error("Sessão expirada");}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p;}
function applySidebarState(c){state.sidebarCollapsed=c;document.body.classList.toggle("cap-sidebar-collapsed",c);localStorage.setItem("cap_sidebar_collapsed",c?"1":"0")}
function bindMenu(){el("agents-menu-toggle")?.addEventListener("click",()=>{if(window.innerWidth<=760){document.body.classList.toggle("sidebar-open");return}applySidebarState(!state.sidebarCollapsed)});}
async function loadSidebar(){const host=el("sidebar-component");if(!host)return;const r=await fetch("components/sidebar-v3.html");if(!r.ok)throw new Error(`sidebar HTTP ${r.status}`);host.innerHTML=await r.text();host.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="agents.html"));host.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>document.body.classList.remove("sidebar-open")));el("btn-logout")?.addEventListener("click",()=>{sessionStorage.clear();location.replace("login.html")});const who=await request("/api/whoami");el("current-user").textContent=`${who.username} (${who.role})`;el("agents-user-name").textContent=who.username||"—";el("agents-user-role").textContent=who.role||"—";document.querySelectorAll(".admin-only").forEach(x=>x.style.display=who.role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(x=>x.style.display=["admin","controller"].includes(who.role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(x=>x.style.display=["admin","controller","operator"].includes(who.role)?"":"none");if(!["admin","controller"].includes(who.role))throw new Error("Você não possui permissão para administrar Agents.");applySidebarState(localStorage.getItem("cap_sidebar_collapsed")==="1");}
function healthy(a){const s=String(a.health_status||a.health||a.status||"").toLowerCase();return ["online","healthy","ok","active"].includes(s)}function txt(v,f="—"){return v===null||v===undefined||v===""?f:String(v)}function escapeHtml(v){return txt(v,"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function heartbeat(a){const value=a.last_heartbeat||a.heartbeat_at||a.last_seen||a.updated_at;if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?txt(value):d.toLocaleString("pt-BR")}
function card(a){const online=healthy(a),id=txt(a.id,""),name=txt(a.name||a.hostname||a.node_id||a.id,"Agent"),address=txt(a.address||a.ip||a.public_host),dc=txt(a.datacenter_name||a.datacenter||a.location_name||a.location),version=txt(a.version||a.agent_version||a.capivara_version),instances=Number(a.instance_count||0)||0;const node=document.createElement("article");node.className=`cap-agent-card ${online?"online":"offline"}`;node.innerHTML=`<div class="cap-agent-card-head"><div><h3>${escapeHtml(name)}</h3><div class="sub">${escapeHtml(id)}</div></div><span class="cap-agent-badge ${online?"online":"offline"}">${online?"Online":"Offline"}</span></div><div class="cap-agent-meta"><div><span>Endereço</span><strong>${escapeHtml(address)}</strong></div><div><span>Datacenter</span><strong>${escapeHtml(dc)}</strong></div><div><span>Versão</span><strong>${escapeHtml(version)}</strong></div><div><span>Heartbeat</span><strong>${escapeHtml(heartbeat(a))}</strong></div></div><div class="cap-agent-actions"><a class="detail" href="agent-details.html?agent_id=${encodeURIComponent(id)}">Detalhes</a><a class="instances" href="servers.html?agent=${encodeURIComponent(id)}">${instances} instância(s)</a></div>`;return node}
function render(){const q=state.query.trim().toLowerCase(),visible=state.agents.filter(a=>{const online=healthy(a);if(state.filter==="online"&&!online)return false;if(state.filter==="offline"&&online)return false;if(!q)return true;return [a.id,a.name,a.hostname,a.node_id,a.address,a.ip,a.public_host,a.datacenter_name,a.datacenter,a.location_name,a.location].some(v=>String(v||"").toLowerCase().includes(q))});el("agents-list").replaceChildren(...visible.map(card));el("agents-empty").hidden=visible.length>0;el("agents-summary-text").textContent=`${visible.length} de ${state.agents.length} Agent(s) exibido(s).`;el("agents-total").textContent=state.agents.length;el("agents-online").textContent=state.agents.filter(healthy).length;el("agents-offline").textContent=state.agents.filter(a=>!healthy(a)).length;el("agents-instances").textContent=state.agents.reduce((sum,a)=>sum+(Number(a.instance_count||0)||0),0)}
async function load(){const btn=el("refresh-agents");if(btn)btn.disabled=true;el("agents-summary-text").textContent="Sincronizando Agents...";try{const result=await request("/api/agents");state.agents=Array.isArray(result)?result:(Array.isArray(result.agents)?result.agents:[]);render();el("agents-error").hidden=true}catch(e){state.agents=[];render();el("agents-error").hidden=false;el("agents-error").textContent=e.message}finally{if(btn)btn.disabled=false}}
function bind(){bindMenu();el("refresh-agents")?.addEventListener("click",load);el("agent-search")?.addEventListener("input",e=>{state.query=e.target.value;render()});document.querySelectorAll(".cap-agent-filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".cap-agent-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;render()}))}
async function init(){if(!auth()){location.replace("login.html");return}bind();try{await loadSidebar();await load()}catch(e){const box=el("agents-error");if(box){box.hidden=false;box.textContent=e.message}}}
document.addEventListener("DOMContentLoaded",init)})();
