(function(){
"use strict";
const $=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";let timer=null;
function bytes(value){const n=Number(value);if(!Number.isFinite(n))return "—";const units=["B","KB","MB","GB","TB"];let v=n,i=0;while(v>=1024&&i<units.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${units[i]}`}
function percent(value){const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1)}%`:"—"}
function duration(value){let seconds=Number(value);if(!Number.isFinite(seconds))return "—";const days=Math.floor(seconds/86400);seconds%=86400;const hours=Math.floor(seconds/3600);const minutes=Math.floor((seconds%3600)/60);return `${days?`${days}d `:""}${hours}h ${minutes}m`}
function bar(id,value){const node=$(id);if(node)node.style.width=`${Math.max(0,Math.min(100,Number(value)||0))}%`}
async function request(path){const response=await fetch(path,{headers:{Authorization:`Basic ${auth()}`,Accept:"application/json"},cache:"no-store",credentials:"same-origin"});if(response.status===401){sessionStorage.removeItem("dsm_auth");location.replace("/login.html");throw new Error("Sessão encerrada")};const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||data.error||`HTTP ${response.status}`);return data}
async function sidebar(){const target=$("sidebar-component");if(!target)return;const response=await fetch("/components/sidebar.html",{cache:"no-store"});if(response.ok)target.innerHTML=await response.text();const logout=$("btn-logout");if(logout)logout.onclick=()=>{sessionStorage.clear();location.replace("/login.html")}}
function metricCard(agent){const card=document.createElement("article");card.className="agent-card infrastructure-agent-card";const health=String(agent.health_status||"offline").toLowerCase();card.dataset.health=health;const title=document.createElement("h3");title.textContent=agent.hostname||agent.agent_id;const status=document.createElement("strong");status.className=`status ${health}`;status.textContent=health.toUpperCase();const meta=document.createElement("p");meta.textContent=`${agent.agent_id} · Node ${agent.node_id||"—"} · ${agent.os_name||"—"} ${agent.architecture||""}`;const instances=document.createElement("p");instances.textContent=`${agent.instance_count||0} instância(s)`;const host=document.createElement("p");host.textContent=`Host: CPU ${percent(agent.host?.cpu_percent)} · RAM ${percent(agent.host?.memory_percent)} · Disco ${percent(agent.host?.storage_percent)}`;const process=document.createElement("p");process.textContent=`Agent: CPU ${percent(agent.agent?.cpu_percent)} · RAM ${bytes(agent.agent?.memory_bytes)}`;const link=document.createElement("a");link.className="button";link.href=`/agents.html?agent=${encodeURIComponent(agent.agent_id)}`;link.textContent="Detalhes do Agent";card.append(title,status,meta,instances,host,process,link);return card}
function render(data){const counts=data.agent_counts||{};$("infra-agents-total").textContent=counts.total??0;$("infra-agents-online").textContent=counts.online??0;$("infra-agents-degraded").textContent=counts.degraded??0;$("infra-agents-offline").textContent=counts.offline??0;$("infra-instance-count").textContent=data.instance_count??0;const controller=data.controller||{},memory=controller.memory||{},storage=controller.storage||{},process=controller.dashboard_process||{},load=controller.load||{};$("controller-cpu").textContent=percent(controller.cpu_percent);$("controller-ram").textContent=percent(memory.used_percent);$("controller-disk").textContent=percent(storage.used_percent);bar("controller-cpu-bar",controller.cpu_percent);bar("controller-ram-bar",memory.used_percent);bar("controller-disk-bar",storage.used_percent);$("controller-load").textContent=[load.load1,load.load5,load.load15].map(v=>Number.isFinite(Number(v))?Number(v).toFixed(2):"—").join(" / ");$("controller-uptime").textContent=duration(controller.uptime_seconds);$("controller-process-cpu").textContent=percent(process.cpu_percent);$("controller-process-ram").textContent=bytes(process.rss_bytes);$("controller-collected-at").textContent=controller.collected_at?new Date(controller.collected_at).toLocaleTimeString():"—";const root=$("infra-agent-list");root.replaceChildren();for(const agent of data.agents||[])root.append(metricCard(agent));if(!(data.agents||[]).length)root.textContent="Nenhum Agent cadastrado.";$("infra-error").hidden=true}
function renderOperations(data){$("active-incidents-count").textContent=data.active_incidents??0;$("critical-incidents-count").textContent=data.critical_incidents??0;$("active-alerts-count").textContent=data.active_alerts??0;const root=$("active-incidents-list");root.replaceChildren();const items=data.incidents||[];if(!items.length){root.textContent="Nenhum incidente ativo.";return}for(const item of items){const card=document.createElement("article");card.className="agent-card";const title=document.createElement("h3");title.textContent=item.title||"Incidente";const meta=document.createElement("p");meta.textContent=`${String(item.severity||"warning").toUpperCase()} · ${item.agent_id||"sem Agent"} · ${item.instance_id||"sem instância"}`;const age=document.createElement("p");age.textContent=`Aberto desde ${item.started_at?new Date(item.started_at).toLocaleString():"—"}`;const link=document.createElement("a");link.className="button";link.href=`/operations.html#incidents`;link.textContent="Ver incidente";card.append(title,meta,age,link);root.append(card)}}
async function load(){try{const [infra,operations]=await Promise.all([request("/api/admin/infrastructure/overview"),request("/api/operations?view=summary")]);render(infra);renderOperations(operations)}catch(error){const box=$("infra-error");box.hidden=false;box.textContent=error.message||String(error)}}
async function init(){if(!auth()){location.replace("/login.html");return}await sidebar();$("infra-refresh").onclick=load;await load();timer=setInterval(load,5000)}
window.addEventListener("beforeunload",()=>{if(timer)clearInterval(timer)});document.addEventListener("DOMContentLoaded",init);
})();
