(async function(){
'use strict';
const byId=id=>document.getElementById(id);const auth=sessionStorage.getItem('dsm_auth')||'';if(!auth){location.href='/login.html';return;}
const state={runtimes:[],agents:[],content:[],profiles:[],currentRuntime:null};
async function request(path,options={}){const headers={Authorization:'Basic '+auth,Accept:'application/json',...(options.headers||{})};if(options.body)headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});if(response.status===401){sessionStorage.removeItem('dsm_auth');location.href='/login.html';throw new Error('Sessão expirada.');}const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error||`HTTP ${response.status}`);return payload;}
function message(text,type='info'){const el=byId('catalog-message');if(!el)return;el.textContent=text;el.dataset.type=type;el.hidden=!text;}
function setOptions(select,items,value,label,placeholder){select.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=placeholder;select.appendChild(first);items.forEach(item=>{const o=document.createElement('option');o.value=value(item);o.textContent=label(item);select.appendChild(o);});select.disabled=!items.length;}
function runtimeGame(runtime){return String(runtime.game||runtime.environment_id||'').toLowerCase();}
function renderRuntime(){const id=byId('catalog-runtime').value;state.currentRuntime=state.runtimes.find(r=>String(r.id)===id)||null;const r=state.currentRuntime||{};byId('catalog-runtime-provider').textContent=`Provider ${r.artifact?.provider||'—'}`;byId('catalog-runtime-version').textContent=`Versão ${r.version?.value||r.version?.strategy||'—'}`;byId('catalog-runtime-platform').textContent=`Plataforma ${(r.requirements?.os||[]).join(', ')||'—'}`;byId('catalog-overview-process').textContent=r.process?.engine?`${r.process.engine} · ${r.process.executable||'—'}`:'—';byId('catalog-param-engine').value=r.process?.engine||'';byId('catalog-param-executable').value=r.process?.executable||'';byId('catalog-param-args').value=Array.isArray(r.process?.args)?r.process.args.join(' '):(r.process?.args||'');byId('catalog-version-declared').textContent=r.version?.value||r.version?.strategy||'—';byId('catalog-version-build').textContent=r.version?.build||'—';loadProfiles();loadAgentInventory();}
function renderProfiles(){const box=byId('catalog-resource-profiles');if(!state.profiles.length){box.innerHTML='<div class="catalog-empty">Nenhum perfil de recursos definido para este jogo.</div>';byId('catalog-overview-profile').textContent='Não definido';return;}box.replaceChildren(...state.profiles.map(p=>{const article=document.createElement('article');article.className='catalog-resource-profile';article.innerHTML=`<div><strong>${p.name||p.id}</strong><span>${p.description||''}</span></div><dl><div><dt>RAM</dt><dd>${Math.round(Number(p.memory_mb||0)/1024)} GB</dd></div><div><dt>Armazenamento</dt><dd>${(Number(p.storage_mb||0)/1024).toFixed(1)} GB</dd></div><div><dt>CPU</dt><dd>${p.cpu_cores||'—'}</dd></div><div><dt>Swap</dt><dd>${p.swap_mb?Math.round(p.swap_mb/1024)+' GB':'—'}</dd></div></dl>`;return article;}));byId('catalog-overview-profile').textContent=state.profiles[0].name||state.profiles[0].id;}
async function loadProfiles(){const game=byId('catalog-game').value;if(!game){state.profiles=[];renderProfiles();return;}try{const data=await request(`/api/catalog/resource-profiles?game=${encodeURIComponent(game)}`);state.profiles=data.profiles||[];}catch(e){state.profiles=[];}renderProfiles();}
async function loadContent(){const game=byId('catalog-game').value;const el=byId('catalog-content-list');if(!game){el.textContent='Selecione um jogo para consultar conteúdo do catálogo.';return;}try{const data=await request(`/api/catalog/content?game=${encodeURIComponent(game)}`);state.content=Array.isArray(data)?data:(data.content||data.entries||[]);el.textContent=state.content.length?state.content.map(x=>x.name||x.id||String(x)).join(' · '):'Nenhum conteúdo adicional publicado para este jogo.';}catch(e){el.textContent='Conteúdo adicional indisponível.';}}
async function loadCatalog(){message('');const [runtimeData,agentData]=await Promise.all([request('/api/catalog/runtimes'),request('/api/agents').catch(()=>({agents:[]}))]);state.runtimes=Array.isArray(runtimeData)?runtimeData:(runtimeData.runtimes||[]);state.agents=Array.isArray(agentData)?agentData:(agentData.agents||[]);const games=[...new Set(state.runtimes.map(runtimeGame).filter(Boolean))].sort();setOptions(byId('catalog-game'),games,x=>x,x=>x,'Selecione um jogo');setOptions(byId('catalog-agent'),state.agents,a=>String(a.agent_id||a.id||a.name||''),a=>String(a.display_name||a.name||a.agent_id||a.id||'Agent'),'Selecione um Agent');if(games.length){byId('catalog-game').value=games[0];await onGameChange();}}
async function onGameChange(){const game=byId('catalog-game').value;const runtimes=state.runtimes.filter(r=>runtimeGame(r)===game);setOptions(byId('catalog-runtime'),runtimes,r=>String(r.id),r=>String(r.name||r.id),'Selecione um runtime');if(runtimes.length){byId('catalog-runtime').value=runtimes[0].id;renderRuntime();}else{state.currentRuntime=null;renderRuntime();}await loadContent();await loadAgentInventory();}
async function gameData(action){const runtime=state.currentRuntime;const agent=byId('catalog-agent').value;if(!runtime||!agent){message('Selecione jogo, runtime e Agent antes de executar a operação.','warning');return;}const selector=byId('catalog-selector').value.trim()||'current';try{message(`Enfileirando ${action}...`);const result=await request('/api/agents/game-data',{method:'POST',body:JSON.stringify({agent_id:agent,environment_id:runtime.id,selector,action})});byId('catalog-game-data-status').textContent=`Operação ${action} enfileirada: ${result.job_id||result.id||'job criado'}`;message('Operação enviada ao Agent.','success');await Promise.all([loadAgentJobs(),loadAgentInventory()]);}catch(e){message(e.message,'error');}}
async function loadAgentJobs(){const agent=byId('catalog-agent').value;const el=byId('catalog-agent-jobs');if(!agent){el.textContent='Selecione um Agent na aba Game Data para consultar operações recentes.';return;}try{const data=await request(`/api/agents/game-data/jobs?agent_id=${encodeURIComponent(agent)}`);const jobs=data.jobs||[];el.textContent=jobs.length?jobs.slice(0,8).map(j=>`${j.action||'operação'} · ${j.environment_id||''} · ${j.status||j.state||'queued'}`).join('\n'):'Nenhuma operação recente para este Agent.';}catch(e){el.textContent='Não foi possível consultar jobs de game-data.';}}
async function loadAgentInventory(){const agent=byId('catalog-agent').value;const status=byId('catalog-game-data-status');if(!agent){status.textContent='Selecione jogo, runtime e Agent.';return;}try{const data=await request(`/api/agents/game-data/inventory?agent_id=${encodeURIComponent(agent)}`);const runtime=state.currentRuntime;const item=(data.items||[]).find(x=>String(x.environment_id||'')===String(runtime?.id||''));if(!runtime){status.textContent=`Agent com ${data.installed_count||0} ambiente(s) de game-data conhecido(s).`;return;}if(!item){status.textContent=`${runtime.name||runtime.id}: não instalado neste Agent · ${data.active_jobs||0} job(s) ativo(s).`;return;}const version=item.version?` · versão ${item.version}`:'';const latest=item.latest_status&&item.latest_status!=='completed'?` · último estado ${item.latest_status}`:'';status.textContent=`${runtime.name||runtime.id}: instalado${version}${latest}${item.target_path?` · ${item.target_path}`:''}`;}catch(e){status.textContent='Inventário de game-data indisponível para este Agent.';}}
function bindTabs(){document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===button.dataset.tab));}));}
try{byId('sidebar-component').innerHTML=await fetch('/components/sidebar-v3.html').then(r=>r.text());}catch(e){}
try{const me=await request('/api/auth/me');const user=me.user||me;const role=String(user.role||'').toLowerCase();byId('catalog-user-name').textContent=user.username||user.name||'Sessão ativa';byId('catalog-user-role').textContent=role||'—';const admin=role==='admin';document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!admin);document.querySelectorAll('.agent-manager-only').forEach(el=>el.hidden=!['admin','controller','operator'].includes(role));}catch(e){}
byId('catalog-menu-toggle')?.addEventListener('click',()=>document.body.classList.toggle('cap-sidebar-collapsed'));byId('btn-logout')?.addEventListener('click',()=>{sessionStorage.removeItem('dsm_auth');location.href='/login.html';});document.querySelectorAll('.cap-sidebar-v3 a').forEach(a=>a.classList.toggle('active',(a.getAttribute('href')||'').startsWith('catalog.html')));
bindTabs();byId('catalog-game').addEventListener('change',onGameChange);byId('catalog-runtime').addEventListener('change',renderRuntime);byId('catalog-agent').addEventListener('change',()=>{loadAgentJobs();loadAgentInventory();});byId('catalog-refresh').addEventListener('click',loadCatalog);byId('catalog-game-data-install').addEventListener('click',()=>gameData('install'));byId('catalog-game-data-update').addEventListener('click',()=>gameData('update'));byId('catalog-game-data-verify').addEventListener('click',()=>gameData('verify'));
try{await loadCatalog();}catch(e){message(`Falha ao carregar catálogo: ${e.message}`,'error');}
})();
