(async function(){
'use strict';
const byId=id=>document.getElementById(id);const auth=sessionStorage.getItem('dsm_auth')||'';if(!auth){location.href='/login.html';return;}
const state={runtimes:[],agents:[],content:[],profiles:[],currentRuntime:null,policy:null,filePath:'',selectedFile:'',fileReadToken:0,fileReadBusy:false,fileListBusy:false,admin:false,activeJobId:'',jobPollToken:0};
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function request(path,options={}){const headers={Authorization:'Basic '+auth,Accept:'application/json',...(options.headers||{})};if(options.body)headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});if(response.status===401){sessionStorage.removeItem('dsm_auth');location.href='/login.html';throw new Error('Sessão expirada.');}const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error||`HTTP ${response.status}`);return payload;}
function message(text,type='info'){const el=byId('catalog-message');if(!el)return;el.textContent=text;el.dataset.type=type;el.hidden=!text;}
function setOptions(select,items,value,label,placeholder){select.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=placeholder;select.appendChild(first);items.forEach(item=>{const o=document.createElement('option');o.value=value(item);o.textContent=label(item);select.appendChild(o);});select.disabled=!items.length;}
function runtimeGame(runtime){return String(runtime.game||runtime.environment_id||'').toLowerCase();}
function selectedAgent(){const id=byId('catalog-agent').value;return state.agents.find(agent=>String(agent.agent_id||agent.id||'')===id)||null;}
function steamReady(){const agent=selectedAgent(),caps=agent?.capabilities||{},detail=caps.steamcmd_status||{};return Boolean(detail.functional||caps.steamcmd===true);}
function updatePrerequisites(){const provider=String(state.currentRuntime?.artifact?.provider||state.currentRuntime?.provider||'').toLowerCase(),needsSteam=provider==='steam',ready=!needsSteam||steamReady();['catalog-game-data-install','catalog-game-data-update','catalog-game-data-repair'].forEach(id=>{const button=byId(id);if(button&&!state.activeJobId)button.disabled=!ready;});if(needsSteam&&selectedAgent()&&!ready)byId('catalog-game-data-status').textContent='SteamCMD não está funcionando neste Agent. Instale-o no card do Agent antes de continuar.';return ready;}
function renderRuntime(){const id=byId('catalog-runtime').value;state.currentRuntime=state.runtimes.find(r=>String(r.id)===id)||null;const r=state.currentRuntime||{};byId('catalog-runtime-provider').textContent=`Provider ${r.artifact?.provider||'—'}`;byId('catalog-runtime-version').textContent=`Versão ${r.version?.value||r.version?.strategy||'—'}`;byId('catalog-runtime-platform').textContent=`Plataforma ${(r.requirements?.os||[]).join(', ')||'—'}`;byId('catalog-overview-process').textContent=r.process?.engine?`${r.process.engine} · ${r.process.executable||'—'}`:'—';byId('catalog-param-engine').value=r.process?.engine||'';byId('catalog-version-declared').textContent=r.version?.value||r.version?.strategy||'—';byId('catalog-version-build').textContent=r.version?.build||'—';state.filePath='';clearEditor();loadProfiles();loadAgentInventory();loadRuntimePolicy();updatePrerequisites();}
function renderProfiles(){const box=byId('catalog-resource-profiles');if(!state.profiles.length){box.innerHTML='<div class="catalog-empty">Nenhum perfil de recursos definido para este jogo.</div>';byId('catalog-overview-profile').textContent='Não definido';return;}box.replaceChildren(...state.profiles.map(p=>{const article=document.createElement('article');article.className='catalog-resource-profile';article.innerHTML=`<div><strong>${p.name||p.id}</strong><span>${p.description||''}</span></div><dl><div><dt>RAM</dt><dd>${Math.round(Number(p.memory_mb||0)/1024)} GB</dd></div><div><dt>Armazenamento</dt><dd>${(Number(p.storage_mb||0)/1024).toFixed(1)} GB</dd></div><div><dt>CPU</dt><dd>${p.cpu_cores||'—'}</dd></div><div><dt>Swap</dt><dd>${p.swap_mb?Math.round(p.swap_mb/1024)+' GB':'—'}</dd></div></dl>`;return article;}));byId('catalog-overview-profile').textContent=state.profiles[0].name||state.profiles[0].id;}
async function loadProfiles(){const game=byId('catalog-game').value;if(!game){state.profiles=[];renderProfiles();return;}try{const data=await request(`/api/catalog/resource-profiles?game=${encodeURIComponent(game)}`);state.profiles=data.profiles||[];}catch(e){state.profiles=[];}renderProfiles();}
async function loadRuntimePolicy(){const runtime=state.currentRuntime;if(!runtime){state.policy=null;return;}try{const data=await request(`/api/catalog/runtime-policy?runtime_id=${encodeURIComponent(runtime.id)}`);state.policy=data.policy||{};const p=state.policy;byId('catalog-param-executable').value=p.executable||runtime.process?.executable||'';byId('catalog-param-args').value=(p.arguments||[]).join('\n');byId('catalog-param-working-dir').value=p.working_directory||'.';const shutdown=p.shutdown||{};byId('catalog-param-shutdown').value=`${shutdown.mode||'signal'}:${shutdown.value||'TERM'}`;byId('catalog-param-start-timeout').value=p.start_timeout_seconds||120;byId('catalog-param-stop-timeout').value=p.stop_timeout_seconds||30;byId('catalog-param-environment').value=JSON.stringify(p.environment||{},null,2);byId('catalog-param-variables').value=JSON.stringify(p.variables||[],null,2);byId('catalog-config-templates').value=JSON.stringify(p.templates||[],null,2);document.querySelectorAll('[data-panel="parameters"] input,[data-panel="parameters"] textarea,[data-panel="configuration"] textarea').forEach(el=>{if(el.id!=='catalog-param-engine')el.disabled=!state.admin;});}catch(e){message(`Parâmetros: ${e.message}`,'error');}}
function policyFromForm(){const shutdownText=byId('catalog-param-shutdown').value.trim()||'signal:TERM';const idx=shutdownText.indexOf(':');const mode=idx>=0?shutdownText.slice(0,idx):'signal';const value=idx>=0?shutdownText.slice(idx+1):shutdownText;return{...(state.policy||{}),runtime_id:state.currentRuntime.id,executable:byId('catalog-param-executable').value.trim(),arguments:byId('catalog-param-args').value.split('\n').map(x=>x.trim()).filter(Boolean),working_directory:byId('catalog-param-working-dir').value.trim()||'.',shutdown:{mode,value},start_timeout_seconds:Number(byId('catalog-param-start-timeout').value||120),stop_timeout_seconds:Number(byId('catalog-param-stop-timeout').value||30),environment:JSON.parse(byId('catalog-param-environment').value||'{}'),variables:JSON.parse(byId('catalog-param-variables').value||'[]'),templates:JSON.parse(byId('catalog-config-templates').value||'[]')};}
async function saveRuntimePolicy(){if(!state.admin||!state.currentRuntime)return;try{const policy=policyFromForm();const data=await request('/api/catalog/runtime-policy',{method:'PUT',body:JSON.stringify({runtime_id:state.currentRuntime.id,policy})});state.policy=data.policy;message('Parâmetros e templates do runtime salvos.','success');await loadRuntimePolicy();}catch(e){message(`Não foi possível salvar: ${e.message}`,'error');}}
async function loadContent(){const game=byId('catalog-game').value;const el=byId('catalog-content-list');if(!game){el.textContent='Selecione um jogo para consultar conteúdo do catálogo.';return;}try{const data=await request(`/api/catalog/content?game=${encodeURIComponent(game)}`);state.content=Array.isArray(data)?data:(data.content||data.entries||[]);el.textContent=state.content.length?state.content.map(x=>x.name||x.id||String(x)).join(' · '):'Nenhum conteúdo adicional publicado para este jogo.';}catch(e){el.textContent='Conteúdo adicional indisponível.';}}
async function loadCatalog(){message('');const [runtimeData,agentData]=await Promise.all([request('/api/catalog/runtimes'),request('/api/agents').catch(()=>({agents:[]}))]);state.runtimes=Array.isArray(runtimeData)?runtimeData:(runtimeData.runtimes||[]);state.agents=Array.isArray(agentData)?agentData:(agentData.agents||[]);const games=[...new Set(state.runtimes.map(runtimeGame).filter(Boolean))].sort();setOptions(byId('catalog-game'),games,x=>x,x=>x,'Selecione um jogo');setOptions(byId('catalog-agent'),state.agents,a=>String(a.agent_id||a.id||a.name||''),a=>String(a.display_name||a.name||a.agent_id||a.id||'Agent'),'Selecione um Agent');if(games.length){byId('catalog-game').value=games[0];await onGameChange();}}
async function onGameChange(){const game=byId('catalog-game').value;const runtimes=state.runtimes.filter(r=>runtimeGame(r)===game);setOptions(byId('catalog-runtime'),runtimes,r=>String(r.id),r=>String(r.name||r.id),'Selecione um runtime');if(runtimes.length){byId('catalog-runtime').value=runtimes[0].id;renderRuntime();}else{state.currentRuntime=null;renderRuntime();}await loadContent();await loadAgentInventory();}
const operationLabels={install:'Instalação',update:'Atualização',verify:'Verificação',repair:'Reparo'};const stateLabels={queued:'Na fila',delivered:'Enviado ao Agent',running:'Instalando',completed:'Concluído',failed:'Falhou'};
const steamAuthCommand=`bash <<'STEAM_AUTH'
set -euo pipefail

read -rp "Nome da conta Steam dedicada (não o e-mail): " STEAM_ACCOUNT < /dev/tty

case "$STEAM_ACCOUNT" in
  (*[!A-Za-z0-9_.-]*|'')
    echo "ERRO: nome de conta Steam inválido."
    exit 1
    ;;
esac

sudo mkdir -p /etc/systemd/system/capivara-agent.service.d

printf '[Service]\\nEnvironment="DSM_STEAM_USER=%s"\\n' "$STEAM_ACCOUNT" |
  sudo tee /etc/systemd/system/capivara-agent.service.d/30-steam-account.conf >/dev/null

echo "O SteamCMD solicitará senha e possivelmente o código Steam Guard."

sudo -u capivara-agent \\
  env HOME=/var/lib/capivara-agent \\
  /var/lib/capivara-agent/tools/steamcmd/steamcmd.sh \\
  +login "$STEAM_ACCOUNT" \\
  +quit < /dev/tty

sudo systemctl daemon-reload
sudo systemctl restart capivara-agent.service

echo "AUTENTICAÇÃO STEAM CONFIGURADA"
STEAM_AUTH`;
function steamAuthenticationRequired(error){return /steam authentication is required|configure\s+DSM_STEAM_USER|steam guard|two-factor/i.test(String(error||''));}
function renderSteamAuthenticationHelp(error){const help=byId('catalog-steam-auth-help');const required=steamAuthenticationRequired(error);help.hidden=!required;byId('catalog-steam-auth-command').textContent=required?steamAuthCommand:'';return required;}
function legacyCopy(text){const input=document.createElement('textarea');input.value=text;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();input.setSelectionRange(0,input.value.length);const copied=document.execCommand('copy');input.remove();return copied;}
async function copySteamAuthenticationCommand(){const button=byId('catalog-copy-steam-auth');let copied=false;try{if(window.isSecureContext&&navigator.clipboard?.writeText){await navigator.clipboard.writeText(steamAuthCommand);copied=true;}else copied=legacyCopy(steamAuthCommand);}catch(e){copied=legacyCopy(steamAuthCommand);}if(copied){button.textContent='Copiado';message('Comando copiado. Execute-o no terminal do Agent.','success');setTimeout(()=>{button.textContent='Copiar comando';},1800);return;}const command=byId('catalog-steam-auth-command');const selection=window.getSelection();const range=document.createRange();range.selectNodeContents(command);selection.removeAllRanges();selection.addRange(range);message('O navegador bloqueou a cópia automática. O comando foi selecionado; pressione Ctrl+C.','warning');}
function operationButtonsDisabled(disabled){['catalog-game-data-install','catalog-game-data-update','catalog-game-data-verify','catalog-game-data-repair'].forEach(id=>{const button=byId(id);if(button)button.disabled=disabled;});}
function renderJob(job,{historical=false}={}){const status=String(job.status||'queued').toLowerCase();const active=['queued','delivered','running'].includes(status);const progress=Math.max(0,Math.min(100,Number(job.progress||(status==='completed'?100:status==='delivered'?10:status==='running'?25:3))));const action=operationLabels[job.action]||'Operação';const panel=byId('catalog-operation-progress');const badge=byId('catalog-operation-badge');panel.hidden=false;panel.dataset.state=status;badge.dataset.state=active?'active':status;badge.textContent=historical?`Último estado: ${stateLabels[status]||status}`:stateLabels[status]||status;byId('catalog-progress-title').textContent=`${historical?'Histórico da ':''}${action} · ${stateLabels[status]||status}`;byId('catalog-progress-value').textContent=`${Math.round(progress)}%`;byId('catalog-progress-bar').style.width=`${progress}%`;panel.querySelector('[role=progressbar]').setAttribute('aria-valuenow',String(progress));const descriptions={queued:'Solicitação registrada. Aguardando o próximo contato do Agent.',delivered:'O Agent recebeu a solicitação e iniciará o processamento.',running:'O Agent está preparando os arquivos do jogo.',completed:historical?'Esta instalação foi concluída anteriormente. Nenhuma nova instalação foi iniciada.':'O jogo está pronto para ser utilizado neste Agent.',failed:'A operação não pôde ser concluída.'};const error=String(job.last_error||job.result?.error||'').trim();const needsSteamAuth=renderSteamAuthenticationHelp(error);byId('catalog-progress-detail').textContent=needsSteamAuth?'A conta Steam deste Agent precisa ser autenticada antes da instalação.':descriptions[status]||'Acompanhando a operação.';byId('catalog-error-details').hidden=!error;byId('catalog-error-text').textContent=error;operationButtonsDisabled(active);return active;}
async function followJob(jobId){const token=++state.jobPollToken;state.activeJobId=jobId;while(token===state.jobPollToken){try{const job=await request(`/api/agents/game-data/jobs?job_id=${encodeURIComponent(jobId)}`);const active=renderJob(job);await Promise.all([loadAgentJobs(),loadAgentInventory()]);if(!active){state.activeJobId='';if(job.status==='completed'){message(`${operationLabels[job.action]||'Operação'} concluída com sucesso.`,'success');const integrity=job.result?.integrity;if(integrity)byId('catalog-version-integrity').textContent=`${integrity.health||'—'} · ${integrity.files||0} arquivos · ${Math.round(Number(integrity.bytes||0)/1048576)} MB`;}else message(job.last_error||job.result?.error||'A operação falhou.','error');return;}await sleep(2000);}catch(e){operationButtonsDisabled(false);message(`Não foi possível acompanhar a operação: ${e.message}`,'error');return;}}}
async function gameData(action){const runtime=state.currentRuntime;const agent=byId('catalog-agent').value;if(!runtime||!agent){message('Selecione jogo, runtime e Agent antes de executar a operação.','warning');return;}if(['install','update','repair'].includes(action)&&!updatePrerequisites()){message('O SteamCMD precisa estar funcionando antes desta operação.','warning');return;}const selector=byId('catalog-selector').value.trim()||'current';try{operationButtonsDisabled(true);message(`${operationLabels[action]||'Operação'} sendo preparada...`);const result=await request('/api/agents/game-data',{method:'POST',body:JSON.stringify({agent_id:agent,environment_id:runtime.id,selector,action})});renderJob(result);byId('catalog-game-data-status').textContent=`${runtime.name||runtime.id}: operação iniciada no Agent selecionado.`;message('Solicitação enviada. O progresso será atualizado automaticamente.','success');followJob(result.job_id);}catch(e){operationButtonsDisabled(false);updatePrerequisites();message(e.message,'error');}}
async function loadAgentJobs(){const agent=byId('catalog-agent').value;const el=byId('catalog-agent-jobs');if(!agent){el.textContent='Selecione um Agent na aba Game Data para consultar operações recentes.';return;}try{const data=await request(`/api/agents/game-data/jobs?agent_id=${encodeURIComponent(agent)}`);const jobs=data.jobs||[];el.textContent=jobs.length?jobs.slice(0,10).map(j=>`${j.action||'operação'} · ${j.environment_id||''} · ${j.status||j.state||'queued'}`).join('\n'):'Nenhuma operação recente para este Agent.';}catch(e){el.textContent='Não foi possível consultar jobs de game-data.';}}
async function resumeAgentJob(){const agent=byId('catalog-agent').value;const runtime=state.currentRuntime;++state.jobPollToken;state.activeJobId='';operationButtonsDisabled(false);updatePrerequisites();if(!agent||!runtime)return;try{const data=await request(`/api/agents/game-data/jobs?agent_id=${encodeURIComponent(agent)}`);const operations=(data.jobs||[]).filter(job=>String(job.environment_id||'')===String(runtime.id)&&Object.hasOwn(operationLabels,String(job.action||'')));const active=operations.find(job=>['queued','delivered','running'].includes(String(job.status||'').toLowerCase()));const latest=active||operations[0];if(!latest)return;renderJob(latest,{historical:!active});if(active)followJob(active.job_id);}catch(e){message(`Não foi possível recuperar o acompanhamento: ${e.message}`,'error');}}
async function loadAgentInventory(){const agent=byId('catalog-agent').value;const status=byId('catalog-game-data-status');if(!agent){status.textContent='Selecione jogo, runtime e Agent.';return;}try{const data=await request(`/api/agents/game-data/inventory?agent_id=${encodeURIComponent(agent)}`);const runtime=state.currentRuntime;const item=(data.items||[]).find(x=>String(x.environment_id||'')===String(runtime?.id||''));if(!runtime){status.textContent=`Agent com ${data.installed_count||0} ambiente(s) de game-data conhecido(s).`;return;}if(!item){status.textContent=`${runtime.name||runtime.id}: não instalado neste Agent · ${data.active_jobs||0} job(s) ativo(s).`;return;}const version=item.version?` · versão ${item.version}`:'';const latest=item.latest_status&&item.latest_status!=='completed'?` · último estado ${item.latest_status}`:'';status.textContent=`${runtime.name||runtime.id}: instalado${version}${latest}${item.target_path?` · ${item.target_path}`:''}`;}catch(e){status.textContent='Inventário de game-data indisponível para este Agent.';}}
function fileContext(){const runtime=state.currentRuntime;const agent=byId('catalog-agent').value;if(!runtime||!agent)throw new Error('Selecione runtime e Agent.');return{agent_id:agent,environment_id:runtime.id,selector:byId('catalog-selector').value.trim()||'current'};}
async function waitJob(jobId,timeoutMs=180000){const started=Date.now();while(Date.now()-started<timeoutMs){const job=await request(`/api/agents/game-data/jobs?job_id=${encodeURIComponent(jobId)}`);if(job.status==='completed')return job.result||job;if(job.status==='failed')throw new Error(job.last_error||job.result?.error||'Operação remota falhou.');await sleep(1500);}throw new Error('O Agent não respondeu após 3 minutos. Verifique sua conexão e os jobs pendentes.');}
async function fileOperation(operation,extra={}){const labels={list:'Consultando arquivos',read:'Abrindo arquivo',write:'Salvando arquivo',create:'Criando arquivo',mkdir:'Criando pasta',rename:'Renomeando',delete:'Excluindo',upload:'Enviando arquivo'};const label=labels[operation]||'Processando arquivos';const body={...fileContext(),operation,...extra};const job=await request('/api/agents/game-data/files',{method:'POST',body:JSON.stringify(body)});message(`${label} no Agent...`,'info');const result=await waitJob(job.job_id);message(`${label} concluído.`,'success');loadAgentJobs();return result.file_result||result;}
function clearEditor(){++state.fileReadToken;state.selectedFile='';byId('catalog-file-editor-name').textContent='Editor';byId('catalog-file-content').value='';byId('catalog-file-content').disabled=true;byId('catalog-file-save').disabled=true;byId('catalog-file-rename').disabled=true;byId('catalog-file-delete').disabled=true;}
function joinPath(base,name){return[base,name].filter(Boolean).join('/');}
async function loadFiles(path=state.filePath){if(state.fileListBusy)return;state.fileListBusy=true;const list=byId('catalog-file-list');const refresh=byId('catalog-file-refresh');refresh.disabled=true;list.setAttribute('aria-busy','true');list.innerHTML='<div class="catalog-empty">Carregando arquivos do Agent... Esta consulta pode levar até um ciclo de heartbeat.</div>';try{const result=await fileOperation('list',{path});state.filePath=result.path||'';byId('catalog-file-current-path').textContent='/'+state.filePath;list.replaceChildren();const entries=result.entries||[];if(!entries.length){list.innerHTML='<div class="catalog-empty">Diretório vazio.</div>';return;}entries.forEach(entry=>{const button=document.createElement('button');button.type='button';button.className='catalog-file-entry';button.dataset.type=entry.type;button.innerHTML=`<span>${entry.type==='directory'?'▸':'·'} ${entry.name}</span><small>${entry.type==='file'?`${entry.size||0} B`:'pasta'}</small>`;button.addEventListener('click',()=>entry.type==='directory'?loadFiles(entry.path):openFile(entry.path));list.appendChild(button);});}catch(e){list.innerHTML=`<div class="catalog-empty">${e.message}</div>`;message(e.message,'error');}finally{state.fileListBusy=false;refresh.disabled=false;list.removeAttribute('aria-busy');}}
async function openFile(path){if(state.fileReadBusy){message('Aguarde a leitura atual terminar antes de abrir outro arquivo.','warning');return;}state.fileReadBusy=true;const token=++state.fileReadToken;state.selectedFile='';byId('catalog-file-list').setAttribute('aria-busy','true');byId('catalog-file-editor-name').textContent=`Abrindo ${path}...`;byId('catalog-file-content').value='Aguardando o Agent enviar o conteúdo do arquivo...';byId('catalog-file-content').disabled=true;byId('catalog-file-save').disabled=true;byId('catalog-file-rename').disabled=true;byId('catalog-file-delete').disabled=true;try{const result=await fileOperation('read',{path});if(token!==state.fileReadToken)return;state.selectedFile=result.path||path;byId('catalog-file-editor-name').textContent=state.selectedFile;byId('catalog-file-content').value=result.content||'';byId('catalog-file-content').disabled=!state.admin;byId('catalog-file-save').disabled=!state.admin;byId('catalog-file-rename').disabled=!state.admin;byId('catalog-file-delete').disabled=!state.admin;}catch(e){if(token!==state.fileReadToken)return;byId('catalog-file-editor-name').textContent=`Falha ao abrir ${path}`;byId('catalog-file-content').value='';message(e.message,'error');}finally{state.fileReadBusy=false;byId('catalog-file-list').removeAttribute('aria-busy');}}
async function saveFile(){if(!state.selectedFile)return;try{await fileOperation('write',{path:state.selectedFile,content:byId('catalog-file-content').value});await loadFiles();}catch(e){message(e.message,'error');}}
async function newFile(){const name=prompt('Nome do novo arquivo:');if(!name)return;try{const path=joinPath(state.filePath,name);await fileOperation('create',{path,content:''});await loadFiles();await openFile(path);}catch(e){message(e.message,'error');}}
async function newFolder(){const name=prompt('Nome da nova pasta:');if(!name)return;try{await fileOperation('mkdir',{path:joinPath(state.filePath,name)});await loadFiles();}catch(e){message(e.message,'error');}}
async function renameSelected(){if(!state.selectedFile)return;const current=state.selectedFile.split('/').pop();const name=prompt('Novo nome:',current);if(!name||name===current)return;const parent=state.selectedFile.includes('/')?state.selectedFile.slice(0,state.selectedFile.lastIndexOf('/')):'';try{const destination=joinPath(parent,name);await fileOperation('rename',{path:state.selectedFile,destination});clearEditor();await loadFiles();}catch(e){message(e.message,'error');}}
async function deleteSelected(){if(!state.selectedFile||!confirm(`Excluir ${state.selectedFile}?`))return;try{await fileOperation('delete',{path:state.selectedFile,recursive:false});clearEditor();await loadFiles();}catch(e){message(e.message,'error');}}
async function uploadFile(file){if(!file)return;if(file.size>32*1024*1024){message('Arquivo excede 32 MB.','error');return;}const reader=new FileReader();reader.onload=async()=>{try{const encoded=String(reader.result||'').split(',',2)[1]||'';await fileOperation('upload',{path:joinPath(state.filePath,file.name),content_base64:encoded});await loadFiles();}catch(e){message(e.message,'error');}};reader.readAsDataURL(file);}
function goUp(){if(!state.filePath)return;const parts=state.filePath.split('/').filter(Boolean);parts.pop();loadFiles(parts.join('/'));}
function bindTabs(){document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.panel===button.dataset.tab));if(button.dataset.tab==='game-data'&&byId('catalog-agent').value)loadFiles();}));}
try{byId('sidebar-component').innerHTML=await fetch('/components/sidebar-v3.html').then(r=>r.text());}catch(e){}
try{const user=await request('/api/whoami');const role=String(user.role||'').toLowerCase();state.admin=role==='admin';byId('catalog-user-name').textContent=user.username||user.name||'Sessão ativa';byId('catalog-user-role').textContent=role||'—';document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!state.admin);document.querySelectorAll('.agent-manager-only').forEach(el=>el.hidden=!['admin','controller','operator'].includes(role));}catch(e){state.admin=false;document.querySelectorAll('.admin-only,.agent-manager-only').forEach(el=>el.hidden=true);message(`Não foi possível confirmar as permissões da sessão: ${e.message}`,'error');}
byId('catalog-menu-toggle')?.addEventListener('click',()=>document.body.classList.toggle('cap-sidebar-collapsed'));byId('btn-logout')?.addEventListener('click',()=>{sessionStorage.removeItem('dsm_auth');location.href='/login.html';});document.querySelectorAll('.cap-sidebar-v3 a').forEach(a=>a.classList.toggle('active',(a.getAttribute('href')||'').startsWith('catalog.html')));
bindTabs();byId('catalog-game').addEventListener('change',onGameChange);byId('catalog-runtime').addEventListener('change',()=>{state.filePath='';clearEditor();renderRuntime();resumeAgentJob();if(byId('catalog-agent').value)loadFiles();});byId('catalog-agent').addEventListener('change',()=>{state.filePath='';clearEditor();loadAgentJobs();loadAgentInventory();resumeAgentJob();if(byId('catalog-agent').value)loadFiles();else byId('catalog-file-list').innerHTML='<div class="catalog-empty">Selecione um Agent com game-data instalado.</div>';});byId('catalog-refresh').addEventListener('click',loadCatalog);byId('catalog-game-data-install').addEventListener('click',()=>gameData('install'));byId('catalog-game-data-update').addEventListener('click',()=>gameData('update'));byId('catalog-game-data-verify').addEventListener('click',()=>gameData('verify'));byId('catalog-game-data-repair').addEventListener('click',()=>gameData('repair'));byId('catalog-copy-steam-auth').addEventListener('click',copySteamAuthenticationCommand);byId('catalog-param-save').addEventListener('click',saveRuntimePolicy);byId('catalog-config-save').addEventListener('click',saveRuntimePolicy);byId('catalog-file-refresh').addEventListener('click',()=>loadFiles());byId('catalog-file-up').addEventListener('click',goUp);byId('catalog-file-new').addEventListener('click',newFile);byId('catalog-file-mkdir').addEventListener('click',newFolder);byId('catalog-file-save').addEventListener('click',saveFile);byId('catalog-file-rename').addEventListener('click',renameSelected);byId('catalog-file-delete').addEventListener('click',deleteSelected);byId('catalog-file-upload').addEventListener('click',()=>byId('catalog-file-upload-input').click());byId('catalog-file-upload-input').addEventListener('change',event=>uploadFile(event.target.files?.[0]));
try{await loadCatalog();}catch(e){message(`Falha ao carregar catálogo: ${e.message}`,'error');}
})();
