(()=>{"use strict";
const q=new URLSearchParams(location.search),iid=q.get("instance")||q.get("instance_id")||"",API="/api/customer/instance/dayz";if(!iid)return;
const H={"Accept":"application/json","X-Capivara-Auth-Area":"customer"};
function toast(t){const n=document.getElementById("toast");if(!n)return;n.textContent=t;n.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove("show"),3500)}
async function req(body){const r=await fetch(body?API:API+"?instance_id="+encodeURIComponent(iid),{method:body?"POST":"GET",headers:body?Object.assign({},H,{"Content-Type":"application/json"}):H,body:body?JSON.stringify(Object.assign({instance_id:iid},body)):undefined,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||d.error||("HTTP "+r.status));e.status=r.status;throw e}return d}
function el(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function ensure(){if(document.getElementById("dayz-tab"))return;const nav=document.querySelector(".sidebar nav"),b=el("button","DayZ");b.id="dayz-tab";b.dataset.view="dayz";const backups=nav&&nav.querySelector('[data-view="backups"]');if(nav)nav.insertBefore(b,backups||null);const s=el("section","","view");s.id="view-dayz";const vb=document.getElementById("view-backups");const parent=(vb&&vb.parentNode)||document.querySelector("main");if(parent)parent.insertBefore(s,vb||null);b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view==="dayz"));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-dayz"));load()}}
function fmt(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("pt-BR")}
function mapState(m){if(m.active)return"ativo";if(m.installed)return"instalado";if(m.available)return"disponível";return"não disponível"}
function render(data){ensure();const v=document.getElementById("view-dayz");if(!v)return;v.replaceChildren();const maps=data.maps||{},editable=!!data.editable;
const grid=el("div","","grid cols-2"),map=el("article","","card"),wipe=el("article","","card");
map.append(el("h2","Mapa / missão"),el("p","Mapas oficiais vêm do runtime. Mapas comunitários usam o fluxo de Conteúdo/Steam Workshop e aparecem aqui quando a missão estiver disponível. A persistência de cada mapa é preservada.","muted"));
const sel=document.createElement("select");sel.id="dayz-mission";(maps.missions||[]).forEach(m=>{const kind=m.official?"oficial":"comunitário",label=(m.active?"✓ ":"")+(m.name||m.id)+" · "+kind+" · "+mapState(m),o=new Option(label,m.id);o.disabled=!m.can_activate;if(m.current)o.selected=true;sel.add(o)});
const row=el("div","","actions mt-12"),refresh=el("button","Atualizar mapas","btn"),content=el("button","Abrir Conteúdo","btn"),change=el("button","Aplicar mapa e reiniciar","btn primary");refresh.disabled=!editable;const selected=()=>((maps.missions||[]).find(m=>m.id===sel.value)||{});const sync=()=>{const m=selected();change.disabled=!editable||!m.can_activate||!!m.active};sel.onchange=sync;sync();row.append(refresh,content,change);map.append(sel,row,el("p","Mapa atual: "+(maps.current_name||maps.current||"aguardando descoberta…")+" · disponíveis: "+((maps.counts||{}).available??0)+" · instalados na instância: "+((maps.counts||{}).installed??0),"muted"));
refresh.onclick=async()=>{await req({action:"refresh_maps"});toast("Descoberta de mapas solicitada.");setTimeout(load,1500)};
content.onclick=()=>{const b=document.querySelector('[data-view="content"]');if(b)b.click();else toast("Abra a aba Conteúdo para instalar dependências de mapas comunitários.")};
change.onclick=async()=>{const m=selected();if(!m.can_activate)return;if(!confirm("Alterar o mapa para "+(m.name||m.id)+"? O mapa atual será preservado e o servidor será reiniciado."))return;await req({action:"change_mission",mission:m.id});toast("Troca de mapa solicitada.");setTimeout(load,1500)};
wipe.append(el("h2","Wipe"),el("p","O wipe é independente da troca de mapa. Por padrão o DSM cria um backup antes de remover a persistência.","muted"));
const scope=document.createElement("select");scope.id="dayz-wipe-scope";scope.append(new Option("Persistência do mapa atual","persistence"),new Option("Persistência + perfis","persistence-and-profiles"));
const when=document.createElement("input");when.type="datetime-local";when.id="dayz-wipe-when";const backup=document.createElement("input");backup.type="checkbox";backup.checked=true;const bl=el("label");bl.append(backup,document.createTextNode(" Criar backup antes do wipe"));
const wr=el("div","","form-grid"),l1=el("label","Escopo"),l2=el("label","Data e hora (vazio = agora)");l1.append(scope);l2.append(when);wr.append(l1,l2,bl);
const schedule=el("button","Executar / agendar wipe","btn danger");schedule.disabled=!editable;schedule.onclick=async()=>{const future=when.value?new Date(when.value):null,msg=future?("Agendar wipe para "+future.toLocaleString("pt-BR")+"?"):"Executar wipe agora?";if(!confirm(msg))return;await req({action:"wipe",scope:scope.value,backup:backup.checked,scheduled_at:future?future.toISOString():null});toast(future?"Wipe agendado.":"Wipe solicitado.");setTimeout(load,1500)};wipe.append(wr,schedule);grid.append(map,wipe);v.append(grid);
const restart=el("article","","card mt-14");restart.append(el("h2","Restart automático"),el("p","Use a aba Manutenção para habilitar horário fixo ou intervalo. No DayZ o aviso e o shutdown usam o countdown nativo do messages.xml.","muted"));const go=el("button","Abrir Manutenção","btn primary");go.onclick=()=>{const b=document.getElementById("maintenance-tab");if(b)b.click()};restart.append(go);v.append(restart);
const hist=el("article","","card mt-14");hist.append(el("h2","Operações DayZ"));(data.operations||[]).forEach(op=>{const r=el("div","","row"),left=el("span",fmt(op.scheduled_at)+" · "+op.action),right=el("strong",op.status||"—");r.append(left,right);if(op.status==="queued"&&op.action==="wipe"){const cancel=el("button","Cancelar","btn");cancel.onclick=async()=>{await req({action:"cancel",operation_id:op.operation_id});toast("Wipe cancelado.");load()};r.append(cancel)}hist.append(r);if(op.last_error)hist.append(el("small",op.last_error,"muted"))});if(!(data.operations||[]).length)hist.append(el("p","Nenhuma operação registrada.","muted"));v.append(hist)}
async function load(){try{render(await req())}catch(e){if(e.status===400||e.status===404){const a=document.getElementById("dayz-tab"),b=document.getElementById("view-dayz");if(a)a.remove();if(b)b.remove();return}toast(e.message)}}
load();setInterval(()=>{const v=document.getElementById("view-dayz");if(v&&v.classList.contains("active"))load()},10000);
})();