(()=>{"use strict";
const q=new URLSearchParams(location.search),iid=q.get("instance")||q.get("instance_id")||"",API="/api/customer/instance/dayz";if(!iid)return;
const H={"Accept":"application/json","X-Capivara-Auth-Area":"customer"};let mapSelection=null,mapContentMode="disable",mapPersistenceMode="fresh";
function toast(t){const n=document.getElementById("toast");if(!n)return;n.textContent=t;n.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove("show"),3500)}
async function req(body){const r=await fetch(body?API:API+"?instance_id="+encodeURIComponent(iid),{method:body?"POST":"GET",headers:body?Object.assign({},H,{"Content-Type":"application/json"}):H,body:body?JSON.stringify(Object.assign({instance_id:iid},body)):undefined,credentials:"same-origin",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||d.error||("HTTP "+r.status));e.status=r.status;throw e}return d}
function el(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function ensure(){if(document.getElementById("dayz-tab"))return;const nav=document.querySelector(".sidebar nav"),b=el("button","Mundo & Mapa");b.id="dayz-tab";b.dataset.view="dayz";const backups=nav&&nav.querySelector('[data-view="backups"]');if(nav)nav.insertBefore(b,backups||null);const s=el("section","","view");s.id="view-dayz";const vb=document.getElementById("view-backups");const parent=(vb&&vb.parentNode)||document.querySelector("main");if(parent)parent.insertBefore(s,vb||null);b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view==="dayz"));document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x.id==="view-dayz"));load()}}
function fmt(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString("pt-BR")}
function mapState(m){if(m.active)return"ativo";if(m.installed)return"instalado";if(m.available)return"disponível";return"não disponível"}
function render(data){ensure();const v=document.getElementById("view-dayz");if(!v)return;v.replaceChildren();const maps=data.maps||{},editable=!!data.editable,operations=data.operations||[],blockingOperation=operations.find(op=>["queued","delivered"].includes(op.status)&&["wipe","change_mission"].includes(op.action));
const grid=el("div","","grid cols-2"),map=el("article","","card"),wipe=el("article","","card");
map.append(el("h2","Mapa / missão"),el("p","Mapas oficiais vêm do runtime. Mapas comunitários usam o fluxo de Conteúdo/Steam Workshop e aparecem aqui quando a missão estiver disponível. A persistência de cada mapa é preservada.","muted"));
const sel=document.createElement("select");sel.id="dayz-mission";const missions=maps.missions||[],remembered=missions.find(m=>m.id===mapSelection&&m.can_activate);missions.forEach(m=>{const kind=m.official?"oficial":"comunitário",label=(m.active?"✓ ":"")+(m.name||m.id)+" · "+kind+" · "+mapState(m),o=new Option(label,m.id);o.disabled=!m.can_activate;if((remembered&&m.id===remembered.id)||(!remembered&&m.current))o.selected=true;sel.add(o)});
const modeLabel=el("label","Conteúdo ao trocar de mapa"),mode=document.createElement("select");mode.id="dayz-map-content-mode";mode.append(new Option("Iniciar novo mapa com mods desabilitados (recomendado)","disable"),new Option("Manter mods ativos (preflight de compatibilidade)","keep"));mode.value=mapContentMode;mode.onchange=()=>{mapContentMode=mode.value};modeLabel.append(mode);map.append(modeLabel,el("p","Desabilitar não desinstala os mods. Ao manter mods ativos, o Agent valida incompatibilidades e dependências antes de parar o servidor; compatibilidade não declarada é tratada como desconhecida.","muted"));const persistenceLabel=el("label","Persistência do mapa de destino"),persistence=document.createElement("select");persistence.id="dayz-map-persistence-mode";persistence.append(new Option("Arquivar persistência existente e iniciar limpa (recomendado)","fresh"),new Option("Manter persistência existente","keep"));persistence.value=mapPersistenceMode;persistence.onchange=()=>{mapPersistenceMode=persistence.value};persistenceLabel.append(persistence);map.append(persistenceLabel,el("p","O modo limpo preserva automaticamente a persistência anterior em backup antes de iniciar o mapa. Manter uma persistência criada com outro conjunto de mods pode causar incompatibilidade ou falha de inicialização.","muted"));
const row=el("div","","actions mt-12"),refresh=el("button","Atualizar mapas","btn"),content=el("button","Abrir Conteúdo","btn"),change=el("button","Aplicar mapa e reiniciar","btn primary");refresh.disabled=!editable;const selected=()=>((maps.missions||[]).find(m=>m.id===sel.value)||{});const sync=()=>{const m=selected();change.disabled=!editable||!m.can_activate||!!m.active||!!blockingOperation};sel.onchange=()=>{mapSelection=sel.value;sync()};sync();row.append(refresh,content,change);map.append(sel,row,el("p","Mapa atual: "+(maps.current_name||maps.current||"aguardando descoberta…")+" · disponíveis: "+((maps.counts||{}).available??0)+" · instalados na instância: "+((maps.counts||{}).installed??0),"muted"));if(blockingOperation){const due=blockingOperation.scheduled_at?fmt(blockingOperation.scheduled_at):"agora";map.append(el("p","Troca de mapa bloqueada por operação pendente: "+blockingOperation.action+" · "+blockingOperation.status+" · "+due+". Cancele ou aguarde a conclusão da operação.","muted"))}
refresh.onclick=async()=>{await req({action:"refresh_maps"});toast("Descoberta de mapas solicitada.");setTimeout(load,1500)};
content.onclick=()=>{const b=document.querySelector('[data-view="content"]');if(b)b.click();else toast("Abra a aba Conteúdo para instalar dependências de mapas comunitários.")};
change.onclick=async()=>{const m=selected();if(!m.can_activate||blockingOperation)return;const keeping=mapContentMode==="keep",fresh=mapPersistenceMode==="fresh",detail=keeping?"Os mods ativos serão mantidos somente se o preflight não encontrar incompatibilidade conhecida.":"Os mods permanecerão instalados, mas serão desabilitados no novo mapa.",persistDetail=fresh?"A persistência existente do mapa de destino será arquivada e uma nova será criada.":"A persistência existente do mapa de destino será reutilizada; isso pode ser incompatível com mudanças de mods.";if(!confirm("Alterar o mapa para "+(m.name||m.id)+"? "+detail+" "+persistDetail+" O servidor será reiniciado."))return;try{await req({action:"change_mission",mission:m.id,content_mode:mapContentMode,persistence_mode:mapPersistenceMode});toast(keeping?"Preflight e troca de mapa solicitados.":"Troca de mapa solicitada com mods desabilitados.");mapSelection=null;setTimeout(load,1500)}catch(e){toast("Falha ao solicitar troca: "+e.message);load()}};
wipe.append(el("h2","Wipe"),el("p","O wipe é independente da troca de mapa. Por padrão o DSM cria um backup antes de remover a persistência.","muted"));
const scope=document.createElement("select");scope.id="dayz-wipe-scope";scope.append(new Option("Persistência do mapa atual","persistence"),new Option("Persistência + perfis","persistence-and-profiles"));
const when=document.createElement("input");when.type="datetime-local";when.id="dayz-wipe-when";const backup=document.createElement("input");backup.type="checkbox";backup.checked=true;const bl=el("label");bl.append(backup,document.createTextNode(" Criar backup antes do wipe"));
const wr=el("div","","form-grid"),l1=el("label","Escopo"),l2=el("label","Data e hora (vazio = agora)");l1.append(scope);l2.append(when);wr.append(l1,l2,bl);
const schedule=el("button","Executar / agendar wipe","btn danger");schedule.disabled=!editable||!!blockingOperation;schedule.onclick=async()=>{const future=when.value?new Date(when.value):null,msg=future?("Agendar wipe para "+future.toLocaleString("pt-BR")+"?"):"Executar wipe agora?";if(!confirm(msg))return;try{await req({action:"wipe",scope:scope.value,backup:backup.checked,scheduled_at:future?future.toISOString():null});toast(future?"Wipe agendado.":"Wipe solicitado.");setTimeout(load,1500)}catch(e){toast("Falha ao solicitar wipe: "+e.message);load()}};wipe.append(wr,schedule);grid.append(map,wipe);v.append(grid);
const restart=el("article","","card mt-14");restart.append(el("h2","Restart automático"),el("p","Use a aba Manutenção para habilitar horário fixo ou intervalo. No DayZ o aviso e o shutdown usam o countdown nativo do messages.xml.","muted"));const go=el("button","Abrir Manutenção","btn primary");go.onclick=()=>{const b=document.getElementById("maintenance-tab");if(b)b.click()};restart.append(go);v.append(restart);
const hist=el("article","","card mt-14");hist.append(el("h2","Operações DayZ"));(data.operations||[]).forEach(op=>{const modeText=op.action==="change_mission"&&op.payload&&op.payload.content_mode?(" · mods: "+(op.payload.content_mode==="keep"?"manter":"desabilitar")):"",persistenceText=op.action==="change_mission"&&op.payload&&op.payload.persistence_mode?(" · persistência: "+(op.payload.persistence_mode==="fresh"?"nova":"manter")):"",r=el("div","","row"),left=el("span",fmt(op.scheduled_at)+" · "+op.action+modeText+persistenceText),right=el("strong",op.status||"—");r.append(left,right);if(op.status==="queued"&&["wipe","change_mission"].includes(op.action)){const cancel=el("button","Cancelar","btn");cancel.onclick=async()=>{try{await req({action:"cancel",operation_id:op.operation_id});toast("Operação cancelada.");load()}catch(e){toast("Falha ao cancelar operação: "+e.message)}};r.append(cancel)}hist.append(r);if(op.last_error)hist.append(el("small",op.last_error,"muted"));const pf=op.result&&op.result.result&&op.result.result.mod_preflight;if(pf&&pf.active_mods){hist.append(el("small","Preflight de mods: "+pf.status+" · ativos "+pf.active_mods+" · compatíveis "+pf.compatible+" · desconhecidos "+pf.unknown+" · incompatíveis "+pf.incompatible,"muted"))}});if(!(data.operations||[]).length)hist.append(el("p","Nenhuma operação registrada.","muted"));v.append(hist)}
async function load(){ensure();try{render(await req())}catch(e){if(e.status===404){const a=document.getElementById("dayz-tab"),b=document.getElementById("view-dayz");if(a)a.remove();if(b)b.remove();return}toast("Falha ao carregar Mundo & Mapa: "+e.message)}}
load();setInterval(()=>{const v=document.getElementById("view-dayz");if(v&&v.classList.contains("active"))load()},10000);
})();