(function(){"use strict";
const $=id=>document.getElementById(id);
function basic(user,password){const bytes=new TextEncoder().encode(`${user}:${password}`);let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary)}
async function json(path,body){const response=await fetch(path,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify(body),credentials:"same-origin"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
async function customerSession(){const response=await fetch("/api/auth/session",{headers:{Accept:"application/json"},credentials:"same-origin",cache:"no-store"});if(!response.ok)return null;const data=await response.json().catch(()=>({}));return data?.role==="customer"&&data?.authenticated?data:null}
const login=$("customer-login-form");
if(login){
 customerSession().then(data=>{if(data)location.replace("/customer.html")}).catch(()=>{});
 login.addEventListener("submit",async event=>{event.preventDefault();const user=$("customer-login-user").value.trim(),password=$("customer-login-password").value,message=$("customer-login-message");try{const token=basic(user,password);const sessionResponse=await fetch("/api/customer/auth/session",{method:"POST",headers:{Authorization:`Basic ${token}`,Accept:"application/json"},credentials:"same-origin",cache:"no-store"});const sessionData=await sessionResponse.json().catch(()=>({}));if(!sessionResponse.ok||sessionData.role!=="customer")throw new Error(sessionResponse.status===429?"Muitas tentativas. Aguarde e tente novamente.":"Usuário ou senha inválidos.");sessionStorage.removeItem("dsm_auth");sessionStorage.removeItem("dsm_customer_auth");const meResponse=await fetch("/api/customer/auth/me",{headers:{Accept:"application/json"},credentials:"same-origin",cache:"no-store"});const data=await meResponse.json().catch(()=>({}));if(!meResponse.ok||data.role!=="customer"||!data.authenticated)throw new Error("Não foi possível validar a sessão do cliente.");location.replace(data.must_change_password?"/customer-change-password.html":"/customer.html")}catch(error){message.textContent=error.message}})
}
const registration=$("customer-register-form");if(registration)registration.addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(registration),body=Object.fromEntries(form.entries()),message=$("customer-register-message");if(body.password!==body.password_confirmation){message.textContent="A confirmação da senha não corresponde.";return}delete body.password_confirmation;try{const data=await json("/api/customer/register",body);message.textContent="Cadastro recebido. Verifique seu e-mail para ativar a conta.";registration.reset();if(data.verification_token)location.href=`/customer-verify-email.html?token=${encodeURIComponent(data.verification_token)}`}catch(error){message.textContent=error.message}});
const recovery=$("customer-recovery-form");if(recovery)recovery.addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(recovery),message=$("customer-recovery-message");try{const data=await json("/api/customer/password-recovery",Object.fromEntries(form.entries()));message.textContent="Se a conta existir, as instruções de recuperação serão enviadas.";if(data.recovery_token)location.href=`/customer-reset-password.html?token=${encodeURIComponent(data.recovery_token)}`}catch(error){message.textContent=error.message}});
const reset=$("customer-reset-form");if(reset){const params=new URLSearchParams(location.search),token=params.get("token")||"";$("customer-reset-token").value=token;reset.addEventListener("submit",async event=>{event.preventDefault();const body=Object.fromEntries(new FormData(reset).entries()),message=$("customer-reset-message");if(!body.token){message.textContent="Link de recuperação inválido.";return}if(body.password!==body.password_confirmation){message.textContent="A confirmação da senha não corresponde.";return}delete body.password_confirmation;try{await json("/api/customer/password-reset",body);message.textContent="Senha alterada. Você já pode entrar com a nova senha.";reset.reset()}catch(error){message.textContent=error.message}})}
})();
