(function(){
"use strict";
const $=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";const params=new URLSearchParams(location.search);const customerId=params.get("id")||"";let requestedInstance=params.get("instance")||"";let currentInstances=[],selectedInstance=null,filePath=".",runtimeSummary={},availableContent=[],installedContent=[],selectedRuntime=null;
async function request(path,options={}){const headers={Authorization:`Basic ${auth()}`,Accept:"application/json"};if(options.body)headers["Content-Type"]="application/json";let response;try{response=await fetch(path,{...options,headers,credentials:"same-origin",cache:"no-store"})}catch{throw new Error("Falha de comunicação com o servidor.")}if(response.status===401){sessionStorage.removeItem("dsm_auth");location.href="/login.html";throw new Error("Sessão encerrada")};const type=response.headers.get("content-type")||"",data=type.includes("application/json")?await response.json().catch(()=>({})):await response.blob();if(!response.ok)throw new Error(data.error||data.message||`HTTP ${response.status}`);return data}
function value(label,text){const item=document.createElement("div"),small=document.createElement("small"),strong=document.createElement("strong");small.textContent=label;strong.textContent=text??"—";item.append(small,strong);return item}
function option(value,label,current){const el=document.createElement("option");el.value=value;el.textContent=label;el.selected=value===current;return el}
function bytes(value){const n=Number(value);if(!Number.isFinite(n))return"—";const units=["B","KB","MB","GB","TB"];let v=n,i=0;while(v>=1024&&i<units.length-1){v/=1024;i++}return`${v.toFixed(i?1:0)} ${units[i]}`}
function pct(value){const n=Number(value);return Number.isFinite(n)?`${n.toFixed(1)}%`:"—"}
function identity(){if(!selectedInstance)throw new Error("Nenhuma instância selecionada.");const server=selectedInstance.node_id||"";if(!server)throw new Error("A instância ainda não possui Node válido.");return{server,game:selectedInstance.game_id,instance:selectedInstance.id}}
function query(extra={}){return new URLSearchParams({...identity(),...extra}).toString()}
function instancePath(){const i=identity();return`/opt/dsm/instances/${i.server}/${i.game}/${i.instance}`}
function notice(text){$("admin-instance-notice").textContent=text||""}
async function changeRole(username,accountRole){await request("/api/admin/customer/member-role",{method:"POST",body:JSON.stringify({customer_id:customerId,username,account_role:accountRole})});$("password-result").textContent=`Função de ${username} atualizada para ${accountRole}.`;await loadCustomer()}
async function changeAccess(username,instanceId,profile){await request("/api/admin/customer/access",{method:"POST",body:JSON.stringify({customer_id:customerId,username,instance_id:instanceId,permission_profile:profile})});$("password-result").textContent=`Acesso de ${username} atualizado.`;await loadCustomer()}
function renderUsers(users){const root=$("detail-users");root.replaceChildren();for(const user of users){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=user.username;const info=document.createElement("p");info.textContent=`${user.active?"Ativo":"Desativado"}${user.email?` · ${user.email}`:""}`;const state=document.createElement("small");state.textContent=user.must_change_password?"Troca de senha obrigatória no próximo acesso":"Senha definitiva configurada";const roleLabel=document.createElement("label");roleLabel.textContent="Função na conta ";const role=document.createElement("select");role.append(option("owner","Owner",user.account_role||"member"),option("manager","Manager",user.account_role||"member"),option("member","Member",user.account_role||"member"));role.addEventListener("change",()=>changeRole(user.username,role.value).catch(showPassword));roleLabel.append(role);card.append(title,info,state,roleLabel);if(currentInstances.length){const accessTitle=document.createElement("strong");accessTitle.textContent="Acesso às instâncias";card.append(accessTitle);for(const instance of currentInstances){const accessLabel=document.createElement("label");accessLabel.textContent=`${instance.name||instance.id} (${instance.game_id}) `;const access=document.createElement("select"),current=(user.instance_access||{})[instance.id]||"";access.append(option("","Sem acesso",current),option("viewer","Viewer",current),option("operator","Operator",current),option("manager","Manager",current));access.addEventListener("change",()=>changeAccess(user.username,instance.id,access.value).catch(showPassword));accessLabel.append(access);card.append(accessLabel)}}const reset=document.createElement("button");reset.type="button";reset.textContent="Gerar senha provisória";reset.addEventListener("click",()=>resetPassword(user.username).catch(showPassword));card.append(reset);root.append(card)}if(!users.length)root.textContent="Nenhum usuário vinculado."}
function renderContracts(items){const root=$("detail-contracts");root.replaceChildren();for(const item of items){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=`${item.game_id} · ${item.id}`;const p=document.createElement("p");p.textContent=`${item.status} · ${item.instances_used||0} de ${item.instance_limit} instância(s)${item.ends_at?` · até ${item.ends_at}`:""}`;card.append(title,p);root.append(card)}if(!items.length)root.textContent="Nenhum contrato cadastrado."}
function renderInstances(items){const root=$("detail-instances");root.replaceChildren();for(const item of items){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=item.name||item.id;const p=document.createElement("p");p.textContent=`${item.game_id} · ${item.status} · Agent ${item.agent_id||"—"} · Node ${item.node_id||"—"} · Contrato ${item.contract_id||"—"}`;const manage=document.createElement("button");manage.type="button";manage.textContent="Administrar instância";manage.disabled=!item.node_id;manage.addEventListener("click",()=>openInstance(item.id).catch(error=>notice(error.message)));card.append(title,p,manage);root.append(card)}if(!items.length)root.textContent="Nenhuma instância criada."}
function showPassword(error){$("password-result").textContent=error.message||String(error)}
async function resetPassword(username){if(!confirm(`Gerar uma nova senha provisória para ${username}?`))return;const data=await request("/api/admin/customer/password-reset",{method:"POST",body:JSON.stringify({username})}),delivery=data.delivered?" A nova senha também foi enviada ao e-mail cadastrado.":" O envio automático não foi realizado; comunique a senha ao cliente por um canal seguro.";$("password-result").textContent=`Senha provisória de ${username}: ${data.temporary_password}. O usuário deverá alterá-la no próximo acesso.${delivery}`;await loadCustomer()}
async function createContract(){const gameId=$("contract-game").value;if(!gameId)throw new Error("Selecione um jogo disponível no catálogo.");const payload={customer_id:customerId,game_id:gameId,instance_limit:Number($("contract-limit").value||1),id:$("contract-id").value.trim(),ends_at:$("contract-ends").value.trim()};const data=await request("/api/admin/customer/contracts",{method:"POST",body:JSON.stringify(payload)});$("contract-result").textContent=`Contrato ${data.id} criado para ${data.game_id}.`;$("contract-id").value="";await loadCustomer()}
async function loadGames(){const select=$("contract-game"),button=$("contract-create");select.replaceChildren(new Option("Carregando catálogo…",""));select.disabled=true;button.disabled=true;try{const data=await request("/api/admin/catalog/games"),games=Array.isArray(data.games)?data.games:[];select.replaceChildren();if(!games.length){select.append(new Option("Nenhum jogo disponível no catálogo",""));$("contract-result").textContent="O Catalog v2 não possui jogos disponíveis para contratação.";return}select.append(new Option("Selecione um jogo",""));for(const game of games)select.append(new Option(game.name||game.id,game.id));select.disabled=false;button.disabled=false}catch(error){select.replaceChildren(new Option("Falha ao carregar catálogo",""));$("contract-result").textContent=error.message}}
async function loadCustomer(){if(!customerId)throw new Error("Customer não informado");$("detail-retry").hidden=true;const data=await request(`/api/admin/customer?id=${encodeURIComponent(customerId)}`),customer=data.customer||{};currentInstances=data.instances||[];$("detail-name").textContent=customer.name||customer.id||"Cliente";$("detail-meta").textContent=`${customer.id||""} · ${customer.status||""}`;const grid=$("detail-data");grid.replaceChildren(value("ID",customer.id),value("Nome",customer.name),value("E-mail",customer.email),value("Telefone",customer.phone),value("Controller",customer.controller_id),value("Status",customer.status));renderUsers(data.users||[]);renderContracts(data.contracts||[]);renderInstances(currentInstances);if(selectedInstance){selectedInstance=currentInstances.find(item=>item.id===selectedInstance.id)||null}if(requestedInstance&&currentInstances.some(item=>item.id===requestedInstance)){const id=requestedInstance;requestedInstance="";await openInstance(id)}}
async function load(){try{await Promise.all([loadCustomer(),loadGames()])}catch(error){$("detail-name").textContent="Falha ao carregar cliente";$("detail-meta").textContent=error.message;$("detail-retry").hidden=false}}
async function openInstance(instanceId){selectedInstance=currentInstances.find(item=>item.id===instanceId);if(!selectedInstance)throw new Error("Instância não encontrada neste Customer.");if(!selectedInstance.node_id)throw new Error("A instância ainda não possui Node/Agent válido.");filePath=".";$("admin-instance-panel").hidden=false;$("admin-instance-title").textContent=selectedInstance.name||selectedInstance.id;$("admin-instance-meta").textContent=`${selectedInstance.game_id} · ${selectedInstance.id} · Agent ${selectedInstance.agent_id||"—"} · Node ${selectedInstance.node_id}`;history.replaceState(null,"",`/customer-admin.html?id=${encodeURIComponent(customerId)}&instance=${encodeURIComponent(instanceId)}`);await loadInstanceAll();$("admin-instance-panel").scrollIntoView({behavior:"smooth",block:"start"})}
function closeInstance(){selectedInstance=null;$("admin-instance-panel").hidden=true;history.replaceState(null,"",`/customer-admin.html?id=${encodeURIComponent(customerId)}`)}
async function loadInstanceAll(){notice("Atualizando instância…");await Promise.allSettled([loadInstanceSummary(),loadInstanceTelemetry(),loadNetwork(),loadLogs(),loadConfigs(),loadFiles(),loadContent(),loadBackups(),loadEvents()]);notice("")}
async function loadInstanceSummary(){runtimeSummary=await request(`/api/runtime?${query()}`);const status=runtimeSummary.server_state?.status?.state||runtimeSummary.server_state?.status||selectedInstance.status||"unknown",meta=runtimeSummary.instance_metadata||{};const root=$("admin-instance-overview");root.replaceChildren(value("Status",status),value("Nome",meta.display_name||selectedInstance.name),value("Game",selectedInstance.game_id),value("Agent",selectedInstance.agent_id),value("Node",selectedInstance.node_id),value("Contrato",selectedInstance.contract_id))}
async function loadInstanceTelemetry(){if(!selectedInstance.agent_id)return;const data=await request(`/api/admin/agent/detail?agent_id=${encodeURIComponent(selectedInstance.agent_id)}`),item=(data.instances||[]).find(row=>row.id===selectedInstance.id),t=item?.telemetry||{},root=$("admin-instance-overview");root.append(value("CPU",pct(t.cpu_percent)),value("RAM",bytes(t.memory_bytes)),value("PID",t.pid),value("Tasks",t.tasks),value("I/O leitura",bytes(t.io_read_bytes)),value("I/O escrita",bytes(t.io_write_bytes)))}
async function lifecycle(action){if(action!=="start"&&!confirm(`${action==="stop"?"Parar":"Reiniciar"} esta instância?`))return;notice(`Executando ${action}…`);await request(`/api/instance/${action}`,{method:"POST",body:JSON.stringify(identity())});notice(`Operação ${action} concluída.`);await Promise.allSettled([loadInstanceSummary(),loadInstanceTelemetry()])}
async function reinstall(){if(!confirm("Reinstalar esta instância usando o game-data disponível no Agent?"))return;const preserve_config=confirm("Preservar arquivos de configuração?"),preserve_map=confirm("Preservar mapa/missão e dados persistentes?");if(!preserve_config&&!preserve_map&&!confirm("Reinstalação limpa. Continuar?"))return;notice("Reinstalando instância…");await request("/api/instance/reinstall/v2",{method:"POST",body:JSON.stringify({...identity(),preserve_config,preserve_map})});notice("Reinstalação concluída.");await loadInstanceAll()}
async function loadNetwork(){const root=$("admin-instance-network");root.replaceChildren(value("Agent",selectedInstance.agent_id),value("Node",selectedInstance.node_id));if(!selectedInstance.agent_id)return;try{const data=await request(`/api/agent/ports?agent_id=${encodeURIComponent(selectedInstance.agent_id)}`);for(const range of data.ranges||[])root.append(value(`${String(range.protocol||"").toUpperCase()} ${range.start_port}-${range.end_port}`,`${range.reserved||0} reservadas · ${range.available||0} disponíveis`))}catch(error){root.append(value("Portas",error.message))}}
async function loadLogs(){const data=await request(`/api/instance/logs?${query({limit:"400"})}`);$("admin-instance-logs").textContent=(data.logs||[]).join("\n")||"Nenhum registro disponível."}
async function loadConfigs(){const select=$("admin-instance-config-file"),data=await request(`/api/instance/config?instance=${encodeURIComponent(instancePath())}`);select.replaceChildren();for(const file of data.files||[])select.append(new Option(file,file));if((data.files||[]).length)await loadConfig();else $("admin-instance-config-editor").value=""}
async function loadConfig(){const file=$("admin-instance-config-file").value;if(!file)return;const data=await request(`/api/instance/config?${new URLSearchParams({instance:instancePath(),file})}`);$("admin-instance-config-editor").value=data.content||""}
async function saveConfig(){const file=$("admin-instance-config-file").value;if(!file)throw new Error("Selecione um arquivo.");await request("/api/instance/config",{method:"POST",body:JSON.stringify({instance:instancePath(),file,content:$("admin-instance-config-editor").value})});notice("Configuração salva.")}
function fileQuery(extra={}){return query({path:filePath,...extra})}
async function loadFiles(){const data=await request(`/api/instance/files?${fileQuery()}`),root=$("admin-instance-files");$("admin-instance-file-path").textContent=filePath==="."?"/":`/${filePath}`;root.replaceChildren();for(const entry of data.entries||[]){const row=document.createElement("article");row.className="customer-admin-result";const title=document.createElement("strong");title.textContent=`${entry.directory?"📁":"📄"} ${entry.name}`;const meta=document.createElement("small");meta.textContent=entry.directory?"Diretório":`${bytes(entry.size)} · ${new Date((entry.modified_at||0)*1000).toLocaleString()}`;const open=document.createElement("button");open.type="button";open.textContent=entry.directory?"Abrir":entry.editable?"Editar":"Baixar";open.onclick=()=>entry.directory?openDirectory(entry.name):entry.editable?openTextFile(entry.name).catch(error=>notice(error.message)):downloadFile(entry.name).catch(error=>notice(error.message));row.append(title,meta,open);root.append(row)}if(!(data.entries||[]).length)root.textContent="Pasta vazia."}
function openDirectory(name){filePath=filePath==="."?name:`${filePath}/${name}`;loadFiles().catch(error=>notice(error.message))}
function parentDirectory(){if(filePath===".")return;const parts=filePath.split("/");parts.pop();filePath=parts.join("/")||".";loadFiles().catch(error=>notice(error.message))}
function relativeFile(name){return filePath==="."?name:`${filePath}/${name}`}
async function openTextFile(name){const path=relativeFile(name),data=await request(`/api/instance/file/text?${query({path})}`);$("admin-instance-file-editor-panel").hidden=false;$("admin-instance-file-editor-path").textContent=`/${path}`;$("admin-instance-file-editor").dataset.path=path;$("admin-instance-file-editor").value=data.content||""}
async function saveTextFile(){const path=$("admin-instance-file-editor").dataset.path;if(!path)throw new Error("Nenhum arquivo aberto.");await request("/api/instance/file/text",{method:"POST",body:JSON.stringify({...identity(),path,content:$("admin-instance-file-editor").value})});notice("Arquivo salvo.");await loadFiles()}
function closeTextFile(){$("admin-instance-file-editor-panel").hidden=true;$("admin-instance-file-editor").value="";delete $("admin-instance-file-editor").dataset.path}
async function downloadFile(name){const path=relativeFile(name),blob=await request(`/api/instance/file?${query({path})}`),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=name;document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url)}
async function loadContent(){const game=encodeURIComponent(selectedInstance.game_id),path=encodeURIComponent(instancePath()),[runtimeData,contentData,installedData]=await Promise.all([request(`/api/catalog/runtimes?game=${game}`),request(`/api/catalog/content?game=${game}`),request(`/api/catalog/installed?instance=${path}`)]);const runtimes=Array.isArray(runtimeData)?runtimeData:(runtimeData.runtimes||[]),runtimeId=runtimeSummary.runtime_definition?.id;selectedRuntime=runtimes.find(item=>item.id===runtimeId)||runtimes[0]||null;availableContent=Array.isArray(contentData)?contentData:(contentData.content||contentData.entries||[]);installedContent=Array.isArray(installedData)?installedData:(installedData.entries||installedData.content||[]);renderContent()}
function renderContent(){const available=$("admin-instance-content-available"),installed=$("admin-instance-content-installed");available.replaceChildren();for(const entry of availableContent){const label=document.createElement("label");label.className="customer-admin-result";const input=document.createElement("input");input.type="checkbox";input.value=entry.id;const text=document.createElement("span");text.textContent=`${entry.name||entry.id} · ${entry.content_type||"conteúdo"}`;label.append(input,text);available.append(label)}if(!availableContent.length)available.textContent="Nenhum conteúdo adicional disponível.";installed.replaceChildren();for(const entry of installedContent){const row=document.createElement("article");row.className="customer-admin-result";row.textContent=`${entry.name||entry.id||entry.content_id} ${entry.version||""}`;installed.append(row)}if(!installedContent.length)installed.textContent="Nenhum conteúdo adicional instalado."}
function contentRequest(){if(!selectedRuntime)throw new Error("Nenhum runtime disponível.");const requirements=selectedRuntime.requirements||{};return{schema_version:2,runtime:{id:selectedRuntime.id,game:selectedRuntime.game||selectedInstance.game_id,version:selectedRuntime.version?.value||selectedRuntime.version?.version||"current",edition:selectedRuntime.edition||null,loader:selectedRuntime.loader||null,loader_version:selectedRuntime.loader_version||null},environment:{os:(requirements.os||[])[0]||null,architecture:(requirements.architectures||[])[0]||null,java:selectedRuntime.process?.engine==="java"?(requirements.java?.min||null):null},content:[...$("admin-instance-content-available").querySelectorAll("input:checked")].map(input=>input.value),installed_content:installedContent.map(entry=>entry.id||entry.content_id).filter(Boolean)}}
async function installContent(){const req=contentRequest();if(!req.content.length)throw new Error("Selecione ao menos um conteúdo.");await request("/api/catalog/install",{method:"POST",body:JSON.stringify({instance:instancePath(),request:req})});notice("Conteúdo instalado.");await loadContent()}
async function verifyContent(){await request("/api/catalog/verify",{method:"POST",body:JSON.stringify({instance:instancePath()})});notice("Integridade do conteúdo verificada.")}
async function loadBackups(){const data=await request(`/api/instance/backups?${query()}`),root=$("admin-instance-backups");root.replaceChildren();for(const backup of data.backups||[]){const row=document.createElement("article");row.className="customer-admin-result";const text=document.createElement("span");text.textContent=`${backup.name} · ${bytes(backup.size)}`;const restore=document.createElement("button");restore.textContent="Restaurar";restore.onclick=()=>backupAction("restore",backup.name).catch(error=>notice(error.message));const remove=document.createElement("button");remove.textContent="Excluir";remove.onclick=()=>backupAction("delete",backup.name).catch(error=>notice(error.message));row.append(text,restore,remove);root.append(row)}if(!(data.backups||[]).length)root.textContent="Nenhum backup disponível."}
async function createBackup(){await request("/api/instance/backup/create",{method:"POST",body:JSON.stringify(identity())});notice("Backup criado.");await loadBackups()}
async function backupAction(action,name){if(!confirm(`${action==="restore"?"Restaurar":"Excluir"} ${name}?`))return;await request(`/api/instance/backup/${action}`,{method:"POST",body:JSON.stringify({...identity(),name})});notice(action==="restore"?"Backup restaurado.":"Backup excluído.");await loadBackups()}
async function loadEvents(){const data=await request("/api/timeline?limit=200"),events=(Array.isArray(data)?data:(data.events||[])).filter(event=>String(event.instance_id||event.instance||event.payload?.instance_id||"")===selectedInstance.id),root=$("admin-instance-events");root.replaceChildren();for(const event of events.slice(0,30)){const row=document.createElement("article");row.className="customer-admin-result";const title=document.createElement("strong");title.textContent=event.event_type||event.type||event.title||"Evento";const detail=document.createElement("p");detail.textContent=event.message||event.payload?.message||event.severity||"";row.append(title,detail);root.append(row)}if(!events.length)root.textContent="Nenhum evento recente encontrado para esta instância."}
$("contract-create").addEventListener("click",()=>createContract().catch(error=>{$("contract-result").textContent=error.message}));$("detail-retry").addEventListener("click",load);$("admin-instance-close").onclick=closeInstance;$("admin-instance-refresh").onclick=()=>loadInstanceAll().catch(error=>notice(error.message));$("admin-instance-start").onclick=()=>lifecycle("start").catch(error=>notice(error.message));$("admin-instance-stop").onclick=()=>lifecycle("stop").catch(error=>notice(error.message));$("admin-instance-restart").onclick=()=>lifecycle("restart").catch(error=>notice(error.message));$("admin-instance-reinstall").onclick=()=>reinstall().catch(error=>notice(error.message));$("admin-instance-config-file").onchange=()=>loadConfig().catch(error=>notice(error.message));$("admin-instance-config-save").onclick=()=>saveConfig().catch(error=>notice(error.message));$("admin-instance-file-up").onclick=parentDirectory;$("admin-instance-file-refresh").onclick=()=>loadFiles().catch(error=>notice(error.message));$("admin-instance-file-save").onclick=()=>saveTextFile().catch(error=>notice(error.message));$("admin-instance-file-close").onclick=closeTextFile;$("admin-instance-content-install").onclick=()=>installContent().catch(error=>notice(error.message));$("admin-instance-content-verify").onclick=()=>verifyContent().catch(error=>notice(error.message));$("admin-instance-backup-create").onclick=()=>createBackup().catch(error=>notice(error.message));if(!auth())location.href="/login.html";else load();
})();
