(function(){
"use strict";const $=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";const customerId=new URLSearchParams(location.search).get("id")||"";let currentInstances=[];
async function request(path,options={}){const headers={Authorization:`Basic ${auth()}`,Accept:"application/json"};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});if(response.status===401){sessionStorage.removeItem("dsm_auth");location.href="/login.html";throw new Error("Sessão encerrada")};const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function value(label,text){const item=document.createElement("div");const small=document.createElement("small");small.textContent=label;const strong=document.createElement("strong");strong.textContent=text??"—";item.append(small,strong);return item}
function option(value,label,current){const el=document.createElement("option");el.value=value;el.textContent=label;el.selected=value===current;return el}
async function changeRole(username,accountRole){await request("/api/admin/customer/member-role",{method:"POST",body:JSON.stringify({customer_id:customerId,username,account_role:accountRole})});$("password-result").textContent=`Função de ${username} atualizada para ${accountRole}.`;await load()}
async function changeAccess(username,instanceId,profile){await request("/api/admin/customer/access",{method:"POST",body:JSON.stringify({customer_id:customerId,username,instance_id:instanceId,permission_profile:profile})});$("password-result").textContent=`Acesso de ${username} atualizado.`;await load()}
function renderUsers(users){const root=$("detail-users");root.replaceChildren();for(const user of users){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=user.username;const info=document.createElement("p");info.textContent=`${user.active?"Ativo":"Desativado"}${user.email?` · ${user.email}`:""}`;const state=document.createElement("small");state.textContent=user.must_change_password?"Troca de senha obrigatória no próximo acesso":"Senha definitiva configurada";const roleLabel=document.createElement("label");roleLabel.textContent="Função na conta ";const role=document.createElement("select");role.append(option("owner","Owner",user.account_role||"member"),option("manager","Manager",user.account_role||"member"),option("member","Member",user.account_role||"member"));role.addEventListener("change",()=>changeRole(user.username,role.value).catch(showPassword));roleLabel.append(role);card.append(title,info,state,roleLabel);if(currentInstances.length){const accessTitle=document.createElement("strong");accessTitle.textContent="Acesso às instâncias";card.append(accessTitle);for(const instance of currentInstances){const accessLabel=document.createElement("label");accessLabel.textContent=`${instance.name||instance.id} (${instance.game_id}) `;const access=document.createElement("select");const current=(user.instance_access||{})[instance.id]||"";access.append(option("","Sem acesso",current),option("viewer","Viewer",current),option("operator","Operator",current),option("manager","Manager",current));access.addEventListener("change",()=>changeAccess(user.username,instance.id,access.value).catch(showPassword));accessLabel.append(access);card.append(accessLabel)}}const reset=document.createElement("button");reset.type="button";reset.textContent="Gerar senha provisória";reset.addEventListener("click",()=>resetPassword(user.username).catch(showPassword));card.append(reset);root.append(card)}if(!users.length)root.textContent="Nenhum usuário vinculado."}
function renderContracts(items){const root=$("detail-contracts");root.replaceChildren();for(const item of items){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=`${item.game_id} · ${item.id}`;const p=document.createElement("p");p.textContent=`${item.status} · ${item.instances_used||0} de ${item.instance_limit} instância(s)${item.ends_at?` · até ${item.ends_at}`:""}`;card.append(title,p);root.append(card)}if(!items.length)root.textContent="Nenhum contrato cadastrado."}
function renderInstances(items){const root=$("detail-instances");root.replaceChildren();for(const item of items){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=item.name||item.id;const p=document.createElement("p");p.textContent=`${item.game_id} · ${item.status} · Agent ${item.agent_id||"—"} · Contrato ${item.contract_id||"—"}`;card.append(title,p);root.append(card)}if(!items.length)root.textContent="Nenhuma instância criada."}
function showPassword(error){$("password-result").textContent=error.message||String(error)}
async function resetPassword(username){if(!confirm(`Gerar uma nova senha provisória para ${username}?`))return;const data=await request("/api/admin/customer/password-reset",{method:"POST",body:JSON.stringify({username})});const delivery=data.delivered?" A nova senha também foi enviada ao e-mail cadastrado.":" O envio automático não foi realizado; comunique a senha ao cliente por um canal seguro.";$("password-result").textContent=`Senha provisória de ${username}: ${data.temporary_password}. O usuário deverá alterá-la no próximo acesso.${delivery}`;await load()}
async function createContract(){const payload={customer_id:customerId,game_id:$("contract-game").value.trim(),instance_limit:Number($("contract-limit").value||1),id:$("contract-id").value.trim(),ends_at:$("contract-ends").value.trim()};const data=await request("/api/admin/customer/contracts",{method:"POST",body:JSON.stringify(payload)});$("contract-result").textContent=`Contrato ${data.id} criado para ${data.game_id}.`;$("contract-id").value="";await load()}
async function load(){if(!customerId)throw new Error("Customer não informado");const data=await request(`/api/admin/customer?id=${encodeURIComponent(customerId)}`);const customer=data.customer||{};currentInstances=data.instances||[];$("detail-name").textContent=customer.name||customer.id;$("detail-meta").textContent=`${customer.id||""} · ${customer.status||""}`;const grid=$("detail-data");grid.replaceChildren(value("ID",customer.id),value("Nome",customer.name),value("E-mail",customer.email),value("Telefone",customer.phone),value("Controller",customer.controller_id),value("Status",customer.status));renderUsers(data.users||[]);renderContracts(data.contracts||[]);renderInstances(currentInstances)}
$("contract-create").addEventListener("click",()=>createContract().catch(error=>{$("contract-result").textContent=error.message}));if(!auth())location.href="/login.html";else load().catch(error=>{$("detail-meta").textContent=error.message});
})();
