(function(){
"use strict";
const $=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";
async function request(path,options={}){const headers={Authorization:`Basic ${auth()}`,Accept:"application/json"};if(options.body)headers["Content-Type"]="application/json";const response=await fetch(path,{...options,headers});if(response.status===401){sessionStorage.removeItem("dsm_auth");location.href="/login.html";throw new Error("Sessão encerrada")};const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function show(text){$("customer-create-result").textContent=text}
function render(items){const root=$("customer-results");root.replaceChildren();for(const item of items){const card=document.createElement("article");card.className="customer-admin-result";const title=document.createElement("h3");title.textContent=item.name||item.id;const meta=document.createElement("p");meta.textContent=`${item.id} · ${item.status||"—"}${item.email?` · ${item.email}`:""}`;const users=document.createElement("small");users.textContent=(item.users||[]).map(user=>`${user.username} (${user.account_role})`).join(" · ")||"Sem usuários";const open=document.createElement("button");open.type="button";open.textContent="Abrir cliente";open.addEventListener("click",()=>{location.href=`/customer-admin.html?id=${encodeURIComponent(item.id)}`});card.append(title,meta,users,open);root.append(card)}if(!items.length)root.textContent="Nenhum cliente encontrado."}
async function search(){const q=$("customer-search").value.trim();const data=await request(`/api/admin/customers?q=${encodeURIComponent(q)}`);render(data.customers||[])}
async function create(){const payload={id:$("customer-id").value.trim(),name:$("customer-name").value.trim(),username:$("customer-username").value.trim(),email:$("customer-email").value.trim(),phone:$("customer-phone").value.trim()};const data=await request("/api/admin/customers",{method:"POST",body:JSON.stringify(payload)});show(`Cliente criado. Login: ${data.username}. Senha provisória: ${data.temporary_password}. O cliente deverá alterá-la no primeiro acesso.`);await search()}
$("customer-search-button").addEventListener("click",()=>search().catch(error=>show(error.message)));$("customer-search").addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();search().catch(error=>show(error.message))}});$("customer-create").addEventListener("click",()=>create().catch(error=>show(error.message)));if(!auth())location.href="/login.html";else search().catch(error=>show(error.message));
})();
