"use strict";
const HOME_API="/api";
const $=id=>document.getElementById(id);
function auth(){const token=sessionStorage.getItem("dsm_auth");if(!token){location.replace("/login.html");throw new Error("auth required")}return {Authorization:`Basic ${token}`,Accept:"application/json"}}
async function get(path){try{const r=await fetch(`${HOME_API}${path}`,{headers:auth(),cache:"no-store"});if(r.status===401){sessionStorage.clear();location.replace("/login.html");return null}if(!r.ok)return null;return await r.json()}catch(e){console.warn("[Capivara Home]",path,e);return null}}
function text(id,value,fallback="—"){const el=$(id);if(el)el.textContent=value??fallback}
function esc(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function isOnline(a){return ["online","healthy","ok","active","running"].includes(String(a?.health_status||a?.health||a?.status||"").toLowerCase())}
function formatTime(value){if(!value)return "—";const d=typeof value==="number"?new Date(value*1000):new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}
function eventText(e){const type=String(e?.type||e?.action||"Evento").replaceAll("_"," ").toLowerCase();const msg=e?.message||e?.details||e?.data?.message||"";return msg?`${type} · ${msg}`:type}
function renderAgents(result){const agents=Array.isArray(result?.agents)?result.agents:[];const online=agents.filter(isOnline).length;const instances=agents.reduce((n,a)=>n+Number(a.instance_count||0),0);text("home-agent-total",agents.length);text("home-agent-online",`${online} online`);text("home-agent-offline",`${Math.max(0,agents.length-online)} offline`);text("home-instance-total",instances);text("home-running-total",agents.reduce((n,a)=>n+Number(a.running_instance_count||a.instances_running||0),0));text("home-infra-agents",agents.length);text("home-infra-online",online);const list=$("home-agent-bars");if(list){list.innerHTML=agents.slice(0,7).map(a=>{const count=Number(a.instance_count||0);const pct=Math.min(100,count*10);return `<div class="cap-bar-row"><span>${esc(a.name||a.id)}</span><div class="cap-bar"><i style="width:${pct}%"></i></div><b>${count}</b></div>`}).join("")||'<div class="cap-empty">Nenhum Agent registrado.</div>'}const health=$("home-health-agents");if(health){health.textContent=agents.length?`${online} / ${agents.length} online`:"Nenhum Agent";health.className=online===agents.length&&agents.length?"cap-good":"cap-warn"}}
function renderInfrastructure(data){let regions=0,datacenters=0;function walk(v){if(!v)return;if(Array.isArray(v)){v.forEach(walk);return}if(typeof v!=="object")return;if(v.type==="region")regions++;if(v.type==="datacenter")datacenters++;Object.values(v).forEach(walk)}walk(data);text("home-infra-regions",regions);text("home-infra-datacenters",datacenters)}
function renderTimeline(result){const events=Array.isArray(result)?result:(result?.events||[]);const list=$("home-events");if(!list)return;list.innerHTML=events.slice(0,5).map(e=>`<div class="cap-event"><time>${esc(formatTime(e.timestamp||e.time))}</time><i class="cap-event-dot"></i><div><p>${esc(eventText(e))}</p><small>${esc(e.category||e.source||"Sistema")}</small></div></div>`).join("")||'<div class="cap-empty">Nenhuma atividade recente.</div>';const important=events.filter(e=>["warning","warn","error","critical","fatal"].includes(String(e.level||"").toLowerCase())).slice(0,3);const alerts=$("home-alerts");if(alerts){alerts.innerHTML=important.map(e=>{const critical=["error","critical","fatal"].includes(String(e.level).toLowerCase());return `<article class="cap-alert ${critical?"":"warning"}"><strong class="${critical?"cap-bad":"cap-warn"}">${esc(String(e.level||"WARNING").toUpperCase())}</strong><p>${esc(eventText(e))}</p><time>${esc(formatTime(e.timestamp||e.time))}</time></article>`}).join("")||'<div class="cap-empty">Nenhum alerta importante no período.</div>';text("home-alert-total",important.length)}}
function renderHealth(result){const d=result?.data||result||{};const ok=String(d.status||"").toLowerCase();text("home-controller-health",d.status||"Operacional");const dot=$("home-controller-dot");if(dot&&["failed","critical","offline","error"].includes(ok))dot.classList.add("off")}
function renderUser(user){text("home-user-name",user?.username||"Usuário");text("home-user-role",user?.role||"");document.querySelectorAll(".admin-only").forEach(e=>e.style.display=user?.role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(e=>e.style.display=["admin","controller"].includes(user?.role)?"":"none")}
async function refresh(){const [user,agents,infra,timeline,health]=await Promise.all([get("/whoami"),get("/agents"),get("/infrastructure?active_only=true"),get("/timeline?limit=30"),get("/health")]);if(user)renderUser(user);renderAgents(agents);renderInfrastructure(infra);renderTimeline(timeline);renderHealth(health);text("home-last-refresh",new Date().toLocaleTimeString("pt-BR"))}
async function loadSidebar(){const target=$("sidebar-component");if(!target)return;const r=await fetch("/components/sidebar.html",{cache:"no-store"});if(r.ok)target.innerHTML=await r.text();const logout=$("btn-logout");if(logout)logout.onclick=()=>{sessionStorage.clear();location.replace("/login.html")}}
document.addEventListener("DOMContentLoaded",async()=>{await loadSidebar();$("home-menu-toggle")?.addEventListener("click",()=>{if(innerWidth<=760)document.body.classList.toggle("sidebar-open");else document.body.classList.toggle("cap-sidebar-collapsed")});$("home-refresh")?.addEventListener("click",refresh);await refresh();setInterval(refresh,30000)});