"use strict";

const API = "/api";

function byId(id){return document.getElementById(id);}
function controllerHeaders(json=false){const headers={Accept:"application/json","X-Capivara-Auth-Area":"controller"};if(json)headers["Content-Type"]="application/json";return headers;}
async function request(path,options={}){const method=String(options.method||"GET").toUpperCase();const init={method,headers:controllerHeaders(options.body!==undefined),credentials:"same-origin",cache:"no-store"};if(options.body!==undefined)init.body=JSON.stringify(options.body);const response=await fetch(`${API}${path}`,init);if(response.status===401){window.location.replace("/login.html");return null;}const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||body.message||`HTTP ${response.status}`);return body;}
function showError(message=""){const box=byId("infra-error");if(!box)return;box.hidden=!message;box.textContent=message;}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});}finally{window.location.replace("/login.html");}}
async function loadSidebar(){const target=byId("sidebar-component");if(!target)return;const response=await fetch("/components/sidebar-v3.html",{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(response.status===401){window.location.replace("/login.html");return;}if(response.ok)target.innerHTML=await response.text();const button=byId("btn-logout");if(button)button.addEventListener("click",logout);const toggle=byId("infra-menu-toggle");if(toggle)toggle.addEventListener("click",()=>document.body.classList.toggle("cap-sidebar-open"));const current=location.pathname.split("/").pop()||"infrastructure.html";document.querySelectorAll(".cap-sidebar-v3 a").forEach(link=>{link.classList.remove("active");const href=(link.getAttribute("href")||"").split("#")[0];if(href===current)link.classList.add("active");});}
function collect(value,type,out=[]){if(Array.isArray(value)){value.forEach(item=>collect(item,type,out));return out;}if(!value||typeof value!=="object")return out;if(value.type===type)out.push(value);Object.values(value).forEach(child=>{if(child&&typeof child==="object")collect(child,type,out);});return out;}
function uniqueById(items){const map=new Map();items.forEach(item=>{if(item&&item.id!=null)map.set(String(item.id),item);});return [...map.values()];}
function card(title,lines,status=null){const node=document.createElement("article");node.className="cap-infra-card";node.innerHTML=`<h3>${title}</h3>${lines.map(line=>`<p>${line}</p>`).join("")}${status?`<span class="cap-infra-status ${status.ok?"":"offline"}">${status.label}</span>`:""}`;return node;}
function datacenterLabel(item){const region=item.region_name||item.region_id||"Region desconhecida";return `${item.name||item.id} (${item.id}) — ${region}`;}
function placementCard(item,datacenters){const current=String(item.datacenter_id||item.location_id||"");const node=card(item.name||item.id,[`Agent: <strong>${item.id||"—"}</strong>`,`Datacenter: <strong>${current||"—"}</strong>`],{ok:Boolean(item.placement_ready),label:item.placement_ready?"Placement ready":"Placement indisponível"});
 const form=document.createElement("form");form.className="cap-agent-location-form";
 const label=document.createElement("label");label.textContent="Datacenter do Agent";
 const select=document.createElement("select");select.required=true;select.setAttribute("aria-label",`Datacenter do Agent ${item.name||item.id}`);select.appendChild(new Option("Selecione um datacenter",""));datacenters.forEach(dc=>select.appendChild(new Option(datacenterLabel(dc),String(dc.id))));if([...select.options].some(option=>option.value===current))select.value=current;
 const region=document.createElement("small");region.className="cap-agent-location-region";
 const updateRegion=()=>{const selected=datacenters.find(dc=>String(dc.id)===select.value);region.textContent=selected?`Region derivada: ${selected.region_name||selected.region_id||"—"}`:"A Region será derivada do Datacenter selecionado.";};select.addEventListener("change",updateRegion);updateRegion();
 const actions=document.createElement("div");actions.className="cap-agent-location-actions";
 const button=document.createElement("button");button.type="submit";button.className="cap-btn cap-btn-secondary";button.textContent=current?"Alterar localização":"Vincular datacenter";
 const feedback=document.createElement("span");feedback.className="cap-agent-location-feedback";feedback.setAttribute("role","status");actions.append(button,feedback);label.appendChild(select);form.append(label,region,actions);
 form.addEventListener("submit",async event=>{event.preventDefault();showError();if(!select.value){feedback.textContent="Selecione um datacenter.";return;}button.disabled=true;feedback.textContent="Salvando…";try{await request("/agent/location",{method:"POST",body:{agent_id:String(item.id),datacenter_id:select.value,status:"active"}});feedback.textContent="Localização salva.";await load();}catch(error){feedback.textContent="";showError(error.message);}finally{button.disabled=false;}});
 node.appendChild(form);return node;}
function setText(id,value){const node=byId(id);if(node)node.textContent=String(value);}
function render(data){const regions=uniqueById(collect(data,"region"));const datacenters=uniqueById(collect(data,"datacenter"));const agents=uniqueById(collect(data,"agent"));const placementReady=agents.filter(agent=>Boolean(agent.placement_ready));setText("infra-region-count",regions.length);setText("infra-dc-count",datacenters.length);setText("infra-agent-count",agents.filter(agent=>agent.datacenter_id||agent.location_id).length);setText("infra-placement-count",placementReady.length);
 const r=byId("infra-regions");if(r){r.replaceChildren();regions.forEach(item=>r.appendChild(card(item.name||item.id,[`ID: <strong>${item.id}</strong>`,item.country_code?`País: <strong>${item.country_code}</strong>`:"País: —"])));if(!regions.length)r.appendChild(card("Nenhuma Region",["A topologia ainda não publicou Regions."]));}
 const d=byId("infra-datacenters");if(d){d.replaceChildren();datacenters.forEach(item=>d.appendChild(card(item.name||item.id,[`ID: <strong>${item.id}</strong>`,item.region_id?`Region: <strong>${item.region_id}</strong>`:"Region: —",item.city?`Cidade: <strong>${item.city}</strong>`:"Cidade: —"])));if(!datacenters.length)d.appendChild(card("Nenhum Datacenter",["A topologia ainda não publicou Datacenters."]));}
 const p=byId("infra-placement");if(p){p.replaceChildren();agents.forEach(item=>p.appendChild(placementCard(item,datacenters)));if(!agents.length)p.appendChild(card("Nenhum Agent",["Cadastre e localize Agents para habilitar Placement."]));}}
async function load(){showError();try{const data=await request("/infrastructure?active_only=true");if(data)render(data);}catch(error){showError(error.message);}}
async function init(){try{await loadSidebar();const user=await request("/whoami");if(!user)return;if(!["admin","controller"].includes(user.role))throw new Error("Você não possui permissão para administrar infraestrutura.");setText("infra-user-name",user.username||"—");setText("infra-user-role",user.role||"—");document.querySelectorAll(".admin-only").forEach(el=>el.style.display=user.role==="admin"?"":"none");byId("infra-refresh")?.addEventListener("click",load);await load();}catch(error){showError(error.message);}}
document.addEventListener("DOMContentLoaded",init);
