"use strict";

const API = "/api";

function byId(id){return document.getElementById(id);}
function authHeader(){const token=sessionStorage.getItem("dsm_auth");if(!token){window.location.replace("/login.html");throw new Error("authentication required");}return {Authorization:`Basic ${token}`,Accept:"application/json"};}
async function request(path){const response=await fetch(`${API}${path}`,{headers:authHeader()});if(response.status===401){sessionStorage.clear();window.location.replace("/login.html");return null;}const body=await response.json();if(!response.ok)throw new Error(body.error||body.message||`HTTP ${response.status}`);return body;}
function showError(message=""){const box=byId("infra-error");if(!box)return;box.hidden=!message;box.textContent=message;}
async function loadSidebar(){const target=byId("sidebar-component");if(!target)return;const response=await fetch("/components/sidebar-v3.html");if(response.ok)target.innerHTML=await response.text();const logout=byId("btn-logout");if(logout)logout.addEventListener("click",()=>{sessionStorage.clear();window.location.replace("/login.html");});const toggle=byId("infra-menu-toggle");if(toggle)toggle.addEventListener("click",()=>document.body.classList.toggle("cap-sidebar-open"));}
function collect(value,type,out=[]){if(Array.isArray(value)){value.forEach(item=>collect(item,type,out));return out;}if(!value||typeof value!=="object")return out;if(value.type===type)out.push(value);Object.values(value).forEach(child=>{if(child&&typeof child==="object")collect(child,type,out);});return out;}
function uniqueById(items){const map=new Map();items.forEach(item=>{if(item&&item.id!=null)map.set(String(item.id),item);});return [...map.values()];}
function card(title,lines,status=null){const node=document.createElement("article");node.className="cap-infra-card";node.innerHTML=`<h3>${title}</h3>${lines.map(line=>`<p>${line}</p>`).join("")}${status?`<span class="cap-infra-status ${status.ok?"":"offline"}">${status.label}</span>`:""}`;return node;}
function render(data){const regions=uniqueById(collect(data,"region"));const datacenters=uniqueById(collect(data,"datacenter"));const agents=uniqueById(collect(data,"agent"));const placementReady=agents.filter(agent=>Boolean(agent.placement_ready));byId("infra-region-count").textContent=regions.length;byId("infra-dc-count").textContent=datacenters.length;byId("infra-agent-count").textContent=agents.filter(agent=>agent.datacenter_id||agent.location_id).length;byId("infra-placement-count").textContent=placementReady.length;
 const r=byId("infra-regions");r.replaceChildren();regions.forEach(item=>r.appendChild(card(item.name||item.id,[`ID: <strong>${item.id}</strong>`,item.country_code?`País: <strong>${item.country_code}</strong>`:"País: —"])));if(!regions.length)r.appendChild(card("Nenhuma Region","A topologia ainda não publicou Regions.".split("|")));
 const d=byId("infra-datacenters");d.replaceChildren();datacenters.forEach(item=>d.appendChild(card(item.name||item.id,[`ID: <strong>${item.id}</strong>`,item.region_id?`Region: <strong>${item.region_id}</strong>`:"Region: —",item.city?`Cidade: <strong>${item.city}</strong>`:"Cidade: —"])));if(!datacenters.length)d.appendChild(card("Nenhum Datacenter",["A topologia ainda não publicou Datacenters."]));
 const p=byId("infra-placement");p.replaceChildren();agents.forEach(item=>p.appendChild(card(item.name||item.id,[`Agent: <strong>${item.id||"—"}</strong>`,`Datacenter: <strong>${item.datacenter_id||item.location_id||"—"}</strong>`],{ok:Boolean(item.placement_ready),label:item.placement_ready?"Placement ready":"Placement indisponível"})));if(!agents.length)p.appendChild(card("Nenhum Agent",["Cadastre e localize Agents para habilitar Placement."]));}
async function load(){showError();try{const data=await request("/infrastructure?active_only=true");if(data)render(data);}catch(error){showError(error.message);}}
async function init(){try{await loadSidebar();const user=await request("/whoami");if(!user)return;if(!["admin","controller"].includes(user.role))throw new Error("Você não possui permissão para administrar infraestrutura.");byId("infra-user-name").textContent=user.username||"—";byId("infra-user-role").textContent=user.role||"—";document.querySelectorAll(".admin-only").forEach(el=>el.style.display=user.role==="admin"?"":"none");byId("infra-refresh")?.addEventListener("click",load);await load();if(location.hash){requestAnimationFrame(()=>document.querySelector(location.hash)?.scrollIntoView({block:"start"}));}}catch(error){showError(error.message);}}
document.addEventListener("DOMContentLoaded",init);
