"use strict";
const OBS_API="/api";const byId=id=>document.getElementById(id);const view=()=>document.body.dataset.observabilityView||"overview";
const controllerHeaders=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
async function get(path){try{const r=await fetch(`${OBS_API}${path}`,{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){location.replace("/login.html");return null}return r.ok?await r.json():null}catch(e){console.warn("[Capivara Observability]",path,e);return null}}
async function post(path,payload){const r=await fetch(`${OBS_API}${path}`,{method:"POST",headers:{...controllerHeaders(),"Content-Type":"application/json"},credentials:"same-origin",cache:"no-store",body:JSON.stringify(payload||{})});if(r.status===401){location.replace("/login.html");return null}let data={};try{data=await r.json()}catch(_){data={}}if(!r.ok)throw new Error(data?.error||`Falha HTTP ${r.status}`);return data}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}function text(id,v,f="—"){const e=byId(id);if(e)e.textContent=v??f}function formatTime(v){if(!v)return"—";const d=typeof v==="number"?new Date(v*1000):new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}
function renderUser(u){const r=String(u?.role||"").toLowerCase();text("observability-user-name",u?.username||"Usuário");text("observability-user-role",r);text("current-user",u?.username||"Sessão ativa");document.querySelectorAll(".admin-only").forEach(e=>e.style.display=r==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(e=>e.style.display=["admin","controller","operator"].includes(r)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(e=>e.style.display=["admin","controller","client","customer"].includes(r)?"":"none")}
function renderTimeline(result){const rows=Array.isArray(result)?result:(result?.events||[]);text("observability-event-total",rows.length);const t=byId("observability-events");if(!t)return;t.innerHTML=rows.slice(0,100).map(e=>{const type=String(e?.type||e?.action||e?.event_type||"Evento").replaceAll("_"," ").toLowerCase(),msg=e?.message||e?.details||e?.data?.message||"";return`<article class="cap-event-item"><time>${escapeHtml(formatTime(e.occurred_at||e.timestamp||e.time||e.created_at||e.received_at))}</time><div><p>${escapeHtml(msg?`${type} · ${msg}`:type)}</p><small>${escapeHtml(e.category||e.source||e.producer||"Sistema")}</small></div></article>`}).join("")||'<div class="cap-empty-state">Nenhum evento recente.</div>'}
function alertScope(a){return[a.agent_id,a.instance_id].filter(Boolean).join(" · ")||a.scope||"Controller"}
function alertControls(a){const id=escapeHtml(a.id||"");if(!id)return"";const state=String(a.state||"OPEN").toUpperCase();const ruleId=String(a.rule_id||"").trim();const genericResolveAllowed=ruleId!=="agent.identity_collision";const viewAgent=a.agent_id?`<a href="agent-details.html?agent_id=${encodeURIComponent(a.agent_id)}">Ver Agent</a>`:"";const acknowledge=state==="OPEN"?`<button type="button" data-alert-action="acknowledge" data-alert-id="${id}">Reconhecer</button>`:"";const resolve=genericResolveAllowed&&["OPEN","ACKNOWLEDGED"].includes(state)?`<button type="button" class="danger" data-alert-action="resolve" data-alert-id="${id}">Resolver</button>`:"";const reopen=["RESOLVED","SUPPRESSED"].includes(state)?`<button type="button" data-alert-action="reopen" data-alert-id="${id}">Reabrir</button>`:"";return`<div class="cap-alert-controls">${viewAgent}<button type="button" data-alert-history="${id}">Ver histórico</button><button type="button" data-alert-action="note" data-alert-id="${id}">Adicionar nota</button>${acknowledge}${resolve}${reopen}</div>`}
function renderAlerts(result){const rows=Array.isArray(result)?result:(result?.alerts||[]);text("observability-alert-total",rows.filter(a=>["OPEN","ACKNOWLEDGED"].includes(String(a.state||"").toUpperCase())).length);const t=byId("observability-alerts");if(!t)return;t.innerHTML=rows.slice(0,100).map(a=>{const level=String(a.level||"warning").toLowerCase(),state=String(a.state||"OPEN").toUpperCase();return`<article class="cap-alert-item" data-level="${escapeHtml(level)}"><strong>${escapeHtml(level)} · ${escapeHtml(state)}</strong><div class="cap-alert-item-main"><p>${escapeHtml(a.message||a.rule_id||a.id||"Alerta")}</p><small>${escapeHtml(alertScope(a))}</small>${alertControls(a)}</div><time>${escapeHtml(formatTime(a.updated_at||a.opened_at))}</time></article>`}).join("")||'<div class="cap-empty-state">Nenhum alerta registrado.</div>'}
function historyMessage(row){return row?.message||row?.summary||row?.action||"Registro administrativo"}
function renderAlertHistory(result){const alert=result?.alert||{},events=Array.isArray(result?.history)?result.history:[],audit=Array.isArray(result?.audit)?result.audit:[];text("alert-history-title",`${alert.rule_id||alert.id||"Alerta"} · ${alert.state||"—"}`);const t=byId("alert-history-body");if(!t)return;const items=[];events.forEach(row=>items.push({kind:"event",time:row.created_at||row.occurred_at||row.timestamp||row.updated_at,action:row.action||"EVENT",message:historyMessage(row),meta:[row.old_state,row.new_state].filter(Boolean).join(" → ")}));audit.forEach(row=>{const note=row?.changes?.note?.after||"";items.push({kind:"audit",time:row.occurred_at,action:row.action||"AUDIT",message:note||row.summary||"Ação administrativa",meta:[row.actor_name||row.actor_id,row.actor_role].filter(Boolean).join(" · ")})});items.sort((a,b)=>new Date(b.time||0)-new Date(a.time||0));t.innerHTML=items.map(item=>`<article class="cap-alert-history-row"><strong>${escapeHtml(String(item.action).replaceAll("_"," "))}</strong><div>${escapeHtml(item.message)}</div><small>${escapeHtml(item.meta||"")} ${item.time?`· ${escapeHtml(formatTime(item.time))}`:""}</small></article>`).join("")||'<div class="cap-empty-state">Nenhum histórico disponível.</div>'}
async function showAlertHistory(alertId){const dialog=byId("alert-history-dialog"),body=byId("alert-history-body");if(body)body.innerHTML='<div class="cap-empty-state">Carregando...</div>';if(dialog&&!dialog.open)dialog.showModal();const result=await get(`/admin/alert?id=${encodeURIComponent(alertId)}`);if(result)renderAlertHistory(result);else if(body)body.innerHTML='<div class="cap-empty-state">Não foi possível carregar o histórico.</div>'}
async function handleAlertAction(button){const id=String(button?.dataset?.alertId||"").trim(),action=String(button?.dataset?.alertAction||"").trim();if(!id||!["acknowledge","note","resolve","reopen"].includes(action))return;let note="";if(action==="note")note=String(prompt("Adicione uma nota administrativa a este alerta:")||"").trim();if(action==="resolve")note=String(prompt("Descreva o que foi feito para resolver este alerta:")||"").trim();if(action==="reopen")note=String(prompt("Informe o motivo da reabertura deste alerta:")||"").trim();if(["note","resolve","reopen"].includes(action)&&!note)return;const original=button.textContent;button.disabled=true;button.textContent=action==="resolve"?"Resolvendo...":action==="reopen"?"Reabrindo...":action==="note"?"Salvando...":"Reconhecendo...";try{await post("/admin/alert/action",{id,action,note});await refresh()}catch(error){alert(`Não foi possível alterar o alerta:\n${error.message}`);button.disabled=false;button.textContent=original}}
function renderMetrics(result){const rows=Array.isArray(result?.metrics)?result.metrics:[];text("observability-metric-total",result?.count??rows.length);const t=byId("observability-metrics");if(!t)return;t.innerHTML=rows.slice(0,100).map(m=>{const name=m?.metric_name||m?.name||m?.key||m?.type||"Métrica",value=m?.value??m?.metric_value??m?.latest??m?.avg??m?.average??m?.status??m?.state??"Disponível",scope=[m?.agent_id,m?.instance_id].filter(Boolean).join(" · ")||m?.scope||"Control Plane",unit=m?.unit?` ${m.unit}`:"";return`<article class="cap-metric-card"><span>${escapeHtml(name)}</span><strong>${escapeHtml(value)}${escapeHtml(unit)}</strong><small>${escapeHtml(scope)}</small></article>`}).join("")||'<div class="cap-empty-state">Nenhuma métrica publicada.</div>'}
function scalarEntries(v,p="",d=0){if(!v||typeof v!=="object"||d>2)return[];const out=[];for(const[k,c]of Object.entries(v)){const label=p?`${p} · ${k}`:k;if(c===null||["string","number","boolean"].includes(typeof c))out.push([label,c]);else if(!Array.isArray(c))out.push(...scalarEntries(c,label,d+1))}return out}
function renderDoctor(result){const t=byId("observability-doctor"),status=String(result?.status||result?.health||result?.state||"operacional");text("observability-doctor-state",status);if(!t)return;const rows=scalarEntries(result).slice(0,60);t.innerHTML=rows.map(([l,v])=>`<article class="cap-doctor-card" data-state="${escapeHtml(String(v||"").toLowerCase())}"><span>${escapeHtml(l.replaceAll("_"," "))}</span><strong>${escapeHtml(v)}</strong></article>`).join("")||'<div class="cap-empty-state">Diagnóstico concluído sem detalhes adicionais.</div>'}
function renderHealth(result){const d=result?.data||result||{},s=String(d.status||"online").toLowerCase(),failed=["failed","critical","offline","error"].includes(s);text("observability-controller-status",failed?"Controller com falha":"Controller Online");document.querySelector(".cap-controller-state")?.classList.toggle("cap-controller-failed",failed)}
function logSignature(logs,message){return JSON.stringify({logs,message:message||""})}
function setLogsRefreshState(state){const button=byId("btn-refresh-logs");if(!button)return;if(button._capResetTimer){clearTimeout(button._capResetTimer);button._capResetTimer=null}const loading=state==="loading";button.disabled=loading;button.classList.toggle("is-loading",loading);button.setAttribute("aria-busy",loading?"true":"false");if(state==="loading"){button.textContent="Atualizando…";return}if(state==="success"){button.textContent="Atualizado ✓";button._capResetTimer=setTimeout(()=>{button.textContent="Atualizar logs"},1200);return}if(state==="error"){button.textContent="Falha ao atualizar";button._capResetTimer=setTimeout(()=>{button.textContent="Atualizar logs"},1800);return}button.textContent="Atualizar logs"}
let logsRequest=null;
async function performLogLoad(){const t=byId("logs");if(!t)return false;const response=await get(`/log-viewer?${new URLSearchParams({source:"controller",limit:"500"})}`);if(response===null)return false;const data=response?.data||response||{},logs=Array.isArray(data.logs)?data.logs:[];text("logs-context","Controller");const message=data.message||"Nenhum log do Controller disponível.",signature=logSignature(logs,message);if(t.dataset.logSignature===signature)return true;const fragment=document.createDocumentFragment();if(!logs.length){const e=document.createElement("div");e.className="cap-empty-state";e.textContent=message;fragment.appendChild(e)}else{logs.forEach(line=>{const e=document.createElement("div");e.className="cap-log-line";e.textContent=line;fragment.appendChild(e)})}t.replaceChildren(fragment);t.dataset.logSignature=signature;return true}
async function loadLogs(options={}){const interactive=Boolean(options.interactive);if(interactive)setLogsRefreshState("loading");if(!logsRequest)logsRequest=performLogLoad().finally(()=>{logsRequest=null});let success=false;try{success=Boolean(await logsRequest);return success}finally{if(interactive)setLogsRefreshState(success?"success":"error")}}
async function refresh(){const v=view(),userPromise=get("/whoami"),healthPromise=get("/health");let timeline=null,alerts=null,metrics=null,doctor=null;if(v==="overview"||v==="events")timeline=await get("/events?limit=100");if(v==="overview")alerts=await get("/admin/alerts?active=true&limit=100");if(v==="alerts")alerts=await get("/admin/alerts?active=false&limit=200");if(v==="overview"||v==="monitoring")metrics=await get("/observability?mode=latest&limit=100");if(v==="overview"||v==="diagnostics")doctor=await get("/infrastructure/doctor");const[user,health]=await Promise.all([userPromise,healthPromise]);if(user)renderUser(user);if(timeline)renderTimeline(timeline);if(alerts)renderAlerts(alerts);if(metrics)renderMetrics(metrics);if(doctor)renderDoctor(doctor);else if(v==="diagnostics"){text("observability-doctor-state","Indisponível");const t=byId("observability-doctor");if(t)t.innerHTML='<div class="cap-empty-state">Diagnóstico indisponível para esta sessão.</div>'}renderHealth(health);if(v==="logs")await loadLogs()}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"})}finally{location.replace("/login.html")}}
async function loadSidebar(){const t=byId("sidebar-component");if(!t)return;const r=await fetch("/components/sidebar-v3.html",{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){location.replace("/login.html");return}if(r.ok)t.innerHTML=await r.text();const button=byId("btn-logout");if(button)button.onclick=logout;const current=location.pathname.split("/").pop()||"observability.html";document.querySelectorAll(".cap-sidebar-v3 a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")?.split("#")[0]===current))}
document.addEventListener("click",event=>{const action=event.target.closest("[data-alert-action]");if(action){event.preventDefault();handleAlertAction(action);return}const history=event.target.closest("[data-alert-history]");if(history){event.preventDefault();showAlertHistory(history.dataset.alertHistory)}});
document.addEventListener("DOMContentLoaded",async()=>{await loadSidebar();byId("observability-menu-toggle")?.addEventListener("click",()=>{if(innerWidth<=760)document.body.classList.toggle("sidebar-open");else document.body.classList.toggle("cap-sidebar-collapsed")});byId("observability-refresh")?.addEventListener("click",refresh);byId("btn-refresh-logs")?.addEventListener("click",()=>loadLogs({interactive:true}));byId("alert-history-close")?.addEventListener("click",()=>byId("alert-history-dialog")?.close());await refresh();setInterval(refresh,30000)});