"use strict";
const OBS_API="/api";const byId=id=>document.getElementById(id);const view=()=>document.body.dataset.observabilityView||"overview";
const controllerHeaders=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
async function get(path){try{const r=await fetch(`${OBS_API}${path}`,{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){location.replace("/login.html");return null}return r.ok?await r.json():null}catch(e){console.warn("[Capivara Observability]",path,e);return null}}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}function text(id,v,f="—"){const e=byId(id);if(e)e.textContent=v??f}function formatTime(v){if(!v)return"—";const d=typeof v==="number"?new Date(v*1000):new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}
function renderUser(u){const r=String(u?.role||"").toLowerCase();text("observability-user-name",u?.username||"Usuário");text("observability-user-role",r);text("current-user",u?.username||"Sessão ativa");document.querySelectorAll(".admin-only").forEach(e=>e.style.display=r==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(e=>e.style.display=["admin","controller","operator"].includes(r)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(e=>e.style.display=["admin","controller","client","customer"].includes(r)?"":"none")}
function renderTimeline(result){const rows=Array.isArray(result)?result:(result?.events||[]);text("observability-event-total",rows.length);const t=byId("observability-events");if(!t)return;t.innerHTML=rows.slice(0,100).map(e=>{const type=String(e?.type||e?.action||e?.event_type||"Evento").replaceAll("_"," ").toLowerCase(),msg=e?.message||e?.details||e?.data?.message||"";return`<article class="cap-event-item"><time>${escapeHtml(formatTime(e.occurred_at||e.timestamp||e.time||e.created_at||e.received_at))}</time><div><p>${escapeHtml(msg?`${type} · ${msg}`:type)}</p><small>${escapeHtml(e.category||e.source||e.producer||"Sistema")}</small></div></article>`}).join("")||'<div class="cap-empty-state">Nenhum evento recente.</div>'}
function renderAlerts(result){const rows=Array.isArray(result)?result:(result?.alerts||[]);text("observability-alert-total",rows.length);const t=byId("observability-alerts");if(!t)return;t.innerHTML=rows.slice(0,100).map(a=>{const level=String(a.level||"warning").toLowerCase(),state=String(a.state||"OPEN").toUpperCase(),scope=[a.agent_id,a.instance_id].filter(Boolean).join(" · ")||a.scope||"Controller";return`<article class="cap-alert-item" data-level="${escapeHtml(level)}"><strong>${escapeHtml(level)} · ${escapeHtml(state)}</strong><p>${escapeHtml(a.message||a.rule_id||a.id||"Alerta")}</p><small>${escapeHtml(scope)}</small><time>${escapeHtml(formatTime(a.updated_at||a.opened_at))}</time></article>`}).join("")||'<div class="cap-empty-state">Nenhum alerta ativo.</div>'}
function renderMetrics(result){const rows=Array.isArray(result?.metrics)?result.metrics:[];text("observability-metric-total",result?.count??rows.length);const t=byId("observability-metrics");if(!t)return;t.innerHTML=rows.slice(0,100).map(m=>{const name=m?.metric_name||m?.name||m?.key||m?.type||"Métrica",value=m?.value??m?.metric_value??m?.latest??m?.avg??m?.average??m?.status??m?.state??"Disponível",scope=[m?.agent_id,m?.instance_id].filter(Boolean).join(" · ")||m?.scope||"Control Plane",unit=m?.unit?` ${m.unit}`:"";return`<article class="cap-metric-card"><span>${escapeHtml(name)}</span><strong>${escapeHtml(value)}${escapeHtml(unit)}</strong><small>${escapeHtml(scope)}</small></article>`}).join("")||'<div class="cap-empty-state">Nenhuma métrica publicada.</div>'}
function scalarEntries(v,p="",d=0){if(!v||typeof v!=="object"||d>2)return[];const out=[];for(const[k,c]of Object.entries(v)){const label=p?`${p} · ${k}`:k;if(c===null||["string","number","boolean"].includes(typeof c))out.push([label,c]);else if(!Array.isArray(c))out.push(...scalarEntries(c,label,d+1))}return out}
function renderDoctor(result){const t=byId("observability-doctor"),status=String(result?.status||result?.health||result?.state||"operacional");text("observability-doctor-state",status);if(!t)return;const rows=scalarEntries(result).slice(0,60);t.innerHTML=rows.map(([l,v])=>`<article class="cap-doctor-card" data-state="${escapeHtml(String(v||"").toLowerCase())}"><span>${escapeHtml(l.replaceAll("_"," "))}</span><strong>${escapeHtml(v)}</strong></article>`).join("")||'<div class="cap-empty-state">Diagnóstico concluído sem detalhes adicionais.</div>'}
function renderHealth(result){const d=result?.data||result||{},s=String(d.status||"online").toLowerCase(),failed=["failed","critical","offline","error"].includes(s);text("observability-controller-status",failed?"Controller com falha":"Controller Online");document.querySelector(".cap-controller-state")?.classList.toggle("cap-controller-failed",failed)}
function logSignature(logs,message){return JSON.stringify({logs,message:message||""})}
async function loadLogs(){const t=byId("logs");if(!t)return;const response=await get(`/log-viewer?${new URLSearchParams({source:"controller",limit:"500"})}`),data=response?.data||response||{},logs=Array.isArray(data.logs)?data.logs:[];text("logs-context","Controller");const message=data.message||"Nenhum log do Controller disponível.",signature=logSignature(logs,message);if(t.dataset.logSignature===signature)return;const fragment=document.createDocumentFragment();if(!logs.length){const e=document.createElement("div");e.className="cap-empty-state";e.textContent=message;fragment.appendChild(e)}else{logs.forEach(line=>{const e=document.createElement("div");e.className="cap-log-line";e.textContent=line;fragment.appendChild(e)})}t.replaceChildren(fragment);t.dataset.logSignature=signature}
async function refresh(){const v=view(),userPromise=get("/whoami"),healthPromise=get("/health");let timeline=null,alerts=null,metrics=null,doctor=null;if(v==="overview"||v==="events")timeline=await get("/events?limit=100");if(v==="overview"||v==="alerts")alerts=await get("/admin/alerts?active=true&limit=100");if(v==="overview"||v==="monitoring")metrics=await get("/observability?mode=latest&limit=100");if(v==="overview"||v==="diagnostics")doctor=await get("/infrastructure/doctor");const[user,health]=await Promise.all([userPromise,healthPromise]);if(user)renderUser(user);if(timeline)renderTimeline(timeline);if(alerts)renderAlerts(alerts);if(metrics)renderMetrics(metrics);if(doctor)renderDoctor(doctor);else if(v==="diagnostics"){text("observability-doctor-state","Indisponível");const t=byId("observability-doctor");if(t)t.innerHTML='<div class="cap-empty-state">Diagnóstico indisponível para esta sessão.</div>'}renderHealth(health);if(v==="logs")await loadLogs()}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"})}finally{location.replace("/login.html")}}
async function loadSidebar(){const t=byId("sidebar-component");if(!t)return;const r=await fetch("/components/sidebar-v3.html",{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){location.replace("/login.html");return}if(r.ok)t.innerHTML=await r.text();const button=byId("btn-logout");if(button)button.onclick=logout;const current=location.pathname.split("/").pop()||"observability.html";document.querySelectorAll(".cap-sidebar-v3 a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")?.split("#")[0]===current))}
document.addEventListener("DOMContentLoaded",async()=>{await loadSidebar();byId("observability-menu-toggle")?.addEventListener("click",()=>{if(innerWidth<=760)document.body.classList.toggle("sidebar-open");else document.body.classList.toggle("cap-sidebar-collapsed")});byId("observability-refresh")?.addEventListener("click",refresh);byId("btn-refresh-logs")?.addEventListener("click",loadLogs);await refresh();setInterval(refresh,30000)});
