(function(){"use strict";
const $=id=>document.getElementById(id);const headers=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
async function request(path){const r=await fetch(path,{headers:headers(),credentials:"same-origin",cache:"no-store"});if(r.status===401){location.replace("/login.html");throw new Error("Sessão expirada")}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function setText(id,value){const node=$(id);if(node)node.textContent=value??"—"}
function applyRBAC(role){document.querySelectorAll(".admin-only").forEach(el=>el.style.display=role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(el=>el.style.display=["admin","controller"].includes(role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(el=>el.style.display=["admin","controller","operator"].includes(role)?"":"none")}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:headers(),credentials:"same-origin",cache:"no-store"})}finally{location.replace("/login.html")}}
async function loadSidebar(){const host=$("sidebar-component");if(!host)return;const r=await fetch("/components/sidebar-v3.html",{headers:headers(),credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error(`sidebar HTTP ${r.status}`);host.innerHTML=await r.text();host.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="operations.html"));$("btn-logout")?.addEventListener("click",logout)}
function bindMenu(){const btn=$("operations-menu-toggle");if(!btn)return;btn.addEventListener("click",()=>document.body.classList.toggle("cap-sidebar-collapsed"))}
async function loadIdentity(){const who=await request("/api/whoami");setText("operations-user-name",who.username);setText("operations-user-role",who.role);const current=$("current-user");if(current)current.textContent=`${who.username} (${who.role})`;applyRBAC(who.role)}
async function loadBackups(){const state=$("backup-state");try{const response=await request("/api/backups");const data=response.data??response;const total=data.total??0;const last=data.last_date??data.last??"—";setText("operations-backup-total",total);setText("operations-backup-last",last);setText("backup-total",total);setText("backup-last",last);if(state)state.textContent="As ações específicas de criação, restauração e exclusão permanecem vinculadas à instância correspondente."}catch(error){setText("operations-backup-total","—");setText("operations-backup-last","—");setText("backup-total","—");setText("backup-last","—");if(state)state.textContent=`Resumo de backups indisponível no momento: ${error.message}`}}
async function refresh(){const btn=$("operations-refresh");if(btn)btn.disabled=true;try{await loadBackups()}finally{if(btn)btn.disabled=false}}
async function init(){await loadSidebar();bindMenu();await loadIdentity();$("operations-refresh")?.addEventListener("click",refresh);await refresh()}
document.addEventListener("DOMContentLoaded",()=>init().catch(error=>{console.error(error);if(String(error?.message||"").includes("Sessão"))location.replace("/login.html")}));
})();
