(function(){
"use strict";
const $=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";
function esc(value){return String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]))}
function stamp(value){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?esc(value):d.toLocaleString()}
async function request(path,options={}){const headers={Authorization:`Basic ${auth()}`,Accept:"application/json",...(options.headers||{})};if(options.body)headers["Content-Type"]="application/json";const r=await fetch(path,{...options,headers,cache:"no-store",credentials:"same-origin"});if(r.status===401){sessionStorage.removeItem("dsm_auth");location.replace("/login.html");throw new Error("Sessão encerrada")};const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.message||data.error||`HTTP ${r.status}`);return data}
async function sidebar(){const root=$("sidebar-component");if(!root)return;const r=await fetch("/components/sidebar.html",{cache:"no-store"});if(r.ok)root.innerHTML=await r.text();const logout=$("btn-logout");if(logout)logout.onclick=()=>{sessionStorage.clear();location.replace("/login.html")}}
function badge(value){const v=String(value||"info").toLowerCase();return `<span class="ops-badge ${esc(v)}">${esc(v.toUpperCase())}</span>`}
function empty(root,text){root.innerHTML=`<p class="operations-empty">${esc(text)}</p>`}
async function loadSummary(){const d=await request("/api/operations?view=summary");$("ops-incidents").textContent=d.active_incidents??0;$("ops-critical-incidents").textContent=d.critical_incidents??0;$("ops-alerts").textContent=d.active_alerts??0;$("ops-critical-alerts").textContent=d.critical_alerts??0;$("ops-schedule-failures").textContent=d.failed_schedule_runs??0}
function incidentRow(item){return `<article class="ops-row incident-row" data-incident="${esc(item.incident_id)}"><div>${badge(item.severity)} <strong>${esc(item.title)}</strong><p>${esc(item.source||"—")} · ${esc(item.agent_id||"sem Agent")} · ${esc(item.instance_id||"sem instância")}</p></div><div><strong>${esc(String(item.status||"").toUpperCase())}</strong><p>${stamp(item.started_at)} → ${item.resolved_at?stamp(item.resolved_at):"em andamento"}</p><button type="button" data-open-incident="${esc(item.incident_id)}">Ver incidente</button></div></article>`}
async function loadIncidents(){const d=await request("/api/operations?view=incidents&limit=500");const root=$("incident-list");if(!(d.incidents||[]).length){empty(root,"Nenhum incidente registrado.");return}root.innerHTML=d.incidents.map(incidentRow).join("");root.querySelectorAll("[data-open-incident]").forEach(btn=>btn.onclick=()=>openIncident(btn.dataset.openIncident))}
async function openIncident(id){const d=await request(`/api/operations?view=incident&incident_id=${encodeURIComponent(id)}`);const i=d.incident,root=$("incident-detail");root.hidden=false;root.innerHTML=`<div class="card-title"><div><h3>${esc(i.title)}</h3><p>Incident ID: ${esc(i.incident_id)} · correlation_id: ${esc(i.correlation_id||"—")}</p></div><button id="incident-close" type="button">Fechar</button></div><div class="incident-timeline">${(i.events||[]).map(e=>`<div class="timeline-entry">${badge(e.severity)}<strong>${esc(e.event_type)}</strong><span>${stamp(e.occurred_at||e.received_at)}</span><p>${esc((e.data||{}).message||(e.data||{}).error||e.source||"")}</p></div>`).join("")}</div>${(i.alerts||[]).length?`<h4>Alertas relacionados</h4>${i.alerts.map(a=>`<p>${badge(a.level)} ${esc(a.message)} · ${esc(a.state)}</p>`).join("")}:""}`;$("incident-close").onclick=()=>{root.hidden=true;root.innerHTML=""};root.scrollIntoView({behavior:"smooth",block:"start"})}
async function alertAction(alertId,operation){await request("/api/operations",{method:"POST",body:JSON.stringify({operation,alert_id:alertId})});await Promise.all([loadSummary(),loadAlerts(),loadIncidents()])}
async function loadAlerts(){const active=$("alerts-active-only").checked?"1":"0",d=await request(`/api/operations?view=alerts&active=${active}&limit=500`),root=$("alert-list");if(!(d.alerts||[]).length){empty(root,"Nenhum alerta encontrado.");return}root.innerHTML=d.alerts.map(a=>`<article class="ops-row"><div>${badge(a.level)} <strong>${esc(a.message||a.rule_id||a.id)}</strong><p>${esc(a.scope||"—")} · ${esc(a.agent_id||"sem Agent")} · ${esc(a.instance_id||"sem instância")}</p></div><div><strong>${esc(a.state)}</strong><p>${stamp(a.opened_at)}</p>${a.state==="OPEN"?`<button data-ack="${esc(a.id)}">Reconhecer</button>`:""}${["OPEN","ACKNOWLEDGED"].includes(a.state)?`<button data-resolve="${esc(a.id)}">Resolver</button>`:""}</div></article>`).join("");root.querySelectorAll("[data-ack]").forEach(b=>b.onclick=()=>alertAction(b.dataset.ack,"acknowledge_alert"));root.querySelectorAll("[data-resolve]").forEach(b=>b.onclick=()=>alertAction(b.dataset.resolve,"resolve_alert"))}
async function loadEvents(){const p=new URLSearchParams({view:"events",limit:"500"});const pairs=[["type","event-type-filter"],["agent_id","event-agent-filter"],["instance_id","event-instance-filter"],["severity","event-severity-filter"]];pairs.forEach(([key,id])=>{const v=$(id).value.trim();if(v)p.set(key,v)});const d=await request(`/api/operations?${p}`),root=$("event-list");if(!(d.events||[]).length){empty(root,"Nenhum evento encontrado.");return}root.innerHTML=d.events.map(e=>`<article class="ops-row"><div>${badge(e.severity)} <strong>${esc(e.event_type)}</strong><p>${esc(e.source||"—")} · ${esc(e.agent_id||"sem Agent")} · ${esc(e.instance_id||"sem instância")}</p></div><div><p>${stamp(e.occurred_at||e.received_at)}</p><code>${esc(e.correlation_id||e.event_id||"")}</code></div></article>`).join("")}
async function loadSchedules(){const d=await request("/api/operations?view=schedules&limit=300"),rules=$("schedule-rules"),runs=$("schedule-runs");if(!(d.rules||[]).length)empty(rules,"Nenhuma regra cadastrada.");else rules.innerHTML=d.rules.map(r=>`<article class="ops-row"><div><strong>${esc(r.name||r.rule_id)}</strong><p>${esc(r.rule_id)} · revisão ${esc(r.revision)}</p></div><div>${r.enabled?badge("info"):badge("warning")}<strong>${r.enabled?"ATIVO":"DESATIVADO"}</strong></div></article>`).join("");if(!(d.runs||[]).length)empty(runs,"Nenhuma execução registrada.");else runs.innerHTML=d.runs.map(r=>`<article class="ops-row"><div><strong>${esc(r.rule_id||r.trigger_type||"manual")}</strong><p>${esc(r.run_id)} · ${esc(r.trigger_type||"")}</p></div><div>${badge(String(r.status||"info").toLowerCase()==="failed"?"critical":"info")}<strong>${esc(r.status)}</strong><p>${stamp(r.started_at||r.created_at)} → ${stamp(r.completed_at)}</p></div></article>`).join("")}
async function loadLogs(){const d=await request("/api/operations?view=logs&limit=500"),root=$("log-list");if(!(d.logs||[]).length){empty(root,"Nenhum registro operacional encontrado.");return}root.innerHTML=d.logs.map(l=>`<div class="log-entry"><span>${stamp(l.timestamp)}</span>${badge(l.level)}<code>${esc(l.source||"system")}</code><strong>${esc(l.event_type)}</strong><p>${esc(l.message||"")}</p><small>${esc(l.correlation_id||"")}</small></div>`).join("")}
async function loadBackups(){const health=$("controller-backup-health"),jobs=$("controller-backup-jobs");try{const [h,j]=await Promise.all([request("/api/backups?kind=health"),request("/api/backups?kind=jobs")]);health.innerHTML=`<article class="ops-row"><div><strong>Saúde do backup</strong><p>${esc(JSON.stringify(h))}</p></div></article>`;const list=j.jobs||j.items||j.backups||[];if(!Array.isArray(list)||!list.length)empty(jobs,"Nenhum job de backup registrado.");else jobs.innerHTML=list.slice(0,50).map(x=>`<article class="ops-row"><div><strong>${esc(x.action||x.kind||x.job_id||"backup")}</strong><p>${esc(x.instance_id||x.agent_id||"Controller")}</p></div><div><strong>${esc(x.status||"—")}</strong><p>${stamp(x.created_at||x.started_at)}</p></div></article>`).join("")}catch(e){health.textContent=`Backup: ${e.message}`;empty(jobs,"Não foi possível consultar jobs de backup.")}}
async function loadAll(){const box=$("operations-error");box.hidden=true;try{await Promise.all([loadSummary(),loadIncidents(),loadAlerts(),loadEvents(),loadSchedules(),loadLogs(),loadBackups()])}catch(e){box.hidden=false;box.textContent=e.message||String(e)}}
async function init(){if(!auth()){location.replace("/login.html");return}await sidebar();$("operations-refresh").onclick=loadAll;$("alerts-active-only").onchange=loadAlerts;$("event-filter-apply").onclick=loadEvents;await loadAll()}
document.addEventListener("DOMContentLoaded",init);
})();
