(function(){"use strict";
const $=id=>document.getElementById(id);const headers=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
async function request(path){const r=await fetch(path,{headers:headers(),credentials:"same-origin",cache:"no-store"});if(r.status===401){location.replace("/login.html");throw new Error("Sessão expirada")}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function setText(id,value){const node=$(id);if(node)node.textContent=value??"—"}
function applyRBAC(role){document.querySelectorAll(".admin-only").forEach(el=>el.style.display=role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(el=>el.style.display=["admin","controller"].includes(role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(el=>el.style.display=["admin","controller","client","customer"].includes(role)?"":"none")}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:headers(),credentials:"same-origin",cache:"no-store"})}finally{location.replace("/login.html")}}
async function loadSidebar(){const host=$("sidebar-component");if(!host)return;const r=await fetch("/components/sidebar.html",{credentials:"same-origin",cache:"no-store"});host.innerHTML=await r.text();host.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="operations.html"));$("btn-logout")?.addEventListener("click",logout)}
function bindMenu(){const btn=$("operations-menu-toggle");if(!btn)return;btn.addEventListener("click",()=>document.body.classList.toggle("cap-sidebar-collapsed"))}
async function loadIdentity(){const who=await request("/api/whoami");setText("operations-user-name",who.username);setText("operations-user-role",who.role);const current=$("current-user");if(current)current.textContent=`${who.username} (${who.role})`;applyRBAC(who.role)}
async function loadBackups(){const response=await request("/api/backups");const data=response.data??response;const total=data.total??0;const last=data.last_date??data.last??"—";setText("operations-backup-total",total);setText("operations-backup-last",last);setText("backup-total",total);setText("backup-last",last)}
async function loadScheduler(){const response=await request("/api/scheduler");const data=response.data??response;const jobs=Array.isArray(data.jobs)?data.jobs:[];setText("operations-scheduler-total",jobs.length);const root=$("scheduler-list");root.replaceChildren();if(!jobs.length){const empty=document.createElement("div");empty.className="cap-empty-state";empty.textContent="Nenhum job agendado.";root.append(empty);return}for(const job of jobs){const row=document.createElement("div");row.className="cap-job-item";const name=document.createElement("div");name.className="cap-job-name";name.textContent=job.name||"Job";const schedule=document.createElement("div");schedule.className="cap-job-schedule";schedule.textContent=job.schedule||"—";row.append(name,schedule);root.append(row)}}
async function refresh(){const btn=$("operations-refresh");if(btn)btn.disabled=true;try{await Promise.all([loadBackups(),loadScheduler()])}catch(error){const root=$("scheduler-list");if(root){root.replaceChildren();const div=document.createElement("div");div.className="cap-empty-state";div.textContent=`Não foi possível carregar as operações: ${error.message}`;root.append(div)}}finally{if(btn)btn.disabled=false}}
async function init(){await loadSidebar();bindMenu();await loadIdentity();$("operations-refresh")?.addEventListener("click",refresh);await refresh()}
document.addEventListener("DOMContentLoaded",()=>init().catch(error=>{console.error(error);if(String(error?.message||"").includes("Sessão"))location.replace("/login.html")}));
})();