(function(){"use strict";
const API="/api";const state={instances:[],filter:"all",query:""};
const el=id=>document.getElementById(id);const auth=()=>sessionStorage.getItem("dsm_auth")||"";
async function request(path){const r=await fetch(path,{headers:{Authorization:"Basic "+auth(),Accept:"application/json"}});if(r.status===401){sessionStorage.clear();location.replace("login.html");throw new Error("Sessão expirada");}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p;}
async function loadSidebar(){const host=el("sidebar-component");if(!host)return;const r=await fetch("components/sidebar.html");host.innerHTML=await r.text();host.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="servers-v2.html"));const out=el("btn-logout");if(out)out.onclick=()=>{sessionStorage.clear();location.replace("login.html")};try{const who=await request("/api/whoami");const user=el("current-user");if(user)user.textContent=`${who.username} (${who.role})`;document.querySelectorAll(".admin-only").forEach(x=>x.style.display=who.role==="admin"?"":"none");document.querySelectorAll(".agent-manager-only").forEach(x=>x.style.display=["admin","controller"].includes(who.role)?"":"none");}catch(_){}
}
function identity(item){return{server:item.server||item.node||item.node_id||"",game:item.game||"unknown",instance:item.instance||item.id||"unknown"}}
function gameIcon(game){const g=String(game).toLowerCase();if(g.includes("minecraft"))return"🧊";if(g.includes("dayz"))return"◈";if(g.includes("rust"))return"⬢";if(g.includes("arma"))return"◆";return"🎮"}
function normalizeStatus(summary){const raw=String(summary?.server_state?.status?.state||summary?.status?.state||summary?.state||summary?.status||"unknown").toLowerCase();if(["online","running","started","active"].includes(raw))return"online";if(["starting","updating","installing","warning","degraded"].includes(raw))return"attention";return"offline"}
function number(v,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function normalize(resource,summary,agents){const id=identity(resource);const meta=summary?.instance_metadata||{};const metrics=summary?.metrics||{};const serverState=summary?.server_state||{};const status=normalizeStatus(summary);const players=number(serverState?.players??metrics?.players??summary?.players,0);const slots=number(serverState?.max_players??serverState?.slots??summary?.max_players,0);const ramMb=number(metrics?.instance?.memory_mb??metrics?.memory_mb??metrics?.ram_mb,0);const cpu=number(metrics?.instance?.cpu_pct??metrics?.cpu_pct??metrics?.cpu?.pct,0);const agentId=meta.agent_id||meta.agent||id.server;const agent=agents.find(a=>[a.id,a.agent_id,a.node_id,a.name].filter(Boolean).map(String).includes(String(agentId)));const location=agent?.location_name||agent?.location||agent?.datacenter_name||agent?.datacenter||meta.datacenter||"-";return{...id,status,players,slots,ramMb,cpu,display:meta.display_name||id.instance,agent:agent?.name||agent?.id||agent?.agent_id||agentId||"-",location,health:String(summary?.health?.status||summary?.health||"-")}}
async function enrich(resources,agents){const result=new Array(resources.length);let cursor=0;async function worker(){while(cursor<resources.length){const i=cursor++;const r=resources[i];const id=identity(r);let summary=null;if(i<48&&id.server&&id.game&&id.instance){try{const qs=new URLSearchParams(id);summary=await request(`/api/runtime?${qs}`)}catch(_){} }result[i]=normalize(r,summary,agents)}}await Promise.all(Array.from({length:Math.min(6,resources.length||1)},worker));return result}
function fmtRam(mb){if(!mb)return"-";return mb>=1024?`${(mb/1024).toFixed(2)} GB`:`${Math.round(mb)} MB`}
function card(instance){const a=document.createElement("article");a.className="cap-instance-card";a.dataset.state=instance.status;const statusLabel=instance.status==="online"?"Online":instance.status==="attention"?"Atenção":"Offline";const playerText=instance.slots?`${instance.players} / ${instance.slots}`:String(instance.players);const ramPct=Math.max(0,Math.min(100,instance.ramMb?Math.min(100,(instance.ramMb/16384)*100):0));const qs=new URLSearchParams({server:instance.server,game:instance.game,instance:instance.instance});a.innerHTML=`<div class="cap-instance-head"><div class="cap-instance-title"><span class="cap-game-mark">${gameIcon(instance.game)}</span><div><strong>${escapeHtml(instance.display)}</strong><small>${escapeHtml(instance.game)} · ${escapeHtml(instance.agent)}</small></div></div><span class="cap-state ${instance.status}">${statusLabel}</span></div><div class="cap-instance-meta"><div><span>Jogadores</span><strong>${playerText}</strong></div><div><span>CPU</span><strong>${instance.cpu?instance.cpu.toFixed(1)+"%":"-"}</strong></div><div><span>Agent</span><strong>${escapeHtml(instance.agent)}</strong></div><div><span>Localização</span><strong>${escapeHtml(instance.location)}</strong></div></div><div class="cap-meter"><div class="cap-meter-row"><span>RAM</span><strong>${fmtRam(instance.ramMb)}</strong></div><div class="cap-meter-track"><div class="cap-meter-fill" style="width:${ramPct}%"></div></div></div><div class="cap-instance-actions"><a class="cap-action-primary" href="console.html?${qs}">Console</a><a class="cap-action-secondary" href="index.html#catalog-v2-card">Gerenciar</a></div>`;return a}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){const q=state.query.trim().toLowerCase();const visible=state.instances.filter(i=>{if(state.filter!=="all"&&i.status!==state.filter)return false;if(!q)return true;return[i.display,i.game,i.instance,i.agent,i.server,i.location].some(v=>String(v).toLowerCase().includes(q))});const grid=el("instance-grid");grid.replaceChildren(...visible.map(card));el("instance-empty").hidden=visible.length>0;el("instance-summary-text").textContent=`${visible.length} de ${state.instances.length} instância(s) exibida(s).`;el("fleet-total").textContent=state.instances.length;el("fleet-online").textContent=state.instances.filter(i=>i.status==="online").length;el("fleet-offline").textContent=state.instances.filter(i=>i.status==="offline").length;el("fleet-agents").textContent=new Set(state.instances.map(i=>i.agent).filter(v=>v&&v!=="-")).size}
async function load(){const btn=el("refresh-instances");if(btn)btn.disabled=true;el("instance-summary-text").textContent="Sincronizando Runtime...";try{const [r,a]=await Promise.all([request("/api/runtime/list"),request("/api/agents").catch(()=>({agents:[]}))]);const resources=Array.isArray(r)?r:(r.resources||[]);const agents=Array.isArray(a)?a:(a.agents||[]);state.instances=await enrich(resources,agents);render()}catch(e){state.instances=[];render();el("instance-summary-text").textContent=`Não foi possível carregar as instâncias: ${e.message}`}finally{if(btn)btn.disabled=false}}
function bind(){el("refresh-instances")?.addEventListener("click",load);el("instance-search")?.addEventListener("input",e=>{state.query=e.target.value;render()});document.querySelectorAll(".cap-filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".cap-filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;render()}))}
async function init(){if(!auth()){location.replace("login.html");return}await loadSidebar();bind();await load()}document.addEventListener("DOMContentLoaded",init);
})();