"use strict";
const $=id=>document.getElementById(id);
const controllerHeaders=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
async function get(path){try{const r=await fetch(`/api${path}`,{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){window.location.replace("/login.html");return null;}if(!r.ok)return null;return await r.json();}catch(e){console.warn("[Capivara System]",path,e);return null;}}
async function post(path,body){const headers={...controllerHeaders(),"Content-Type":"application/json"};try{const r=await fetch(path,{method:"POST",headers,credentials:"same-origin",cache:"no-store",body:JSON.stringify(body||{})});if(r.status===401){window.location.replace("/login.html");return null;}const data=await r.json().catch(()=>({}));return {...data,_ok:r.ok,_status:r.status};}catch(e){return {_ok:false,_status:0,message:"Falha de comunicação com o Controller."};}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function time(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("pt-BR");}
function listOf(data,key){return Array.isArray(data)?data:(Array.isArray(data?.[key])?data[key]:[]);}
function renderUser(user){const role=String(user?.role||"").toLowerCase();$("system-user-name").textContent=user?.username||"Usuário";$("system-user-role").textContent=role;$("current-user").textContent=user?.username||"Sessão ativa";document.querySelectorAll(".admin-only").forEach(e=>e.style.display=["admin","controller"].includes(role)?"":"none");document.querySelectorAll(".agent-manager-only").forEach(e=>e.style.display=["admin","controller"].includes(role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(e=>e.style.display=["admin","controller","client","customer"].includes(role)?"":"none");}
function renderConfigs(data){const rows=listOf(data,"configurations");$("system-config-total").textContent=data?.count??rows.length;$("system-config-list").innerHTML=rows.slice(0,12).map(x=>`<div class="cap-system-row"><strong>${esc(x.namespace||x.key||"Configuração")}</strong><span>${esc(x.scope_type||x.scope||"global")}${x.scope_id?` · ${esc(x.scope_id)}`:""}</span><small>rev ${esc(x.revision??"—")}</small></div>`).join("")||'<div class="cap-empty-state">Nenhuma configuração registrada.</div>';}
function renderTokens(data){const rows=listOf(data,"tokens");$("system-token-total").textContent=data?.count??rows.length;$("system-token-list").innerHTML=rows.slice(0,12).map(x=>{const active=!x.revoked_at&&!x.revoked;return `<div class="cap-system-row"><strong>${esc(x.name||x.token_id||"Token API")}</strong><span>${esc(Array.isArray(x.scopes)?x.scopes.join(", "):(x.scopes||"escopo não informado"))}</span><small class="cap-system-pill ${active?"":"off"}">${active?"Ativo":"Revogado"}</small></div>`;}).join("")||'<div class="cap-empty-state">Nenhum token API registrado.</div>';}
function eventText(e){return e?.message||e?.details||String(e?.type||e?.action||"Evento").replaceAll("_"," ");}
function renderAudit(data){const rows=listOf(data,"events");$("system-audit-total").textContent=rows.length;$("system-audit-list").innerHTML=rows.slice(0,12).map(e=>`<div class="cap-system-row"><strong>${esc(eventText(e))}</strong><span>${esc(e.category||e.source||e.actor||"Sistema")}</span><small>${esc(time(e.timestamp||e.time||e.created_at))}</small></div>`).join("")||'<div class="cap-empty-state">Nenhum evento recente.</div>';}
function renderCurseForge(data){const configured=Boolean(data?.configured),status=$("curseforge-status"),message=$("curseforge-message"),remove=$("curseforge-remove"),test=$("curseforge-test");if(status){status.textContent=configured?"Configurado":"Não configurado";status.classList.toggle("off",!configured);}if(remove)remove.disabled=!configured;if(test)test.disabled=!configured&&!String($("curseforge-key")?.value||"").trim();if(message&&data?.modified_at)message.textContent=`Chave configurada · atualizada em ${time(data.modified_at)}. O valor não é exibido pelo Controller.`;else if(message&&!data?.message)message.textContent="A chave salva nunca é exibida novamente pelo Controller.";}
async function loadCurseForge(){const data=await get("/admin/providers/curseforge");if(data)renderCurseForge(data);}
async function curseforgeAction(action){const input=$("curseforge-key"),message=$("curseforge-message"),key=String(input?.value||"").trim();if(action==="save"&&!key){if(message)message.textContent="Informe a API key do CurseForge.";return;}if(action==="remove"&&!confirm("Remover a API key CurseForge deste Controller?"))return;[$("curseforge-save"),$("curseforge-test"),$("curseforge-remove")].forEach(b=>{if(b)b.disabled=true;});if(message)message.textContent=action==="test"?"Testando conexão com CurseForge...":"Salvando configuração...";const body={action};if(key&&action!=="remove")body.api_key=key;const data=await post("/api/admin/providers/curseforge",body);if(data){renderCurseForge(data);if(message)message.textContent=data.message||(data._ok?"Operação concluída.":"Não foi possível concluir a operação.");if(data._ok&&action==="save"&&input)input.value="";}await loadCurseForge();}
async function refresh(){const [configs,tokens,audit,curseforge]=await Promise.all([get("/configurations?limit=100"),get("/api-tokens"),get("/timeline?limit=50"),get("/admin/providers/curseforge")]);if(configs)renderConfigs(configs);if(tokens)renderTokens(tokens);if(audit)renderAudit(audit);if(curseforge)renderCurseForge(curseforge);}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});}finally{window.location.replace("/login.html");}}
async function loadSidebar(){const target=$("sidebar-component");if(!target)return;const r=await fetch("/components/sidebar-v3.html",{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){window.location.replace("/login.html");return;}if(r.ok)target.innerHTML=await r.text();const button=$("btn-logout");if(button)button.onclick=logout;}
document.addEventListener("DOMContentLoaded",async()=>{await loadSidebar();const user=await get("/whoami");if(user)renderUser(user);$("system-menu-toggle")?.addEventListener("click",()=>{if(window.innerWidth<=760)document.body.classList.toggle("sidebar-open");else document.body.classList.toggle("cap-sidebar-collapsed");});$("system-refresh")?.addEventListener("click",refresh);$("curseforge-save")?.addEventListener("click",()=>curseforgeAction("save"));$("curseforge-test")?.addEventListener("click",()=>curseforgeAction("test"));$("curseforge-remove")?.addEventListener("click",()=>curseforgeAction("remove"));$("curseforge-key")?.addEventListener("input",()=>{const test=$("curseforge-test");if(test)test.disabled=!String($("curseforge-key")?.value||"").trim()&&$("curseforge-status")?.classList.contains("off");});await refresh();});