"use strict";
const $=id=>document.getElementById(id);
const controllerHeaders=()=>({Accept:"application/json","X-Capivara-Auth-Area":"controller"});
const SYSTEM_SECTIONS=new Set(["configuration","api-security","audit"]);
async function get(path){try{const r=await fetch(`/api${path}`,{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.status===401){window.location.replace("/login.html");return null;}if(!r.ok){console.warn("[Capivara System]",path,`HTTP ${r.status}`);return null;}return await r.json();}catch(e){console.warn("[Capivara System]",path,e);return null;}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function time(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString("pt-BR");}
function listOf(data,key){return Array.isArray(data)?data:(Array.isArray(data?.[key])?data[key]:[]);}
function renderUser(user){const role=String(user?.role||"").toLowerCase();$("system-user-name").textContent=user?.username||"Usuário";$("system-user-role").textContent=role;const current=$("current-user");if(current)current.textContent=user?.username||"Sessão ativa";document.querySelectorAll(".admin-only").forEach(e=>e.style.display=["admin","controller"].includes(role)?"":"none");document.querySelectorAll(".agent-manager-only").forEach(e=>e.style.display=["admin","controller"].includes(role)?"":"none");document.querySelectorAll(".instance-manager-only").forEach(e=>e.style.display=["admin","controller","client","customer"].includes(role)?"":"none");}
function renderConfigs(data){const rows=listOf(data,"configurations");$("system-config-total").textContent=data?.count??rows.length;$("system-config-list").innerHTML=rows.slice(0,12).map(x=>`<div class="cap-system-row"><strong>${esc(x.namespace||x.key||"Configuração")}</strong><span>${esc(x.scope_type||x.scope||"global")}${x.scope_id?` · ${esc(x.scope_id)}`:""}</span><small>rev ${esc(x.revision??"—")}</small></div>`).join("")||'<div class="cap-empty-state">Nenhuma configuração registrada.</div>';}
function renderTokens(data){const rows=listOf(data,"tokens");$("system-token-total").textContent=data?.count??rows.length;$("system-token-list").innerHTML=rows.slice(0,12).map(x=>{const active=!x.revoked_at&&!x.revoked;return `<div class="cap-system-row"><strong>${esc(x.name||x.token_id||"Token API")}</strong><span>${esc(Array.isArray(x.scopes)?x.scopes.join(", "):(x.scopes||"escopo não informado"))}</span><small class="cap-system-pill ${active?"":"off"}">${active?"Ativo":"Revogado"}</small></div>`;}).join("")||'<div class="cap-empty-state">Nenhum token API registrado.</div>';}
function eventText(e){return e?.message||e?.details||String(e?.type||e?.action||"Evento").replaceAll("_"," ");}
function renderAudit(data){const rows=listOf(data,"events");$("system-audit-total").textContent=rows.length;$("system-audit-list").innerHTML=rows.slice(0,12).map(e=>`<div class="cap-system-row"><strong>${esc(eventText(e))}</strong><span>${esc(e.category||e.source||e.actor||"Sistema")}</span><small>${esc(time(e.timestamp||e.time||e.created_at))}</small></div>`).join("")||'<div class="cap-empty-state">Nenhum evento recente.</div>';}
function renderUnavailable(id,total,message){const node=$(id);if(node)node.innerHTML=`<div class="cap-empty-state">${esc(message)}</div>`;const counter=$(total);if(counter)counter.textContent="—";}
function activeSection(){const value=String(window.location.hash||"").replace(/^#/,"");return SYSTEM_SECTIONS.has(value)?value:"configuration";}
function applySection(){const selected=activeSection();document.querySelectorAll(".cap-system-card").forEach(section=>{section.hidden=section.id!==selected;});document.querySelectorAll('.cap-sidebar-v3 a[href^="system.html#"],.cap-sidebar-v3 a[href^="/system.html#"]').forEach(link=>{const hash=(link.getAttribute("href")||"").split("#")[1]||"";link.classList.toggle("active",hash===selected);});}
async function refresh(){const [configs,tokens,audit]=await Promise.all([get("/configurations?limit=100"),get("/api-tokens"),get("/timeline?limit=50")]);if(configs)renderConfigs(configs);else renderUnavailable("system-config-list","system-config-total","Configurações indisponíveis no momento.");if(tokens)renderTokens(tokens);else renderUnavailable("system-token-list","system-token-total","API e Segurança indisponíveis no momento.");if(audit)renderAudit(audit);else renderUnavailable("system-audit-list","system-audit-total","Auditoria indisponível no momento.");}
async function logout(){try{await fetch("/api/auth/logout",{method:"POST",headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});}finally{window.location.replace("/login.html");}}
async function loadSidebar(){const target=$("sidebar-component");if(!target)return;const r=await fetch("/components/sidebar-v3.html",{headers:controllerHeaders(),credentials:"same-origin",cache:"no-store"});if(r.ok)target.innerHTML=await r.text();const button=$("btn-logout");if(button)button.onclick=logout;applySection();}
document.addEventListener("DOMContentLoaded",async()=>{await loadSidebar();const user=await get("/whoami");if(user)renderUser(user);$("system-menu-toggle")?.addEventListener("click",()=>{if(window.innerWidth<=760)document.body.classList.toggle("sidebar-open");else document.body.classList.toggle("cap-sidebar-collapsed");});$("system-refresh")?.addEventListener("click",refresh);window.addEventListener("hashchange",applySection);applySection();await refresh();});