(function(){"use strict";
const num=v=>typeof v==="number"&&Number.isFinite(v)?v:null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const at=(o,path)=>path.split(".").reduce((v,k)=>v&&typeof v==="object"?v[k]:undefined,o);
function bytes(v){const n=num(v);if(n===null)return"—";const units=["B","KB","MB","GB","TB"];let x=n,i=0;while(Math.abs(x)>=1024&&i<units.length-1){x/=1024;i++}return`${x>=10||i===0?x.toFixed(0):x.toFixed(1)} ${units[i]}`}
function rate(v){const n=num(v);return n===null?"—":`${bytes(n)}/s`}
function pct(v){const n=num(v);return n===null?"—":`${n.toFixed(1)}%`}
function duration(v){const n=num(v);if(n===null)return"—";const d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60);return d?`${d}d ${h}h`:`${h}h ${m}m`}
function temp(v){const n=num(v);return n===null?"N/D":`${n.toFixed(1)}°C`}
function val(v){const n=num(v);return n===null?"—":String(Math.round(n*100)/100)}
function points(history,path){return(history||[]).map((s,i)=>({x:i,v:num(at(s,path))})).filter(p=>p.v!==null)}
function chart(history,path,color,ceiling){const pts=points(history,path);if(!pts.length)return`<svg class="cap-telemetry-chart ${color}" viewBox="0 0 240 74" preserveAspectRatio="none"><path class="grid" d="M0 18.5H240M0 37H240M0 55.5H240"/></svg>`;let min=Math.min(...pts.map(p=>p.v)),max=Math.max(...pts.map(p=>p.v));if(ceiling!=null){min=0;max=ceiling}else if(max===min){max=min+1}const coords=pts.map((p,i)=>{const x=pts.length===1?0:(i/(pts.length-1))*240;const y=70-((p.v-min)/(max-min))*64;return[x,y]});const line=coords.map((p,i)=>`${i?"L":"M"}${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(" ");const area=`${line} L240 74 L0 74 Z`;return`<svg class="cap-telemetry-chart ${color}" viewBox="0 0 240 74" preserveAspectRatio="none"><path class="grid" d="M0 18.5H240M0 37H240M0 55.5H240"/><path class="area" d="${area}"/><path class="line" d="${line}"/></svg>`}
function card(label,valueText,history,path,color,ceiling,foot=""){return`<article class="cap-telemetry-card"><header><label>${esc(label)}</label></header><strong>${esc(valueText)}</strong>${chart(history,path,color,ceiling)}<small>${esc(foot)}</small></article>`}
function processCards(current,history,processKey,label){const p=current?.[processKey]||{};return`<div class="cap-telemetry-process">${card(`CPU do ${label}`,pct(p.cpu_usage_pct),history,`${processKey}.cpu_usage_pct`,"cap-telemetry-blue",100)}${card(`Memória do ${label}`,bytes(p.memory_rss_bytes),history,`${processKey}.memory_rss_bytes`,"cap-telemetry-purple")}${card(`Threads do ${label}`,val(p.threads),history,`${processKey}.threads`,"cap-telemetry-green")}${card(`PID do ${label}`,val(p.pid),history,`${processKey}.pid`,"cap-telemetry-yellow")}</div>`}
function topTable(current,label){const rows=Array.isArray(current?.top_processes)?current.top_processes:[];return`<div class="cap-telemetry-table-wrap"><h3>Processos (${label}) · Top 5 por CPU</h3>${rows.length?`<table class="cap-telemetry-table"><thead><tr><th>Processo</th><th>PID</th><th>CPU</th><th>RAM</th><th>Threads</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name||"—")}</td><td>${esc(r.pid??"—")}</td><td>${esc(pct(r.cpu_usage_pct))}</td><td>${esc(bytes(r.memory_rss_bytes))}</td><td>${esc(r.threads??"—")}</td></tr>`).join("")}</tbody></table>`:`<div class="cap-telemetry-empty">Nenhum processo disponível nesta amostra.</div>`}</div>`}
function render(container,current,history,options={}){if(!container)return;const processKey=options.processKey||"agent",label=options.label||"Agent",host=current?.host||{},mem=host.memory||{},disk=host.disk||{},net=host.network||{},load=host.load_average||{};const collected=current?.collected_at_unix?new Date(current.collected_at_unix*1000).toLocaleTimeString("pt-BR"):"—";container.innerHTML=`<div class="cap-telemetry-head"><div><h2>Telemetria ${esc(label)}</h2><p>${esc(options.description||"Consumo do host e do processo em execução.")}</p></div><div class="cap-telemetry-meta"><span>Atualização: ${esc(collected)}</span><span>${history?.length||0} amostras</span></div></div><div class="cap-telemetry-grid">${card("CPU",pct(host.cpu_usage_pct),history,"host.cpu_usage_pct","cap-telemetry-blue",100)}${card("Memória (RAM)",`${bytes(mem.used_bytes)} / ${bytes(mem.total_bytes)}`,history,"host.memory.usage_pct","cap-telemetry-purple",100,pct(mem.usage_pct))}${card("Disco",`${pct(disk.usage_pct)} · ${bytes(disk.used_bytes)} / ${bytes(disk.total_bytes)}`,history,"host.disk.usage_pct","cap-telemetry-green",100)}${card("Load Average",`${val(load["1m"])} / ${val(load["5m"])} / ${val(load["15m"])}`,history,"host.load_average.1m","cap-telemetry-yellow")}${card("Uptime",duration(host.uptime_seconds),history,"host.uptime_seconds","cap-telemetry-blue")}${card("Rede recebida",rate(net.rx_bytes_per_second),history,"host.network.rx_bytes_per_second","cap-telemetry-green",null,`Total: ${bytes(net.rx_bytes)}`)}${card("Rede enviada",rate(net.tx_bytes_per_second),history,"host.network.tx_bytes_per_second","cap-telemetry-blue",null,`Total: ${bytes(net.tx_bytes)}`)}${card("Temperatura (CPU)",temp(host.temperature_c),history,"host.temperature_c","cap-telemetry-red",null,host.temperature_c==null?"Sensor não disponível":"")}</div>${processCards(current,history,processKey,label)}${topTable(current,label)}`}
window.CapivaraTelemetry={render};
})();
