(function(){"use strict";
const num=v=>typeof v==="number"&&Number.isFinite(v)?v:null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const at=(o,path)=>path.split(".").reduce((v,k)=>v&&typeof v==="object"?v[k]:undefined,o);
function bytes(v){const n=num(v);if(n===null)return"—";const units=["B","KB","MB","GB","TB"];let x=n,i=0;while(Math.abs(x)>=1024&&i<units.length-1){x/=1024;i++}return`${x>=10||i===0?x.toFixed(0):x.toFixed(1)} ${units[i]}`}
function rate(v){const n=num(v);return n===null?"N/D":`${bytes(n)}/s`}
function pct(v){const n=num(v);return n===null?"—":`${n.toFixed(1)}%`}
function duration(v){const n=num(v);if(n===null)return"—";const d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60);return d?`${d}d ${h}h`:`${h}h ${m}m`}
function temp(v){const n=num(v);return n===null?"N/D":`${n.toFixed(1)}°C`}
function val(v){const n=num(v);return n===null?"—":String(Math.round(n*100)/100)}
function points(history,path){return(history||[]).map((s,i)=>({x:i,v:num(at(s,path))})).filter(p=>p.v!==null)}
function chart(history,path,color,ceiling){const pts=points(history,path);if(!pts.length)return`<svg class="cap-telemetry-chart ${color}" viewBox="0 0 240 74" preserveAspectRatio="none"><path class="grid" d="M0 18.5H240M0 37H240M0 55.5H240"/></svg>`;let min=Math.min(...pts.map(p=>p.v)),max=Math.max(...pts.map(p=>p.v));if(ceiling!=null){min=0;max=ceiling}else if(max===min){max=min+1}const coords=pts.map((p,i)=>{const x=pts.length===1?0:(i/(pts.length-1))*240;const y=70-((p.v-min)/(max-min))*64;return[x,y]});const line=coords.map((p,i)=>`${i?"L":"M"}${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(" ");const area=`${line} L240 74 L0 74 Z`;return`<svg class="cap-telemetry-chart ${color}" viewBox="0 0 240 74" preserveAspectRatio="none"><path class="grid" d="M0 18.5H240M0 37H240M0 55.5H240"/><path class="area" d="${area}"/><path class="line" d="${line}"/></svg>`}
function card(label,valueText,history,path,color,ceiling,foot=""){return`<article class="cap-telemetry-card"><header><label>${esc(label)}</label></header><strong>${esc(valueText)}</strong>${chart(history,path,color,ceiling)}<small>${esc(foot)}</small></article>`}
function mergeSample(current,history){const latest=Array.isArray(history)&&history.length?history[history.length-1]:{};return{...current,...latest,host:{...(current?.host||{}),...(latest?.host||{}),memory:{...(current?.host?.memory||{}),...(latest?.host?.memory||{})},disk:{...(current?.host?.disk||{}),...(latest?.host?.disk||{})},network:{...(current?.host?.network||{}),...(latest?.host?.network||{})},load_average:{...(current?.host?.load_average||{}),...(latest?.host?.load_average||{})}},agent:{...(current?.agent||{}),...(latest?.agent||{})},node_activity:{...(current?.node_activity||{}),...(latest?.node_activity||{})},storage_pools:Array.isArray(current?.storage_pools)?current.storage_pools:(Array.isArray(latest?.storage_pools)?latest.storage_pools:[]),instance_telemetry:Array.isArray(current?.instance_telemetry)?current.instance_telemetry:(Array.isArray(latest?.instance_telemetry)?latest.instance_telemetry:[]),top_processes:Array.isArray(current?.top_processes)?current.top_processes:(Array.isArray(latest?.top_processes)?latest.top_processes:[])};}
function aggregateActivity(sample){const host=sample?.host||{},disk=host.disk||{},net=host.network||{},explicit=sample?.node_activity||{},instances=Array.isArray(sample?.instance_telemetry)?sample.instance_telemetry:[],pools=Array.isArray(sample?.storage_pools)?sample.storage_pools:[];const sum=(rows,key)=>rows.reduce((total,row)=>{const n=num(row?.[key]);return total+(n===null?0:n)},0);const knownPlayers=instances.filter(row=>num(row?.players_online)!==null),knownCapacity=instances.filter(row=>num(row?.players_max)!==null);const poolFree=pools.reduce((total,row)=>{const n=num(row?.free_bytes??row?.usable_bytes);return total+(n===null?0:n)},0);const healthy=instances.filter(row=>String(row?.health||"").toLowerCase()==="healthy").length;return{players_online:num(explicit.players_online)??(knownPlayers.length?sum(knownPlayers,"players_online"):null),players_capacity:num(explicit.players_capacity)??(knownCapacity.length?sum(knownCapacity,"players_max"):null),instances_running:num(explicit.instances_running)??(instances.length?healthy:null),instances_total:num(explicit.instances_total)??(instances.length?instances.length:null),storage_free_bytes:num(explicit.storage_free_bytes)??num(disk.free_bytes)??(pools.length?poolFree:null),storage_used_bytes:num(explicit.storage_used_bytes)??num(disk.used_bytes),network_rx_bytes_per_second:num(explicit.network_rx_bytes_per_second)??num(net.rx_bytes_per_second),network_tx_bytes_per_second:num(explicit.network_tx_bytes_per_second)??num(net.tx_bytes_per_second),disk_read_bytes_per_second:num(explicit.disk_read_bytes_per_second)??num(disk.read_bytes_per_second),disk_write_bytes_per_second:num(explicit.disk_write_bytes_per_second)??num(disk.write_bytes_per_second)};}
function processCards(current,history,processKey,label){const p=current?.[processKey]||{};return`<div class="cap-telemetry-process">${card(`CPU do ${label}`,pct(p.cpu_usage_pct),history,`${processKey}.cpu_usage_pct`,"cap-telemetry-blue",100)}${card(`Memória do ${label} (RAM)`,bytes(p.memory_rss_bytes),history,`${processKey}.memory_rss_bytes`,"cap-telemetry-purple")}${card(`Threads do ${label}`,val(p.threads),history,`${processKey}.threads`,"cap-telemetry-green")}${card(`PID do ${label}`,val(p.pid),history,`${processKey}.pid`,"cap-telemetry-yellow")}</div>`}
function activityCards(sample,history){const a=aggregateActivity(sample),playersFoot=a.players_capacity===null?"Capacidade não publicada":`${val(a.players_online)} / ${val(a.players_capacity)} slots`,instancesFoot=a.instances_total===null?"Inventário não publicado":`${val(a.instances_running)} / ${val(a.instances_total)} instâncias saudáveis`;return`<div class="cap-telemetry-grid">${card("Players online",val(a.players_online),history,"node_activity.players_online","cap-telemetry-blue",null,playersFoot)}${card("Capacidade de players",val(a.players_capacity),history,"node_activity.players_capacity","cap-telemetry-purple",null,playersFoot)}${card("Instâncias ativas",val(a.instances_running),history,"node_activity.instances_running","cap-telemetry-green",null,instancesFoot)}${card("Armazenamento livre",bytes(a.storage_free_bytes),history,"node_activity.storage_free_bytes","cap-telemetry-yellow",null,a.storage_used_bytes===null?"":`Usado: ${bytes(a.storage_used_bytes)}`)}${card("Rede recebida",rate(a.network_rx_bytes_per_second),history,"host.network.rx_bytes_per_second","cap-telemetry-green")}${card("Rede enviada",rate(a.network_tx_bytes_per_second),history,"host.network.tx_bytes_per_second","cap-telemetry-blue")}${card("Disco · leitura",rate(a.disk_read_bytes_per_second),history,"host.disk.read_bytes_per_second","cap-telemetry-purple",null,a.disk_read_bytes_per_second===null?"Coletor de I/O não disponível":"")}${card("Disco · escrita",rate(a.disk_write_bytes_per_second),history,"host.disk.write_bytes_per_second","cap-telemetry-yellow",null,a.disk_write_bytes_per_second===null?"Coletor de I/O não disponível":"")}</div>`}
function topTable(current,label){const rows=Array.isArray(current?.top_processes)?current.top_processes:[];return`<div class="cap-telemetry-table-wrap"><h3>Processos do ${esc(label)} (Top 5 por CPU)</h3>${rows.length?`<table class="cap-telemetry-table"><thead><tr><th>Processo</th><th>PID</th><th>CPU %</th><th>RAM</th><th>Threads</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name||"—")}</td><td>${esc(r.pid??"—")}</td><td>${esc(pct(r.cpu_usage_pct))}</td><td>${esc(bytes(r.memory_rss_bytes))}</td><td>${esc(r.threads??"—")}</td></tr>`).join("")}</tbody></table>`:`<div class="cap-telemetry-empty">Nenhum processo do ${esc(label)} disponível nesta amostra.</div>`}</div>`}
function sectionHead(title,description,meta=""){return`<div class="cap-telemetry-head"><div><h2>${esc(title)}</h2><p>${esc(description)}</p></div>${meta}</div>`}
function render(container,current,history,options={}){if(!container)return;const processKey=options.processKey||"agent",label=options.label||"Agent",sample=mergeSample(current||{},history||[]),host=sample.host||{},mem=host.memory||{},disk=host.disk||{},net=host.network||{},load=host.load_average||{};const collected=sample.collected_at_unix?new Date(sample.collected_at_unix*1000).toLocaleTimeString("pt-BR"):"—";const meta=`<div class="cap-telemetry-meta"><span>Atualização: ${esc(collected)}</span><span>${history?.length||0} amostras</span></div>`;container.innerHTML=`<section class="cap-telemetry-block">${sectionHead("Telemetria do computador","Consumo total do host físico ou virtual onde o Agent está executando.",meta)}<div class="cap-telemetry-grid">${card("CPU",pct(host.cpu_usage_pct),history,"host.cpu_usage_pct","cap-telemetry-blue",100)}${card("Memória (RAM)",`${bytes(mem.used_bytes)} / ${bytes(mem.total_bytes)}`,history,"host.memory.usage_pct","cap-telemetry-purple",100,pct(mem.usage_pct))}${card("Disco",`${pct(disk.usage_pct)} · ${bytes(disk.used_bytes)} / ${bytes(disk.total_bytes)}`,history,"host.disk.usage_pct","cap-telemetry-green",100)}${card("Load Average",`${val(load["1m"])} / ${val(load["5m"])} / ${val(load["15m"])}`,history,"host.load_average.1m","cap-telemetry-yellow")}${card("Uptime",duration(host.uptime_seconds),history,"host.uptime_seconds","cap-telemetry-blue")}${card("Rede recebida",rate(net.rx_bytes_per_second),history,"host.network.rx_bytes_per_second","cap-telemetry-green",null,`Total: ${bytes(net.rx_bytes)}`)}${card("Rede enviada",rate(net.tx_bytes_per_second),history,"host.network.tx_bytes_per_second","cap-telemetry-blue",null,`Total: ${bytes(net.tx_bytes)}`)}${card("Temperatura (CPU)",temp(host.temperature_c),history,"host.temperature_c","cap-telemetry-red",null,host.temperature_c==null?"Sensor não disponível":"")}</div></section><section class="cap-telemetry-block">${sectionHead(`Telemetria do Capivara ${label}`,`Consumo exclusivo do processo do ${label}, separado do restante da máquina.`)}${processCards(sample,history,processKey,label)}</section><section class="cap-telemetry-block">${sectionHead("Capacidade e atividade do Node","Carga operacional agregada das instâncias hospedadas neste Agent: players, armazenamento, rede e atividade de disco.")}${activityCards(sample,history)}</section>${topTable(sample,label)}`}
window.CapivaraTelemetry={render};
})();
