-- =============================================================
-- Capivara Distributed Server Manager
-- PostgreSQL Migration 001
-- Initial persistence model
-- =============================================================

CREATE TABLE nodes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,

    role TEXT NOT NULL
        CHECK (
            role IN (
                'controller',
                'agent',
                'hybrid'
            )
        ),

    status TEXT NOT NULL
        DEFAULT 'pending',

    metadata_json JSONB NOT NULL
        DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE instances (
    id TEXT PRIMARY KEY,

    node_id TEXT,

    game_id TEXT NOT NULL,

    edition TEXT,
    runtime_id TEXT,
    version TEXT,

    name TEXT NOT NULL,

    status TEXT NOT NULL
        DEFAULT 'unknown',

    manifest_path TEXT,

    metadata_json JSONB NOT NULL
        DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_instances_node
        FOREIGN KEY (node_id)
        REFERENCES nodes(id)
        ON DELETE SET NULL
);


CREATE TABLE operations (
    id TEXT PRIMARY KEY,

    operation_type TEXT NOT NULL,
    status TEXT NOT NULL,

    node_id TEXT,
    instance_id TEXT,

    request_json JSONB NOT NULL
        DEFAULT '{}'::jsonb,

    result_json JSONB,

    error_code TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_operations_node
        FOREIGN KEY (node_id)
        REFERENCES nodes(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_operations_instance
        FOREIGN KEY (instance_id)
        REFERENCES instances(id)
        ON DELETE SET NULL
);


CREATE TABLE events (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    event_id TEXT UNIQUE,

    event_type TEXT NOT NULL,

    severity TEXT NOT NULL
        DEFAULT 'info',

    source TEXT NOT NULL,

    node_id TEXT,
    instance_id TEXT,
    operation_id TEXT,

    payload_json JSONB NOT NULL
        DEFAULT '{}'::jsonb,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_events_node
        FOREIGN KEY (node_id)
        REFERENCES nodes(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_events_instance
        FOREIGN KEY (instance_id)
        REFERENCES instances(id)
        ON DELETE SET NULL,

    CONSTRAINT fk_events_operation
        FOREIGN KEY (operation_id)
        REFERENCES operations(id)
        ON DELETE SET NULL
);


CREATE TABLE content_installations (
    instance_id TEXT NOT NULL,
    content_id TEXT NOT NULL,

    content_type TEXT NOT NULL,
    version TEXT NOT NULL,

    status TEXT NOT NULL
        DEFAULT 'installed',

    lock_path TEXT,

    installed_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (
        instance_id,
        content_id
    ),

    CONSTRAINT fk_content_installations_instance
        FOREIGN KEY (instance_id)
        REFERENCES instances(id)
        ON DELETE CASCADE
);


CREATE INDEX idx_instances_node_game
    ON instances(
        node_id,
        game_id
    );

CREATE INDEX idx_operations_status_created
    ON operations(
        status,
        created_at
    );

CREATE INDEX idx_events_created
    ON events(
        created_at
    );

CREATE INDEX idx_events_instance_created
    ON events(
        instance_id,
        created_at
    );

CREATE INDEX idx_content_instance_status
    ON content_installations(
        instance_id,
        status
    );
