-- =============================================================
-- Capivara Distributed Server Manager
-- PostgreSQL Migration 005
-- Dashboard users, access control and audit
-- =============================================================

CREATE TABLE dashboard_users (
    username TEXT PRIMARY KEY,

    password_hash TEXT NOT NULL,

    role TEXT NOT NULL
        CHECK (
            role IN (
                'admin',
                'controller',
                'customer',
                'operator'
            )
        ),

    scope_id TEXT,

    active BOOLEAN NOT NULL
        DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE instance_access (
    username TEXT NOT NULL,

    instance_id TEXT NOT NULL,

    permission_profile TEXT NOT NULL
        DEFAULT 'viewer'
        CHECK (
            permission_profile IN (
                'viewer',
                'operator',
                'manager'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (
        username,
        instance_id
    ),

    CONSTRAINT fk_instance_access_user
        FOREIGN KEY (username)
        REFERENCES dashboard_users(username)
        ON DELETE CASCADE,

    CONSTRAINT fk_instance_access_instance
        FOREIGN KEY (instance_id)
        REFERENCES instances(id)
        ON DELETE CASCADE
);


CREATE TABLE audit_log (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    username TEXT NOT NULL,

    instance_id TEXT,

    action TEXT NOT NULL,
    result TEXT NOT NULL,

    details TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


CREATE INDEX idx_dashboard_users_role_scope
    ON dashboard_users(
        role,
        scope_id,
        active
    );

CREATE INDEX idx_audit_log_instance_created
    ON audit_log(
        instance_id,
        created_at
    );
