-- =============================================================
-- Capivara Distributed Server Manager
-- PostgreSQL Migration 010
-- Alert persistence
-- =============================================================


-- =============================================================
-- ALERTS
-- =============================================================

CREATE TABLE alerts (
    id TEXT PRIMARY KEY,

    scope TEXT NOT NULL
        CHECK (
            scope IN (
                'controller',
                'agent',
                'node',
                'instance'
            )
        ),

    controller_id TEXT,
    agent_id TEXT,
    node_id TEXT,
    instance_id TEXT,

    rule_id TEXT NOT NULL,

    level TEXT NOT NULL
        CHECK (
            level IN (
                'INFO',
                'WARNING',
                'CRITICAL'
            )
        ),

    state TEXT NOT NULL
        CHECK (
            state IN (
                'OPEN',
                'ACKNOWLEDGED',
                'RESOLVED',
                'SUPPRESSED'
            )
        ),

    message TEXT NOT NULL,

    opened_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    suppressed_until TIMESTAMPTZ,

    CONSTRAINT fk_alerts_controller
        FOREIGN KEY (controller_id)
        REFERENCES controllers(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_alerts_agent
        FOREIGN KEY (agent_id)
        REFERENCES agents(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_alerts_node
        FOREIGN KEY (node_id)
        REFERENCES nodes(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_alerts_instance
        FOREIGN KEY (instance_id)
        REFERENCES instances(id)
        ON DELETE RESTRICT
);


-- =============================================================
-- ALERT EVENTS
-- =============================================================

CREATE TABLE alert_events (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    alert_id TEXT NOT NULL,

    action TEXT NOT NULL
        CHECK (
            action IN (
                'OPEN',
                'REOPEN',
                'ESCALATE',
                'ACK',
                'RESOLVE',
                'SUPPRESS'
            )
        ),

    level TEXT NOT NULL
        CHECK (
            level IN (
                'INFO',
                'WARNING',
                'CRITICAL'
            )
        ),

    old_state TEXT,

    new_state TEXT NOT NULL
        CHECK (
            new_state IN (
                'OPEN',
                'ACKNOWLEDGED',
                'RESOLVED',
                'SUPPRESSED'
            )
        ),

    message TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_alert_events_alert
        FOREIGN KEY (alert_id)
        REFERENCES alerts(id)
        ON DELETE CASCADE
);


-- =============================================================
-- ALERT SCOPE INTEGRITY
-- =============================================================

CREATE OR REPLACE FUNCTION
validate_alert_scope()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN

    IF NEW.scope = 'controller'
       AND NEW.controller_id IS NULL
    THEN
        RAISE EXCEPTION
            'alert_controller_scope_requires_controller';
    END IF;


    IF NEW.scope = 'agent'
       AND (
           NEW.controller_id IS NULL
           OR NEW.agent_id IS NULL
       )
    THEN
        RAISE EXCEPTION
            'alert_agent_scope_requires_controller_agent';
    END IF;


    IF NEW.scope = 'node'
       AND (
           NEW.controller_id IS NULL
           OR NEW.node_id IS NULL
       )
    THEN
        RAISE EXCEPTION
            'alert_node_scope_requires_controller_node';
    END IF;


    IF NEW.scope = 'instance'
       AND (
           NEW.controller_id IS NULL
           OR NEW.agent_id IS NULL
           OR NEW.node_id IS NULL
           OR NEW.instance_id IS NULL
       )
    THEN
        RAISE EXCEPTION
            'alert_instance_scope_requires_controller_agent_node_instance';
    END IF;


    IF NEW.agent_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM agents
           WHERE id = NEW.agent_id
             AND controller_id = NEW.controller_id
       )
    THEN
        RAISE EXCEPTION
            'alert_agent_controller_mismatch';
    END IF;


    IF NEW.instance_id IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM instances
           WHERE id = NEW.instance_id
             AND controller_id = NEW.controller_id
             AND agent_id = NEW.agent_id
             AND node_id = NEW.node_id
       )
    THEN
        RAISE EXCEPTION
            'alert_instance_ownership_mismatch';
    END IF;


    RETURN NEW;
END;
$$;


CREATE TRIGGER alerts_validate_scope_insert
BEFORE INSERT
ON alerts
FOR EACH ROW
EXECUTE FUNCTION validate_alert_scope();


CREATE TRIGGER alerts_validate_scope_update
BEFORE UPDATE OF
    scope,
    controller_id,
    agent_id,
    node_id,
    instance_id
ON alerts
FOR EACH ROW
EXECUTE FUNCTION validate_alert_scope();


-- =============================================================
-- ACTIVE ALERT DEDUPLICATION
-- =============================================================

CREATE UNIQUE INDEX idx_alerts_active_controller
    ON alerts(
        rule_id,
        controller_id
    )
    WHERE
        scope = 'controller'
        AND state <> 'RESOLVED';


CREATE UNIQUE INDEX idx_alerts_active_agent
    ON alerts(
        rule_id,
        controller_id,
        agent_id
    )
    WHERE
        scope = 'agent'
        AND state <> 'RESOLVED';


CREATE UNIQUE INDEX idx_alerts_active_node
    ON alerts(
        rule_id,
        controller_id,
        node_id
    )
    WHERE
        scope = 'node'
        AND state <> 'RESOLVED';


CREATE UNIQUE INDEX idx_alerts_active_instance
    ON alerts(
        rule_id,
        controller_id,
        agent_id,
        node_id,
        instance_id
    )
    WHERE
        scope = 'instance'
        AND state <> 'RESOLVED';


-- =============================================================
-- INDEXES — ALERTS
-- =============================================================

CREATE INDEX idx_alerts_state
    ON alerts(state);

CREATE INDEX idx_alerts_level
    ON alerts(level);

CREATE INDEX idx_alerts_rule
    ON alerts(rule_id);

CREATE INDEX idx_alerts_controller
    ON alerts(controller_id);

CREATE INDEX idx_alerts_agent
    ON alerts(agent_id);

CREATE INDEX idx_alerts_node
    ON alerts(node_id);

CREATE INDEX idx_alerts_instance
    ON alerts(instance_id);

CREATE INDEX idx_alerts_scope_state
    ON alerts(
        scope,
        state
    );


-- =============================================================
-- INDEXES — ALERT EVENTS
-- =============================================================

CREATE INDEX idx_alert_events_alert
    ON alert_events(alert_id);

CREATE INDEX idx_alert_events_created
    ON alert_events(created_at);

CREATE INDEX idx_alert_events_action
    ON alert_events(action);
