
-- =============================================================
-- Capivara Distributed Server Manager
-- PostgreSQL Migration 011
-- Agent managed network port ranges
-- =============================================================

CREATE TABLE agent_port_ranges (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    agent_id TEXT NOT NULL,

    protocol TEXT NOT NULL
        CHECK (protocol IN ('tcp', 'udp')),

    start_port INTEGER NOT NULL
        CHECK (start_port BETWEEN 1 AND 65535),

    end_port INTEGER NOT NULL
        CHECK (end_port BETWEEN 1 AND 65535),

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled')),

    label TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_agent_port_ranges_order
        CHECK (start_port <= end_port),

    CONSTRAINT fk_agent_port_ranges_agent
        FOREIGN KEY (agent_id)
        REFERENCES agents(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_agent_port_ranges
        UNIQUE (
            agent_id,
            protocol,
            start_port,
            end_port
        )
);

CREATE INDEX idx_agent_port_ranges_agent
    ON agent_port_ranges(agent_id);

CREATE INDEX idx_agent_port_ranges_lookup
    ON agent_port_ranges(
        agent_id,
        protocol,
        status,
        start_port,
        end_port
    );

INSERT INTO agent_port_ranges(
    agent_id,
    protocol,
    start_port,
    end_port,
    status,
    label
)
SELECT
    id,
    'udp',
    24000,
    24999,
    'active',
    'default'
FROM agents;

INSERT INTO agent_port_ranges(
    agent_id,
    protocol,
    start_port,
    end_port,
    status,
    label
)
SELECT
    id,
    'tcp',
    24000,
    24999,
    'active',
    'default'
FROM agents;

CREATE OR REPLACE FUNCTION
    capivara_agents_default_port_ranges()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO agent_port_ranges(
        agent_id,
        protocol,
        start_port,
        end_port,
        status,
        label
    )
    VALUES
        (
            NEW.id,
            'udp',
            24000,
            24999,
            'active',
            'default'
        ),
        (
            NEW.id,
            'tcp',
            24000,
            24999,
            'active',
            'default'
        );

    RETURN NEW;
END;
$$;

CREATE TRIGGER agents_default_port_ranges_insert
AFTER INSERT ON agents
FOR EACH ROW
EXECUTE FUNCTION
    capivara_agents_default_port_ranges();
