#!/usr/bin/env bash

GAME_ID="arma3"

GAME_NAME="Arma 3"

ENGINE="Real Virtuality"

EXECUTABLE="arma3server"

APPID_SERVER="233780"

PROFILE_PATH="profiles"

MOD_PATH="@mods"

LOG_EXTENSION=".RPT"

MOD_PREFIX="@"

INSTALL_DIR="/home/arma3/serverfiles"

SAVE_DIR="${INSTALL_DIR}"

LOG_DIR="${INSTALL_DIR}/profiles"

CONFIG_FILE="server.cfg"